### ISSUE TITLE
Support for firmware update

### ISSUE THREAD

**Issue by kunyi731** [metal3-io/baremetal-operator#1001]
Hello,

I wonder whether there is currently a plan to support firmware update/upgrade actions in Metal3 baremetal operator? I saw there are firmware field with several configurations that seem like very particular BIOS settings, but didn't see anything mentioned about firmware updates.

Looks like Ironic Redfish driver supports firmware update as [a custom cleaning step](https://docs.openstack.org/ironic/latest/admin/drivers/redfish.html#firmware-update-using-manual-cleaning).

Thanks a lot!

**Comment by dtantsur** [comment]
I don't have objections, but someone needs to write a design document and drive the work.
