### ISSUE TITLE
Add PreprovisioningImage documentation

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/baremetal-operator#1009]
Recently PreprovisioningImage API https://github.com/metal3-io/baremetal-operator/pull/936 landed and
we need to add some documentation to explain how
to use it, turn on/off controller and etc. Adding this
task here so that we don't forget to add documentation.

/kind documentation
/priority important-soon

**Comment by s3rj1k** [comment]
I have a question regarding this [change](https://github.com/metal3-io/baremetal-operator/commit/42db90bf6938eb9905e7518c5d258b83ef434573), I assume this is related to docs.

Why do we consider all labels as Preprovision labels?
cc: @dtantsur

**Comment by s3rj1k** [comment]
This commit should explain that https://github.com/metal3-io/baremetal-operator/commit/363ab1782bb0c395bbec7ff395856d47076452c7

**Comment by zaneb** [comment]
Yeah, it's up to downstreams to build their own controller, so we can't hard-code any list of labels. The default controller provided in metal³ doesn't care about _any_ labels.

**Comment by s3rj1k** [comment]
> Yeah, it's up to downstreams to build their own controller, so we can't hard-code any list of labels. The default controller provided in metal³ doesn't care about _any_ labels.

Initially I assumed that this could be somehow filtered by key label suffix or prefix or gTLD label part :)

**Comment by Rozzii** [comment]
/remove-lifecycle stale 
We would need to convert this to a metal3-docs User-Guide issue.
