### ISSUE TITLE
Unable to introspect node and modify BIOS parameterts via baremetal operator

### ISSUE THREAD

**Issue by maheshd2** [metal3-io/baremetal-operator#1016]
We are trying to configure baremetal operator on the OCP cluster 4.8 and verify

    Adding baremetal host
    Configuring the BIOS settings
    Introspecting the baremetal host
    Booting the OS

And we followed the doc (https://github.com/metal3-io/baremetal-operator), it explains setting up baremetal operator with minikube/virtual bmc environment. We need the instructions for setting up baremetal operator with ironic on a regular OCP cluster.

We still followed above document and tried configuring the baremetal-operator on our OCP cluster with default values.
After that we were able to deploy the baremetalhost CR by following doc https://github.com/metal3-io/baremetal-operator/blob/master/docs/api.md

We are able to power on/off the baremetal host. But we see following error for the firmware field.
```
error: error validating "baremetalhost-9-37-131-45.yaml": error validating data: ValidationError(BareMetalHost.spec): unknown field "firmware" in io.metal3.v1alpha1.BareMetalHost.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
Further we see that there is no introspection happening on the baremetal host. But the node reflects final state as 'Provisioned'.

**Comment by maheshd2** [comment]
We opened a redhat support ticket and received following response.
```
After looking at the case description and shared context, I am able to understand that you are trying to configure baremetal operator on the OCP cluster 4.8 by following doc[https://github.com/metal3-io/baremetal-operator].

First of all, I want to highlight here the doc you are referring to is the upstream solution doc for bare-metal, We at Red Hat don't support solutions from upstream that are not tested integrations[0], Also I checked there is no operator listed by metal3 on OperatorHub.

[0] - https://access.redhat.com/articles/4763741

Let's come to the solution you referred to and why not worked?.
- After checking https://github.com/metal3-io/baremetal-operator/blob/master/docs/api.md the API is made for minikube/virtual bmc environment but as there is no set of instructions for openshift for same, You need to open an issue at respective documentation GitHub repo[https://github.com/metal3-io/baremetal-operator/issues] for accessing same furthermore they might help here.
```

**Comment by dtantsur** [comment]
Hi! Please report OpenShift issues to the Red Hat bugzilla. In you case, BIOS settings were not supported in 4.8 (nor in 4.9, if I recall correctly, cc @bfournie)

/close
