### ISSUE TITLE
Need installation steps for BOM on an existing management cluster

### ISSUE THREAD

**Issue by dramasamy** [metal3-io/baremetal-operator#1024]
The document doesn't have any steps to install BOM on existing clusters, Can we add that? Please let me know where I can find that info.

I hope 'https://github.com/metal3-io/metal3-helm-chart' is the helm repo.

**Comment by dramasamy** [comment]
`dramasamy@dev01:~/metal3-helm-chart/charts/baremetal-operator$ helm install -n bom bom .
W1116 13:30:49.342176  416636 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: INSTALLATION FAILED: create: failed to create: namespaces "bom" not found`

**Comment by dramasamy** [comment]
`
dramasamy@dev01:~/metal3-helm-chart$ pwd
/home/dramasamy/metal3-helm-chart

helm install -n metal3 metal3 .
NAME: metal3
LAST DEPLOYED: Tue Nov 16 13:37:13 2021
NAMESPACE: metal3
STATUS: deployed
REVISION: 1
TEST SUITE: None 

`

`
NAMESPACE                 NAME                                                          READY   STATUS             RESTARTS   AGE     IP           NODE                 NOMINATED NODE   READINESS GATES
default                   cabpk-controller-manager-5b787fb859-9ttzz                     2/2     Running            0          2m18s   10.244.2.6   kind-worker          <none>           <none>
default                   capbm-controller-manager-0                                    2/2     Running            0          2m18s   10.244.2.5   kind-worker          <none>           <none>
default                   cluster-api-controller-manager-0                              1/1     Running            0          2m18s   10.244.2.4   kind-worker          <none>           <none>
default                   ironic-7669fd8c97-84ljm                                       3/5     CrashLoopBackOff   8          2m18s   172.18.0.3   kind-worker2         <none>           <none>
default                   metal3-baremetal-operator-59dc8f599f-jjcfd                    2/3     CrashLoopBackOff   4          2m18s   10.244.1.2   kind-worker2         <none>           <none>
hardware-classification   hardware-classification-controller-manager-6565b4654f-f4mdq   1/1     Running            0          2m18s   10.244.2.3   kind-worker          <none>           <none>
`

`
{"level":"error","ts":1637091488.1551936,"logger":"controller.hostfirmwaresettings","msg":"Could not wait for Cache to sync","reconciler group":"metal3.io","reconciler kind":"HostFirmwareSettings","error":"failed to wait for hostfirmwaresettings caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/manager/internal.go:696"}
{"level":"error","ts":1637091488.1552877,"msg":"error received after stop sequence was engaged","error":"failed to wait for hostfirmwaresettings caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1637091488.1553273,"logger":"controller.baremetalhost","msg":"Could not wait for Cache to sync","reconciler group":"metal3.io","reconciler kind":"BareMetalHost","error":"failed to wait for baremetalhost caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:221\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/manager/internal.go:696"}
{"level":"error","ts":1637091488.1553454,"logger":"setup","msg":"problem running manager","error":"open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}
`

**Comment by zhouhao3** [comment]
> The document doesn't have any steps to install BOM on existing clusters, Can we add that? Please let me know where I can find that info.

You can find related content `5. Install operator in the cluster` in this [document](https://github.com/metal3-io/baremetal-operator/blob/master/docs/dev-setup.md).

**Comment by Rozzii** [comment]
/triage accepted
In case the answer was sufficient then please @dramasamy close the ticket with the "/close" command.
