### ISSUE TITLE
Clean up ironic deployment manifests

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/baremetal-operator#1072]
The [ironic-deployment](https://github.com/metal3-io/baremetal-operator/tree/main/ironic-deployment) files are currently [treated with `envsubst`](https://github.com/metal3-io/baremetal-operator/blob/7125c9160a005b0ae92b9c7aac8d87812e352cf7/tools/deploy.sh#L28-L53) in order to inject some values from environment variables. This can be warranted in some situations (e.g. in the [ironic-auth-config-tpl](https://github.com/metal3-io/baremetal-operator/blob/main/ironic-deployment/basic-auth/ironic-auth-config-tpl)) but most of the time it is just replacing the `${NAMEPREFIX}`. This is not at all necessary, as can be seen in the BMO manifests where it is not used.

We should get rid of unnecessary use of `envsubst` and make the Ironic manifests treated similar to how the BMO manifests are.

**Comment by Rozzii** [comment]
NOTE to everybody: Fell free to work on this and contact/ping @lentzi90  if you have any question!
