### ISSUE TITLE
Failures in ironic httpd probes 

### ISSUE THREAD

**Issue by mel1nn** [metal3-io/baremetal-operator#1114]
Using the last version of ironic (capm3-v1.1.1), the probes of the ironic-httpd container fail : 
`Warning  Unhealthy  6s (x2 over 36s)  kubelet Liveness probe failed: curl: (35) error:0A00010B:SSL routines::wrong version number`

Same error for the readiness probe.

Thanks for your help.

**Comment by mel1nn** [comment]
To be more specific, the liveness and readiness probes returns a 404 HTTP error: 
`Liveness probe failed: curl: (22) The requested URL returned error: 404` (associated curl command: `curl -sSf http://127.0.0.1:6180`)

The error `error:0A00010B:SSL routines::wrong version number` happens with the second curl command `curl -sSfk https://127.0.0.1:6180`

**Comment by Rozzii** [comment]
Yes I have seen this downstream also. I will take care of it .
/remove-lifecycle stale
