### ISSUE TITLE
Add the feature of specifying the certificate path in BMH

### ISSUE THREAD

**Issue by zhouhao3** [metal3-io/baremetal-operator#1129]
Currently there is only one field `disableCertificateVerification` in BMH to skip certificate verification. When this field is set to true, the default certificate in ironic will be used for SSL authentication when connecting to BMC. But these default certificate validations may fail (we have validated the iRMC server).
BMO sets the contents of `driver_info(verify_ca)` based on the value of `disableCertificateVerification` . now it can only be set to true or false, but `verify_ca` can also be a path to a CA_BUNDLE.
So we want to add the feature of specifying the certificate path in BMH, so that the certificate can be passed into ironic for connecting to BMC.

**Comment by zhouhao3** [comment]
@dtantsur @zaneb @andfasano Is this an acceptable feature?

**Comment by dtantsur** [comment]
Hi! I'm not sure how you want to put a file to the containers... If you build a new container, you can just as well make your certificate trusted?

**Comment by fenggw-fnst** [comment]
> Hi! I'm not sure how you want to put a file to the containers... If you build a new container, you can just as well make your certificate trusted?

Can we mount the certificate to the Ironic container? The specified certificate path should be the mount point in that container.

**Comment by Rozzii** [comment]
@zhouhao3 Could you please explain to us that why is bundling multiple certificates together is not a suitable solution?
What is blocking you from using a CA bundle ?

**Comment by zaneb** [comment]
If there were a way to pass the certificate directly to ironic then I could see us allowing the user to specify the certificate in the BMH. As it is, though, I can't imagine this ever making sense because the certificate must be on-disk in the ironic container, and that's not something that the BMO could control. Nor would we want to make paths that are specific to a particular deployment of ironic part of the BMH api.

**Comment by Rozzii** [comment]
@zhouhao3 The certificate used by Ironic is not controlled by BMO at all, the certificate used by ironic is directly mounted to the ironic container as part of the Ironic deployment BMO has no say in it. You can just mount the required certificates directly to the Ironic container and this is the reason why we are a bit puzzled here that why would you involve BMO and BMH in this process at all?

**Comment by zhouhao3** [comment]
@Rozzii Thank you for your reply, as I said above, Currently IPI does not  support specifying root certificates, so I wonder if it can be passed from BMO. So I wrote this issue to see what everyone thinks. 
Now that I know this is not part of the BMO thing to do, I created an [issue](https://github.com/openshift/installer/issues/6001) in openshift to discuss this, and I will close this issue.
