### ISSUE TITLE
Update customized property of BMH

### ISSUE THREAD

**Issue by k82cn** [metal3-io/baremetal-operator#1158]
In my scenario, I'd like to add more properties when creating node.

**Comment by s3rj1k** [comment]
@k82cn Please provide example

**Comment by k82cn** [comment]
Those two properties are required to my HW, I hack the code to make it work; that'll be great to have a way to add more customized properties.

```
--driver-info ipmi_cipher_suite=17 \
--driver-info ipmi_disable_boot_timeout=false \
```

**Comment by k82cn** [comment]
typo: properties -> driver_info :)

**Comment by s3rj1k** [comment]
> --driver-info ipmi_cipher_suite=17 \
--driver-info ipmi_disable_boot_timeout=false \

I assume that you can set those values directly in ironic config?

**Comment by dtantsur** [comment]
Re cipher suite. Our image already has this in the configuration:

```
# List of possible cipher suites versions that can be
# supported by the hardware in case the field `cipher_suite`
# is not set for the node. (list value)
cipher_suite_versions = 3,17
```

It should allow negotiation. Isn't it enough for your case?

**Comment by dtantsur** [comment]
I'd be curious to hear why you need `ipmi_disable_boot_timeout`, but it feels like something we could add as an option to the BMC address.

**Comment by k82cn** [comment]
> Re cipher suite. Our image already has this in the configuration:
> 
> ```
> # List of possible cipher suites versions that can be
> # supported by the hardware in case the field `cipher_suite`
> # is not set for the node. (list value)
> cipher_suite_versions = 3,17
> ```
> 
> It should allow negotiation. Isn't it enough for your case?

let me try this for cipher part.

**Comment by Rozzii** [comment]
@k82cn did @dtantsur 's answer help, or is it still an active issue for you?
