### ISSUE TITLE
Open up the possibility of using all deviceHint operators in certain deviceHint types

### ISSUE THREAD

**Issue by Rozzii** [metal3-io/baremetal-operator#1159]
The way device hint handling is implemented right now in https://github.com/metal3-io/baremetal-operator/blob/main/pkg/provisioner/ironic/devicehints/devicehints.go#L18-L44 means that there is no possibility to use any other Ironic device hint operator other than the ones that are hard coded in the aforementioned implementation.

IMO: the serialNumber and the 3 different WWN hints, the DeviceName and HCTL don't require the "s==" prefix at the BMO level because for string type device hints IPA checks the presence of valid operators and if there is no valid operator then IPA will prepend  the hint with "s==" as implemented here https://opendev.org/openstack/ironic-lib/src/commit/95ce746ad101b7af32684c29384237061565a4af/ironic_lib/utils.py#L279-L284 . 

I understand that the hard coded operators are more explicit but at the same time they artificially limit the functionality of Ironic/IPA when used in combination with BMO. I am currently facing a situation where I would need the "\<in\>" operator in the serialNumber device hint but I can't use it because BMO blocks me despite the fact that Ironic/IPA supports the feature.

Would it be okay to stop prepending  the hard coded operators fro the  serialNumber,WWN,  WWNWithExtension, WWNWithVendorExtension, HCTL and DeviceName hints?

**Comment by kashifest** [comment]
+1 for removing the "s==" prefix at BMO level. @dtantsur @zaneb wdyt? Do you have any suggestions?

**Comment by dtantsur** [comment]
No objections from me. We also need to consider non-default operators for integer values.

/triage accepted

**Comment by zaneb** [comment]
One goal we have with the Metal³ is to _not_ be a passthrough for the ironic API. I'm concerned that this approach is based on ease of implementation, not whether it is actually a good k8s API design. I'm more concerned that this opens up the possibility that the behaviour will be different in the future depending on the version of ironic, and entirely untethered from the versioning of the BMH API.

(FWIW we have downstream code that uses the deviceHint field in the BMH API independently of ironic, and it would need to be updated to reimplement these new behaviours. I wouldn't say this is the main reason to avoid this, but it's an example of the consequences of delegating the meaning of an API to another project.)

**Comment by dtantsur** [comment]
So, our options:

1) Expose operators in the current API. I'm not overly fond how they're done in Ironic, and we don't want to leak the Ironic API directly to consumers.

2) Change all hints to be a structure with a value and an operator. Clean but backward incompatible.

3) Add new hints like `serialIn` which is the same as `serial: <in> value`. Easy to do in a compatible way, but unclear what to do with hints that already use `<in>`.

Thoughts?

**Comment by kashifest** [comment]
> 1. Expose operators in the current API. I'm not overly fond how they're done in Ironic, and we don't want to leak the Ironic API directly to consumers.

I think this is the easier way perhaps not popular as @zaneb pointed out. 

> 2. Change all hints to be a structure with a value and an operator. Clean but backward incompatible.

I dont think this is preferable as it would be a breaking change. 
> 3. Add new hints like `serialIn` which is the same as `serial: <in> value`. Easy to do in a compatible way, but unclear what to do with hints that already use `<in>`.

We need something similar to this perhaps to make the BMO API sustainable. We need some suggestions on how to make it work for all the operators.

**Comment by Rozzii** [comment]
Thanks for all the feedback, I agree with you @zaneb and I will try to propose a approach based on what @dtantsur  mentioned
based as option 3.

**Comment by Rozzii** [comment]
Honestly I would close it in favor of #1308 , support for that Issue is progressing in both oslo, Ironic, and would solve my BMO use-cases, WDYT @kashifest   @dtantsur  @zaneb should we still keep this issue is there benefit in this ?
