### ISSUE TITLE
ipv4 address in baremetalhost is different from actual ipv4 address

### ISSUE THREAD

**Issue by ileixe** [metal3-io/baremetal-operator#1199]
**What steps did you take and what happened:**
It's closer to question not a bug, and I want to raise this issue to know what the expected behavior.

After creating a baremetalhost, IP address(10.0.0.99) like below
```sh
kubectl describe bmh worker-001

...
Nics:
      Ip:           169.254.3.1
      Mac:          f2:ce:8f:67:1e:cd
      Name:         enp4s0f3u1u2c2
      Ip:           fe80::4658:56ec:7bf4:f65d%enp4s0f3u1u2c2
      Mac:          f2:ce:8f:67:1e:cd
      Name:         enp4s0f3u1u2c2
      Ip:           10.0.0.99
      Mac:          3c:ec:ef:fb:83:4a
      Model:        0x8086 0x1563
      Name:         enp197s0f0
```
shows it has `10.0.0.99`.

But the ip `10.0.0.99` is leased by first boot (inspector), and the provisioned OS has different ip address `10.0.0.100` like below
```
#This is in ironic-dnsmasq

[root@mgmt-001 dnsmasq]# cat dnsmasq.leases
1671684072 3c:ec:ef:fb:83:4a 10.0.0.100 worker-001 ff:f8:1a:ae:7d:00:02:00:00:ab:11:77:8e:f7:9a:5b:c6:14:20
```

It's because dnsmasq currently uses pair of `client id` (worker-001), and MAC as an identifier to lease a IP. First boot does not have `client id` so dnsmasq leased different IP as it differentiates the host even if it has same MAC.

Is it expected behavior? How the operator find the right ip if they don't have the information in bmh?

We have custom dnsmasq.conf having `dhcp-ignore-clid` option which makes dnsmasq not use `client id` as identifier, but I'm not sure how others deal with it.

**What did you expect to happen:**
N/A

**Anything else you would like to add:**
N/A

**Environment:**

- Baremetal Operator version: latest
- Environment (metal3-dev-env or other): latest k8s

/kind bug

**Comment by Rozzii** [comment]
From my point of view (and also we discussed this on community meeting) this is simply an unsupported use-case from the perspective of the Metal3 stack. You would need to bake in a feature to IPA (ironic-python-agent) that could assign these client-ids to your nodes during inspection, in order to make the id based ip allocation work properly. 

At least that is how I understand your issue.

**Comment by Rozzii** [comment]
Do you have further questions @ileixe or can we close this issue?

**Comment by ileixe** [comment]
Sorry for late response. I can understand current situation at least, and we've used metal3 ip pool rather than relying on DHCP. Thanks.
