### ISSUE TITLE
`saveHostStatus` triggers even on unchanged object

### ISSUE THREAD

**Issue by s3rj1k** [metal3-io/baremetal-operator#1253]
```
func (r *BareMetalHostReconciler) saveHostStatus(host *metal3v1alpha1.BareMetalHost) error {
	t := metav1.Now()
	host.Status.LastUpdated = &t

	return r.Status().Update(context.TODO(), host)
}
```

There is an edge case when `saveHostStatus` is triggered even when no actual objects changes are made, the only change to object is updating `LastUpdated` filed.

It would be better to have this field updated only if something in status was actually changed.

Current behavior adds unneeded reconciles for external watchers that follow BMH changes, this becomes noticeable on big clusters with lots for BMH.

**Comment by s3rj1k** [comment]
@dtantsur What do you think?

**Comment by dtantsur** [comment]
From a quick look at the source code, we do seem to only call `saveHostStatus` when the action returns a `dirty` flag. Maybe we sometimes do it incorrectly. Do you have specific examples when it happens @s3rj1k?

**Comment by s3rj1k** [comment]
@Rozzii What information is needed?

**Comment by s3rj1k** [comment]
> Do you have specific examples when it happens @s3rj1k?

It affected me noticeably during the pre-provision phase (in big cluster), when machines are getting linked with hosts, host where changing constantly.

**Comment by Rozzii** [comment]
@s3rj1k I would like to have steps to reproduce the issue, as far as I understand from your description this happens when there are a lot of new machines are getting registered  but from that I can't tell what exactly is causing the issue.

**Comment by s3rj1k** [comment]
> @s3rj1k I would like to have steps to reproduce the issue, as far as I understand from your description this happens when there are a lot of new machines are getting registered but from that I can't tell what exactly is causing the issue.

I am not sure what extra steps you need to reproduce this, the issue of NOP updates is there all the time, just check the code, updates are unconditional, every reconcile (in not provisioned states) time is getting updated.

**Comment by Rozzii** [comment]
I will go ahead and accept this, although I am not that familiar with this part of the code, the issue makes sense to me and no one else have reacted.
/accept
/remove-lifecycle stale
/lifecycle frozen

**Comment by zaneb** [comment]
> I am not sure what extra steps you need to reproduce this, the issue of NOP updates is there all the time, just check the code, updates are unconditional, every reconcile (in not provisioned states) time is getting updated.

This is referring to https://github.com/metal3-io/baremetal-operator/blob/release-0.3/controllers/metal3.io/baremetalhost_controller.go#L1538-L1541

However, I checked the code and [as Dmitry said](https://github.com/metal3-io/baremetal-operator/issues/1253#issuecomment-1549695960), we only call this if something else had changed: https://github.com/metal3-io/baremetal-operator/blob/release-0.3/controllers/metal3.io/baremetalhost_controller.go#L235-L245

Without even a single example of this happening - even a log would be helpful, we always log when we update the Status - there's no way for us to tell if any change has actually had any effect.

**Comment by Rozzii** [comment]
Both @dtantsur and @zaneb have unanswered questions around the same topic thus I have removed the "accepted" label until they receive the info they need to evaluate the issue.

**Comment by s3rj1k** [comment]
@zaneb, @dtantsur  https://github.com/metal3-io/baremetal-operator/issues/1253#issue-1671388799

Do you agree that this specific function is updating status disregarding if the actual change is happening?
Meaning it does not check if in fact old `host` and new `host` are different.

**Comment by zaneb** [comment]
> @zaneb, @dtantsur [#1253 (comment)](https://github.com/metal3-io/baremetal-operator/issues/1253#issue-1671388799)
> 
> Do you agree that this specific function is updating status disregarding if the actual change is happening?

I don't disagree with that.
I disagree that anybody in this thread has identified an instance where that function is called without an actual change happening. If you find one I'd consider it a (minor) bug, but I don't know where to look.

**Comment by s3rj1k** [comment]
> I don't disagree with that.

Issue is exclusively about that piece if code.

> If you find one I'd consider it a (minor) bug.

Feel free to close the issue.

**Comment by zaneb** [comment]
OK, thanks. Feel free to open a new issue if you see writes in the logs that don't correspond to any change in the status.
/close
