### ISSUE TITLE
BMH architecture is hard-coded from the profile before inspection

### ISSUE THREAD

**Issue by yanfeng1992** [metal3-io/baremetal-operator#1270]
**User Story**

In a multi-architecture scenario, I want to get the cpu architecture from bmh to set the Architecture field in PreprovisioningImage. Now the implementation in getHostArchitecture is obtained from the host.Status.HardwareDetails.CPU.Arch field, or from the profile. This It does not meet the needs of my scene.

Can you provide a way to manually set the cpu architecture when creating bmh？

https://github.com/metal3-io/baremetal-operator/pull/1252

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

**Comment by dtantsur** [comment]
/triage accepted
/kind bug

We've hit this downstream recently, it's pretty annoying. After inspection, the correct data will be there, but you may need it *for* inspection.
