### ISSUE TITLE
The baremetal-operator-ironic pod does goes in CrashLoopBackOff state

### ISSUE THREAD

**Issue by fracappa** [metal3-io/baremetal-operator#1313]
Hello everyone.
I'm here to report an issue that I'm struggling with.

I'm trying to setup a k8s cluster on bare metal host using metal3, and I'm trying to deploy the management cluster.

By following the [dev-setup](https://github.com/metal3-io/baremetal-operator/blob/main/docs/dev-setup.md), I successfully reach step 1,2,3,4,5 and 7.
The problem is that I still don't have the baremetal-operator-ironic pod running.
To launch it within the cluster I execute the script `./baremetal-operator/tools/deploy.sh -i` after setting **IRONIC_HOST**  and **IRONIC_HOST_IP** variables (simpliy by issuing export on the terminal session where I'm launching the configuration, setting them to the hostname and the IP of the machine I'm currently using).

The problem is that the baremetal-operator-ironic pod goes in **CrashLoopBackOff state** and it sees to be some networking configuration.
The following are the logs from the pods:

`++ echo 'Waiting for eth2 interface to be configured'
Waiting for eth2 interface to be configured
+++ ip -br add show scope global up dev eth2
+++ awk '{print $3}'
+++ sed -e 's%/.*%%'
+++ head -n 1
Device "eth2" does not exist.
++ IRONIC_IP=`

I'm trying to launch the management cluster on a minikube cluster made by two nodes.

Is this something I can solve by changing some configuration or there is something I'm missing?

Thanks

**Environment:**

- Ubuntu Server: 22.04.2 LTS
- Linux kernel version: 5.15.0-76-generic

/kind bug

**Comment by Rozzii** [comment]
I am not sure if this is a bug, the deploy.sh script and the other helper scripts might require a bit more tuning when it comes to real hardware and real networks. The setup here is a bit unclear to me, let's see if someone hits the same issue.
