### ISSUE TITLE
Fix code quality issues introduced in TLS flags PR

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/baremetal-operator#1320]
**What steps did you take and what happened:**
https://github.com/metal3-io/baremetal-operator/pull/1282 was merged and some code quality issues were raised after merging.

**Environment:**

- [x] Baremetal Operator version: main (https://github.com/metal3-io/baremetal-operator/pull/1327)
- [x] Cluster Api Provider Metal3: main (https://github.com/metal3-io/cluster-api-provider-metal3/pull/1125)
- [x] IP Address Manager: main (https://github.com/metal3-io/ip-address-manager/pull/289)

/triage accepted
/assign @as20203

**Comment by as20203** [comment]
FIxed code quality issues in below PR [1327](https://github.com/metal3-io/baremetal-operator/pull/1327)

**Comment by adilGhaffarDev** [comment]
cc @adilGhaffarDev

**Comment by adilGhaffarDev** [comment]
@tuminoid can we close this issue if it is fixed? I see a merged PR that says it has fixed this issue: https://github.com/metal3-io/baremetal-operator/pull/1327

**Comment by tuminoid** [comment]
Yes, this is completed.
