### ISSUE TITLE
BareMetalHost CR does not react if the credential secret is changed

### ISSUE THREAD

**Issue by raffaelespazzoli** [metal3-io/baremetal-operator#1346]
**What steps did you take and what happened:**
if a BMH resource is in error for invalid credentials, and the values in the credential secret are changed/fixed, the BMH resource does not wake up to try again. Notice that instead this happens if the secret is deleted and recreated.
So it looks like only the create event is considered for that secret and not the update (I have not checked the code).

**What did you expect to happen:**
I'd expect the BMH resource to try again with the new values.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Baremetal Operator version: OCP 4.13.x
- Environment (metal3-dev-env or other):

/kind bug

**Comment by dtantsur** [comment]
Do you have https://github.com/metal3-io/baremetal-operator/commit/232b7f07a87fb1b01b5ff74ef178263776a3fceb applied? I think it may solve your problem.

The OCP 4.13 counterpart is https://issues.redhat.com/browse/OCPBUGS-14250 if you want to follow-up internally.

**Comment by dtantsur** [comment]
I believe it has been fixed, please reopen with new information if it has not.
