### ISSUE TITLE
Make Ironic and BMO kustomizations usable off the shelf

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/baremetal-operator#1361]
**User Story**

As a user/operator I would like to use the BMO/Ironic kustomizations as bases for my overlays to simplify deployment.

**Detailed Description**

It is not currently possible to use the kustomizations directly as is (ref https://github.com/metal3-io/metal3-docs/issues/298). For TLS and basic-auth variants it is required to add files that kustomize will use to generate secrets. This means that the Ironic/BMO kustomizations are only usable if you clone the repo and make changes to it first.

I would want to make these kustomizations usable directly as is. Then it would be possible to reference them in overlays as URLs even.
To make this possible I see two options:

1. (preferred) Remove secret generators, [such as this](https://github.com/metal3-io/baremetal-operator/blob/bdfa1bd1bd5e3d2a98534ab1fd22616677c1568a/config/basic-auth/default/kustomization.yaml#L8-L16), from the kustomizations. All the rest stays as is. This means that the manifests are created just like before but without the secrets. The user is then responsible for adding the secrets in any way they see fit. This can be for example, by creating an overlay that adds the secrets, or using the external secrets operator. Until the secrets are created, the pods will stay pending with explanation that it is missing a secret to mount. This is a common pattern and should be easy to understand for the user.
2. Keep the secret generators, but provide example credentials for them so that the kustomizations can be built without changes. It would be up to the user to overwrite the example credentials in their overlay or through other means. I would avoid this alternative since it is easy to make mistakes and end up with example credentials used in the actual deployment. It is much better (IMO) to get the pending pods as in alternative 1.

**Anything else you would like to add:**

An easy way to check if this issue has been resolved is to do `kustomize build` for each kustomization under `config` and `ironic-deployment`. They should all succeed.

/kind feature

**Comment by Rozzii** [comment]
I am fine with option 1, let's see what the community's opinion.

**Comment by kashifest** [comment]
+1 for option 1

**Comment by tuminoid** [comment]
Default creds is bad approach, and we should strive to get rid of those, so let's not add more. Option 1 is generally better and more secure option. We just need to take care that it is documented well, with templates, because nothing is more annoying to user than finding `just create secrets` in documentation without any specifics or examples. I've found plenty of those recently in other projects, its killing me.
