### ISSUE TITLE
make lint only checks root and test folders

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/baremetal-operator#1387]
**What steps did you take and what happened:**

`make lint` is only checking the repo root and `test`, as can be seen here:
https://github.com/metal3-io/baremetal-operator/blob/c4936230d2e3bb5f136166852534760b56f523c8/Makefile#L127-L130

**What did you expect to happen:**

I think we should at least check `apis` and possibly also `pkg/hardwareutils`, similar to what we do for `make mod`
https://github.com/metal3-io/baremetal-operator/blob/c4936230d2e3bb5f136166852534760b56f523c8/Makefile#L300-L311

**Anything else you would like to add:**

We seem to have a few linting errors in `apis` already from a quick test. Nothing too serious but it would be good to make sure we do not introduce more issues.

**Environment:**

- Baremetal Operator version: main
- Environment (metal3-dev-env or other): irrelevant

/kind bug

**Comment by kashifest** [comment]
I propose to fix it as we do in CAPM3. We run golangci as a github workflow [here](https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/.github/workflows/golangci-lint.yml). Advantage is one less prow job. For local dev and test, we can do something similar to https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/Makefile#L279-L282. If this is ok, I can push a PR. 
cc @lentzi90 @dtantsur @honza @zaneb

**Comment by lentzi90** [comment]
@kashifest was this fixed in #1536?

**Comment by kashifest** [comment]
> #1536



> @kashifest was this fixed in #1536?
Yes. This is now fixed. I am planning to perhaps retire the prow job but the phony is fixed to test locally.

/close
