### ISSUE TITLE
Unable to update BMC address

### ISSUE THREAD

**Issue by sebastiaopamplona** [metal3-io/baremetal-operator#1458]
**What steps did you take and what happened:**
I have a use case where the BMC address changes after the BMH CRD is created (I'm manually changing it via Redfish).
I tried to update the BMH CRD `spec.bmc.address` accordingly, but I'm unable to do it (I suspect the field is immutable, but I did not find anything in the docs about it).

**What did you expect to happen:**
I expected the `spec.bmc.address` to be updated

/kind feature-request

**Comment by sebastiaopamplona** [comment]
nevermind, I just got this error:

```
error: baremetalhosts.metal3.io "bmh123" could not be patched: admission webhook "baremetalhost.metal3.io" denied the request: BMC address can not be changed once it is set
```

is there any plans this would be made possible?

**Comment by dtantsur** [comment]
I would like to make it possible in at least some way. It's not exactly trivial because there are many states where changing the BMC addresses can lead to weird results. Possibly, we do it through detaching.

**Comment by sebastiaopamplona** [comment]
I see; in my use case I need to do it imedeately after the first inspection, so my workaround is re-creating the BMH with the new BMC address and settimg the status annotation equal to the status of the original BMH

**Comment by dtantsur** [comment]
@sebastiaopamplona I'm curious, can you share any details why it happens?

**Comment by sebastiaopamplona** [comment]
do you mean why I need to do to change the BMC address immediately after the first inspection?

**Comment by dtantsur** [comment]
@sebastiaopamplona yep, that's my question.

**Comment by dtantsur** [comment]
/triage accepted

I must admit, your case is quite unusual. Yet, I believe that it's good to allow changing BMC addresses in at least some cases.

**Comment by dtantsur** [comment]
/remove-lifecycle stale

Is https://github.com/metal3-io/baremetal-operator/pull/1549 sufficient to close this?

**Comment by sebastiaopamplona** [comment]
@dtantsur thanks for having this implemented :)

a small question: does the BMH need to be in `registering` provisioning state? in our case we'd like to be able to change it from the `available` provisioning state

maybe this was a [small bug in the if statement](https://github.com/metal3-io/baremetal-operator/pull/1549/files#diff-f4d776327c237034e90b14c686c2257e4a914a57742cae5da3054d0a97f1f78eR80-R81) that makes it so that the BMH needs to be in the `registering` provisioning state **and** `detached` (the PR description mentions [Registering state or is detached](https://github.com/metal3-io/baremetal-operator/pull/1549#:~:text=Registering%20state%20or%20is%20detached))

**Comment by sebastiaopamplona** [comment]
hey @MahnoorAsghar , thank you for the detailed explanation and implementation; as far as i'm concerned, we can close this issue (not sure what's the standard way to go about it, so i did not close it myself)
have a nice day!
