### ISSUE TITLE
Error: wrong Node Kind for spec.dnsNames expected: MappingNode kustomization 

### ISSUE THREAD

**Issue by cleitonpena** [metal3-io/baremetal-operator#1477]
**What steps did you take and what happened:**
Run kustomize build config/default | kubectl apply -f - 
Returns this error:

```
Error: wrong Node Kind for spec.dnsNames expected: MappingNode was SequenceNode: value: {- $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc  - $(SERVICE_NAME).$(SERVICE_NAMESPACE).svc.cluster.local}
error: no objects passed to apply
```

**What did you expect to happen:**
It is expected that the deployment that is in
~/go/src/github.com/metal3-io/baremetal-operator/config/default/kustomization.yaml

**Anything else you would like to add:**
The error could be just configuring the kustomization.yaml file
On lines 100 and 113. But I'm not sure about that.

**Environment:**

- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind bug

**Comment by Rozzii** [comment]
@lentzi90 @Sunnatillo @mboukhalfa WDYT? Is anyone up for reproducing this?

**Comment by lentzi90** [comment]
I cannot reproduce this. I tested with commit `dcc132e596f086ea7cd1614e2fd46d590ce8ec3b` (which should be just before this issue was opened) and `9ce684e6462a6ab55ff650cb6c11f9ba1ffb395d` (main right now).

What is your kustomize verion?
I tested with `v5.2.1` and also the compiled binary you get with `make tools/bin/kustomize`.

**Comment by mquhuy** [comment]
Hi @cleitonpena, could you check what `kustomize` version are you using? I think I saw this error, or something similar, before, and what solved the problem was a simple kustomize upgrade.
