### ISSUE TITLE
expand image checksum type support

### ISSUE THREAD

**Issue by mhrivnak** [metal3-io/baremetal-operator#148]
The `BareMetalHost.Spec` currently supports [providing a checksum](https://github.com/metalkube/baremetal-operator/blob/8e13289/pkg/apis/metalkube/v1alpha1/baremetalhost_types.go#L150) for the image to be provisioned. The checksum can be provided directly as a string, or as a URL which will be fetched.

These questions need to be answered:
* Is the checksum assumed to be md5sum?
* Should we allow the checksum type to be specified somehow, either as a separate field, or as part of the same field? example of the latter: "sha256:abcdef..."

Whatever answers emerge, the documentation for the Image struct should be improved with more detail.

**Comment by dhellmann** [comment]
cc @juliakreger @dtantsur

**Comment by juliakreger** [comment]
Ff translated directly to ironic's image_checksum it is assumed to be md5. Two different fields are used for other checksums: 'image_os_hash_algo' and 'image_os_hash_value'. FWIW, it requires a stein IPA ramdisk.

**Comment by hardys** [comment]
It would be nice to revive this as in combination with https://storyboard.openstack.org/#!/story/2006936 we could deploy the OKD images directly (they are shipped as xz compressed qcow2 images, with an sha256sum)

I think specifying the type of checksum in the existing field e.g `sha256:xxxx` seems reasonable and keeps the interface terse but still flexible - any objections to that approach?

We could retain the existing behavior by default by assuming md5 when no prefix is given?

@dtantsur can you confirm if `image_os_hash_value` works with the URL support we now rely on?

**Comment by kirankt** [comment]
Question. If the checksum is passed, say, as: "sha256:https://...", does it mean that it needs to converted into md5hash before passing it on to ironic?

**Comment by kirankt** [comment]
Hi, I have a question. Is the plan to still keep "image_checsum" in addition to a combo of "image_os_hash_algo:image_os_hash_value" or completely replace "image_checksum" with the latter?

**Comment by hardys** [comment]
> Hi, I have a question. Is the plan to still keep "image_checsum" in addition to a combo of "image_os_hash_algo:image_os_hash_value" or completely replace "image_checksum" with the latter?

Perhaps @juliakreger can answer that, but I'd assume we continue using the existing interface for md5 checksums (e.g the default case) unless we're advised otherwise.

**Comment by kirankt** [comment]
Fixed in #401 
/close.
