### ISSUE TITLE
Is there a best practice when not deploying the cluster api service？

### ISSUE THREAD

**Issue by xinzhongyoumeng** [metal3-io/baremetal-operator#1482]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

**What did you expect to happen:**

The user docs could be more detail. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind help wanted

**Comment by dtantsur** [comment]
Hi! Please elaborate on your question, I'm not sure what exactly you're interested in.

**Comment by xinzhongyoumeng** [comment]
> Hi! Please elaborate on your question, I'm not sure what exactly you're interested in.

Our scenario is only use bmo to rebuild the system, don't need the cluster api. So we only need deploy baremetal operator and ironic deployment. In this senario, our user docs is so simple（https://book.metal3.io/），a new user can't deploy this quickly, If we can deploy it by helm , so it is greatful.

Another, I have two question about rebuild system with BMH. 

One is the first rebuild system is successful by define BMH A, after a period of time need to reinstall the system on the same node again how to do? If is change image url in the BMH A yaml  and apply this yaml again? If so, I meet metal3-baremetal-controller  tell me "Cleaning failed: Timeout reached while cleaning the node. Please check if the ramdisk responsible for the cleaning is running on the node. Failed on step {}" .  How to do about this?

Another one is can't login the system after rebuild the system. Here is my yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: bmh1
  namespace: baremetal-operator-system
type: Opaque
data:
  username: emhhbmd6aGVuaHVpCg==
  password: eWFjbkJ5bHUyOXYlMFk1alk1Cg==
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bmh1
  namespace: baremetal-operator-system
spec:
  online: true
  userData:
    name: cloud-init
    namespace: baremetal-operator-system
  bootMACAddress: 6c:92:bf:ce:12:ee
  image:
    url: http://10.46.72.2:6180/imageconfigd.qcow2
    checksum: 2ff02b943d645b16f9da34bbd4d294d1
    checksumType: md5
  bmc:
    address: 10.46.8.102:623
    credentialsName: bmh1
    disableCertificateVerification: true
---
apiVersion: v1
data:
  userData: dXNlckRhdGE6IHwKICAjY2xvdWQtY29uZmlnCiAgdXNlcnM6CiAgLSBuYW1lOiB0ZXN0dXNlcgogICAgcGFzc3dkOiB0ZXN0dXNlcgogICAgc3VkbzogQUxMPShBTEwpIE5PUEFTU1dEOkFMTAogICAgZ3JvdXBzOiB1c2VycywgYWRtaW4sIHdoZWVsCg==
kind: Secret
metadata:
  creationTimestamp: "2023-12-19T07:37:18Z"
  labels:
    environment.metal3.io: baremetal
  name: cloud-init
  namespace: baremetal-operator-system
  resourceVersion: "753936"
  uid: f5aa2870-d8ec-477a-9827-dafcb6b7fdeb
type: Opaque
```
and the image build with disk-image-create, the build cli is 
```
export DIB_LOCAL_IMAGE=/root/images/CentOS-7-x86_64-GenericCloud.qcow2.xz
export DIB_YUM_REPO_CONF=/etc/yum.repos.d/CentOS-Base.repo
export DIB_DNF_MODULE_STREAMS=biosdevname
export DIB_CLOUD_INIT_ALLOW_SSH_PWAUTH=yes
export DIB_CLOUD_INIT_DATASOURCES="ConfigDrive" 
disk-image-create centos7 vm cloud-init-datasources block-device-efi dhcp-all-interfaces -o imageconfigd
```
Can you give me some solution, thank you

**Comment by Rozzii** [comment]
Do you still need help @xinzhongyoumeng
