### ISSUE TITLE
Only support UEFI  boot mode?

### ISSUE THREAD

**Issue by xinzhongyoumeng** [metal3-io/baremetal-operator#1506]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

The bmo ironic deployment ironic conf is only set uefi(https://github.com/metal3-io/ironic-image/blob/main/ironic-config/ironic.conf.j2#L89C1-L89C11) , so if it means only support uefi boot mode, do not support legacy bios mode?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind help

**Comment by dtantsur** [comment]
> The bmo ironic deployment ironic conf is only set uefi(https://github.com/metal3-io/ironic-image/blob/main/ironic-config/ironic.conf.j2#L89C1-L89C11) , so if it means only support uefi boot mode, do not support legacy bios mode?

Hi! Metal3 supports both legacy boot and UEFI; UEFI is the default. You can change it by setting the BootMode field on your BareMetalHost objects.

/close
