### ISSUE TITLE
Running Metal-dev-env with Tilt not deploying BMO correctly

### ISSUE THREAD

**Issue by peppi-lotta** [metal3-io/baremetal-operator#1508]
**What steps did you take and what happened:**
The problem occurs by following the steps to develop with Tilt outlined in Metal3-dev-env [ README.md
](https://github.com/metal3-io/metal3-dev-env#deploying-and-developing-with-tilt)

**What did you expect to happen:**
I expected Tilt to deploy BMO but it didn't. 

**Anything else you would like to add:**
It seems changes made in PR #1438 regarding basic-auth and TLS are causing the issues in setting up Tilt. 

**Environment:**

- Baremetal Operator version: 
- Environment: metal3-dev-env

/kind bug

**Comment by Rozzii** [comment]
Thanks for the investigation and the bug report @peppi-lotta 
/triage accepted
/kind bug
/assign @peppi-lotta
