### ISSUE TITLE
E2E: Test virtualmedia boot

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/baremetal-operator#1512]
Test virtualmedia boot in the e2e tests. We have a live-iso test already [here](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/live_iso_test.go), but this just sets the disk format. The idea with the live-iso test that we have in CAPM3 is to test virtualmedia booting with a live-iso and that would be good to test here as well.

I think we have two alternatives:

1. Make the live-iso test "special". It would require redfish-virtualmedia or skip the test
2. Make all tests work with virtualmedia. Just like we currently test with IPMI and redfish, this would just be another option. In this case the live-iso test stays like it is now but we may have to adapt other tests to work with virtualmedia (e.g. disk cleaning could be strange).

I would prefer option 2.

**Comment by Rozzii** [comment]
I would prefer option 2 we are doing it in CAPM3 tests as out of the 4 nodes some are using virtualmedia to boot. This is also an easy test, you just add the prefix to the bmc address. I don't really expect issues even with disk cleaning, IPA should handle that just fine . 
/triage accepted
