### ISSUE TITLE
The official website has so many errors and user can't use it to deploy the enviorment

### ISSUE THREAD

**Issue by matthewei** [metal3-io/baremetal-operator#1516]
**What steps did you take and what happened:**

**What did you expect to happen:**
we can use user-guide to deploy the enviorment!

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind bug

**Comment by tuminoid** [comment]
Hello @matthewei, can you be more specific what exactly doesn't work?

**Comment by matthewei** [comment]
yes, if I have already a kubernetes cluster and I can't find any docs to help me install the metal3.

**Comment by matthewei** [comment]
If you use kind to install metal3 and you can get a total different devel env from minikube. So I think we should provide some info to tell developers.

**Comment by Rozzii** [comment]
So the actionable parts are the following:

- Document how the kind and the minikube deployments differ in dev-env.
- Document deploying Metal3 control plane components on existing K8s cluster

Would documentation  of these two things be suitable solution? Is there any other topic you think we should add @matthewei ?

**Comment by matthewei** [comment]
![image](https://github.com/metal3-io/baremetal-operator/assets/86186853/ab84c213-d74c-4f90-bc51-f9d6a72c6925)
Hi all, could you find this errors, The official docs can't mattch the github's registry. I just post one .

**Comment by matthewei** [comment]
![image](https://github.com/metal3-io/baremetal-operator/assets/86186853/51c9dc80-78e4-4774-9d28-8b2c32cf84e6)
Hi all, If you use this official command and you maybe get the error result.

**Comment by lentzi90** [comment]
There is an issue for it here: https://github.com/metal3-io/metal3-docs/issues/298
Nobody had time to fix it yet

**Comment by matthewei** [comment]
@lentzi90  May I fix it?. Please assign it to me.

**Comment by lentzi90** [comment]
@mquhuy just started working on it. Could you two sync? There is probably enough to fix for two separate PRs :smile:

**Comment by matthewei** [comment]
Hahaha, as a former Ericsson person, I am very happy to do this. @lentzi90

**Comment by mquhuy** [comment]
Hi @matthewei , sorry I only checked your reply just now.
I've made a PR related to this:

Fix ironic installation with kustomize instruction: https://github.com/metal3-io/metal3-docs/pull/407

If you have time, maybe you could check it out and give comments?

**Comment by matthewei** [comment]
> Hi @matthewei , sorry I only checked your reply just now. I've made a PR related to this:
> 
> Fix ironic installation with kustomize instruction: [metal3-io/metal3-docs#407](https://github.com/metal3-io/metal3-docs/pull/407)
> 
> If you have time, maybe you could check it out and give comments?

yes,

**Comment by matthewei** [comment]
![image](https://github.com/metal3-io/baremetal-operator/assets/86186853/254ce64e-260d-415e-932e-900f3043a6c3)
where is `bmext`? we need to tell how to create `bmext`. What about you?

**Comment by matthewei** [comment]
![image](https://github.com/metal3-io/baremetal-operator/assets/86186853/1d59bf1c-86c9-4350-8ebf-2a6f4a04658a)
I work through this docs. I feel confiuesd....

**Comment by matthewei** [comment]
@mquhuy Do you have any plan to fix this errors?

**Comment by mquhuy** [comment]
Hi @matthewei. Sorry I forgot about it, I'll check and come back to you asap.

**Comment by Rozzii** [comment]
I think we can remove this "Installing on Baremetal" section as now we have much more up to date tutorials in the [quickstart](https://book.metal3.io/quick-start) would be enough? The older "Installing on Baremetal" was anyways following a dev-env specific process that isn't applicable for production deployments.

**Comment by matthewei** [comment]
I think our docs should be improved just like `kubevirt`. There are so many info in our docs.

**Comment by lentzi90** [comment]
I'm fine with removing the "Installing on Baremetal", but it would be good to check with the community first if someone needs it and wants to work on improving it

**Comment by matthewei** [comment]
![image](https://github.com/metal3-io/baremetal-operator/assets/86186853/c977a139-57de-431c-825d-d8feee31ef10)

**Comment by matthewei** [comment]
I think we should tell user which image should be downloaded.

**Comment by matthewei** [comment]
![image](https://github.com/metal3-io/baremetal-operator/assets/86186853/44ce5d74-f71b-4115-8c31-f0482eb91815)

@mquhuy

**Comment by matthewei** [comment]
![image](https://github.com/metal3-io/baremetal-operator/assets/86186853/32eb474a-e568-4bf8-ad4c-b718cc386097)
so many .....

**Comment by lentzi90** [comment]
It looks like you are mixing up the quick-start and the deploy.sh script. They are not compatible. Pick one and stick to it.
