### ISSUE TITLE
BMO won't start on K3s server

### ISSUE THREAD

**Issue by s0uky** [metal3-io/baremetal-operator#1552]
**What steps did you take and what happened:**
Clean build of BMO through deploy.sh script deployed into the K3s cluster never start, manager container ends with the error below in log:  

```
{"level":"error","ts":1707749352.3224826,"logger":"setup","msg":"unable to start manager","error":"failed to determine if *v1.Secret is namespaced: failed to get restmapping: failed to get server groups: Get \"https://10.43.0.1:443/api\": context deadline exceeded","stacktrace":"main.main\n\t/workspace/main.go:227\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

and changing with this error on every restart: 

```
{"level":"error","ts":1707747096.004748,"logger":"setup","msg":"unable to start manager","error":"failed to determine if *v1.Secret is namespaced: failed to get restmapping: failed to get server groups: Get \"https://10.43.0.1:443/api\": Service Unavailable","stacktrace":"main.main\n\t/workspace/main.go:227\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

Other deployments on the same K3s cluster working normally, e.g. ironic. 

**What did you expect to happen:**
BMO in running state.

**Anything else you would like to add:**
IP `10.43.0.1` is default kubernetes service, other deployments communicate normally with API server. 
CNI is the Cilium in version 1.14.3 and in the Cilium log is nothing suspiciously.

**Environment:**

- Baremetal Operator version: 0.5.0
- k3s version v1.29.1+k3s2 (57482a1c)
- go version go1.21.6

/kind bug

**Comment by Rozzii** [comment]
/help
Well I have never used BMO with K3s controlplane cluster, the Metal3-io community does not test K3s as a official controlplane.
We run tests with kind and minikube and on regular K8s setups , I hope there is someone in the community who could help you.
I would suggest joining the official slack channel, the mailing list or the community meeting and asking this question there.

**Comment by goshlanguage** [comment]
I've run BMO on k3s. What issue are you having? Is your master node tainted to not accept workloads?
