### ISSUE TITLE
Support Intel AMT power management driver

### ISSUE THREAD

**Issue by gabloe** [metal3-io/baremetal-operator#1555]
**User Story**

As a user of Metal Kubed I need to provision hardware that uses Intel Advanced Management Technology (AMT) for power management

**Detailed Description**

I would like the addition of a power driver for AMT, or if one is already available and I just not aware then please close my request.

/kind feature

**Comment by synthe102** [comment]
Hi !
I raised a similar question on [k8s slack](https://kubernetes.slack.com/archives/CHD49TLE7/p1704192732529099?thread_ts=1704017265.787529&cid=CHD49TLE7).
The TL;DR on this topic is: `ironic-staging-drivers` have an AMT driver but it's not maintained anymore. Two solutions:

1. Add a maintained AMT driver to upstream ironic
2. Hack something around fakefish

**Comment by Rozzii** [comment]
/kind invalid
After some discussion on community meeting I have to agree with @synthe102 's answer , this is something that is not even supported in Ironic and there are no plans to support it unless someone is willing to maintain the AMT driver. From Metal3 perspective this is an invalid issue.
