### ISSUE TITLE
E2E: Make go tool for creating BMH VMs

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/baremetal-operator#1560]
**User Story**

As a developer I would like to have a go module for creating virtualized BMHs, so that this can be easily reused and consumed between repos and scripts.

**Detailed Description**

Similar to [make-virt-host](https://github.com/metal3-io/baremetal-operator/tree/main/cmd/make-virt-host), convert the [scripts](https://github.com/metal3-io/baremetal-operator/blob/main/hack/create_bmcs.sh) that we use into a go tool that can be reused for e2e tests, tilt setup and (in the future) CAPM3. The currently used scripts work well but are tricky to reuse. It is doable for e2e and tilt so far but it would be much nicer to have a proper go module for it. That module could then be used also by projects building on BMO, e.g. CAPM3, not to mention downstream projects and "testing environments".

At a high level, I want to be able to
1. `go install` a binary for creating VMs that can be used as BMHs
2. import a go module to do the same in go code
3. specify some basic parameters for how to configure the VMs (amount of VMs to create, CPU, RAM, disk size, MAC, etc). Some kind of config file would probably make sense for this.

**Anything else you would like to add:**

I think this is the library we should use: https://gitlab.com/libvirt/libvirt-go-module

/kind feature

**Comment by Rozzii** [comment]
@lentzi90 should we either reword this or should we create a separate for the KubeVirt approach (if it doesn't exist already, I haven't checked) . As far as I understand right now the main goal would be to bring kube-virt into our dev-env and e2e tests to handle the VMs.

**Comment by lentzi90** [comment]
I can create a separate for kubevirt, but there is work needed on the kubevirt side before we can start using it. Until we have that, I think this is a good alternative that we could do pretty quickly if prioritized.

**Comment by mquhuy** [comment]
Hi @lentzi90, did you mean to refer to [this script](https://github.com/metal3-io/baremetal-operator/blob/main/tools/bmh_test/create_vm.sh) instead?

**Comment by lentzi90** [comment]
Well, the script I linked to calls the script you linked but it also does a few more things that we would need. The go tool would need to do these things also, e.g. handle the network and adding the VMs to sushy-tools or VBMC

**Comment by mquhuy** [comment]
> Well, the script I linked to calls the script you linked but it also does a few more things that we would need. The go tool would need to do these things also, e.g. handle the network and adding the VMs to sushy-tools or VBMC

Thanks. I just want to make sure, since the script you linked doesn't seem to be needed for tilt setup. Anyway, all the functionalities can fit well in the same module, and we can just call what we need.
