### ISSUE TITLE
Label e2e tests in BMO

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/baremetal-operator#1573]
Our [e2e tests](https://github.com/metal3-io/baremetal-operator/tree/main/test/e2e) have no labels. We select subsets of tests to run based only on the descriptions. So we can run only tests that have a description matching `upgrade` for example.
There is a better way to [label ginkgo tests](https://onsi.github.io/ginkgo/#spec-labels) now and we should adopt it.

The initial task is to add labels to the tests matching the current split into optional and required tests. The only optional test for now is [upgrade](https://github.com/metal3-io/baremetal-operator/blob/main/test/e2e/upgrade_test.go). It should be labeled as optional and all other tests as required. It would also be good to label the tests with a descriptive name.

For example [this](https://github.com/metal3-io/baremetal-operator/blob/b5c4120dd294e94cd63fede91321f38623293ec7/test/e2e/upgrade_test.go#L173)

```go
var _ = Describe("BMO Upgrade", func() {
```

should be changed to

```go
var _ = Describe("BMO Upgrade", Label("optional", "upgrade"), func() {
```

and [this](https://github.com/metal3-io/baremetal-operator/blob/b5c4120dd294e94cd63fede91321f38623293ec7/test/e2e/provisioning_and_annotation_test.go#L27)

```go
var _ = Describe("BMH Provisioning and Annotation Management", func() {
```

should be changed to

```go
var _ = Describe("BMH Provisioning and Annotation Management", Label("required", "provision"), func() {
```

**Comment by MeenuyD** [comment]
Hello @lentzi90 I would like to work on this issue but I have a question I have to change only this or all of the e2e test

**Comment by lentzi90** [comment]
/assign @MeenuyD 
Thank you for working on this issue!
