### ISSUE TITLE
Unit test coverage improvement in BMO

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/baremetal-operator#1574]
Improve the unit test coverage by writing new test cases or completely new tests. Check the current coverage with `make unit-cover`.

Here are some suggestions on where to start. Note that some functions are harder to test than others because they may depend on access to network resources or a database. If you come across such function, skip them and aim for the low hanging fruits instead.

- [x] [features.go](https://github.com/metal3-io/baremetal-operator/blob/main/pkg/provisioner/ironic/clients/features.go) has no tests at all and looks quite simple to test. Fixed in https://github.com/metal3-io/baremetal-operator/pull/1579
- [ ] [loadTLSConfigFromEnv](https://github.com/metal3-io/baremetal-operator/blob/main/pkg/provisioner/ironic/factory.go#L169) is untested and should be easy to test. Fixed in https://github.com/metal3-io/baremetal-operator/pull/1589 or https://github.com/metal3-io/baremetal-operator/pull/2013
- [x] [baremetalhost_types.go](https://github.com/metal3-io/baremetal-operator/blob/main/apis/metal3.io/v1alpha1/baremetalhost_types.go) has multiple small functions without coverage that could easily be tested. Fixed in https://github.com/metal3-io/baremetal-operator/pull/1615
- [x] [bmceventsubscription_controller.go](https://github.com/metal3-io/baremetal-operator/blob/main/controllers/metal3.io/bmceventsubscription_controller.go) has no tests at all. Fixed in https://github.com/metal3-io/baremetal-operator/pull/1615
- [ ] [preprovisioningimage_controller.go](https://github.com/metal3-io/baremetal-operator/blob/main/controllers/metal3.io/preprovisioningimage_controller.go) has no tests at all. Fixed in https://github.com/metal3-io/baremetal-operator/pull/2013
- [x] [LoadAuth](https://github.com/metal3-io/baremetal-operator/blob/b5c4120dd294e94cd63fede91321f38623293ec7/pkg/provisioner/ironic/clients/auth.go#L43) is untested. Fixed in https://github.com/metal3-io/baremetal-operator/pull/1774
- [x] [client.go](https://github.com/metal3-io/baremetal-operator/blob/main/pkg/provisioner/ironic/clients/client.go) has no tests at all. Fixed in https://github.com/metal3-io/baremetal-operator/pull/1606

**Comment by lentzi90** [comment]
/reopen
There are a few items in the list still

**Comment by babugeet** [comment]
@lentzi90 : can i take it up for adding test cases for LoadAuth

**Comment by lentzi90** [comment]
Sure! Go ahead @babugeet ! :slightly_smiling_face:

**Comment by babugeet** [comment]
@lentzi90 : pls review the above PR

The provided test cases cover the following scenarios for the LoadAuth function:

    No Authentication Directory Exists:
        Test Case: NoAuthDirectory
        Description: Tests the scenario where the ironic authentication directory does not exist. The function should return NoAuth as the authentication type without any errors.

    Valid Authentication Credentials:
        Test Case: ValidAuth
        Description: Tests the scenario where the ironic directory exists with valid username and password files. The function should return HTTPBasicAuth with the correct username and password.

    Empty Username File:
        Test Case: EmptyUsername
        Description: Tests the scenario where the username file is present but empty. The function should return an error indicating that the HTTP Basic Auth username is empty.

    Empty Password File:
        Test Case: EmptyPassword
        Description: Tests the scenario where the password file is present but empty. The function should return an error indicating that the HTTP Basic Auth password is empty.

**Comment by Rozzii** [comment]
@lentzi90  this is still open, can we close this ? If not I would like to move this to the general roadmap.

**Comment by lentzi90** [comment]
Yes let's keep it open until we finish the last few points on the list
