### ISSUE TITLE
We can execute `make install` and `make uninstall`

### ISSUE THREAD

**Issue by matthewei** [metal3-io/baremetal-operator#1648]
**What steps did you take and what happened:**
I want to install BMO by using makefile. I just execute `make install` and `make uninstall` and I got some errors.

**What did you expect to happen:**
I can use `make install` and `make uninstall`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

![image](https://github.com/metal3-io/baremetal-operator/assets/86186853/f19076f4-5bd8-45db-bc40-c6f592dd3034)

**Environment:**

- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind bug

**Comment by Rozzii** [comment]
Those are probably not live targets , so I would propose just removing them.
They are still causing confusion so IMO it is a bug and they have to be removed.
