### ISSUE TITLE
Why don't we have a Chart Package?

### ISSUE THREAD

**Issue by matthewei** [metal3-io/baremetal-operator#1649]
**User Story**

As a user I would like to have a high level description for reasons

we want to have a chart package to install BMO. we can define the values.yaml to controller how to install the BMO

/kind feature

**Comment by lentzi90** [comment]
Helm has [no support for CRD upgrades](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations), so this will anyway need to be handled separately. So why have two tools when kustomize can cover it all?
Then there is the question of config files. For BMO it is not so bad, just a few environment variables are needed and they can be easily added through helm values. But for something more complex, like Ironic, you quickly end up with inline config in the helm values. :grimacing: 

I'm not completely objecting having a helm chart though. If someone is willing to create one and do a PR to add it, go for it!

**Comment by matthewei** [comment]
yeah, Thanks a lot for your timely reply.The user can learn how to set variables for the BMO and Ironic if we provied the helm chart. From my point of view, using "export variables" may not be a good method. 
if we don't want to use helm chart. I think we can genereate deploying-scripts for user. The users don't need to clone code from github to execute './tools/deploy.sh ------'.

**Comment by matthewei** [comment]
If we want more people to use metal3, we should provide a more convenient installation method. what about you?

**Comment by lentzi90** [comment]
I totally agree! Have you seen the new [quick-start](https://book.metal3.io/quick-start)? My goal was to address exactly these issues. The user does not need to have go installed or the repo cloned or run random scripts from the internet. They still need to provide some configuration and credentials though. I understand that kustomize isn't as well known as helm and the initial deployment does take more time, but I do think this is a great improvement over the deploy.sh script and should work well in most cases.

**Comment by matthewei** [comment]
yes, I have read it and followed it. But I foud as a fresh man I need more time to study it. The official documentation does not match the actual situation.
