### ISSUE TITLE
How can i get all the deploying scripts?

### ISSUE THREAD

**Issue by matthewei** [metal3-io/baremetal-operator#1650]
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

I want to get all the deploying scripts. Could you tell me the method?

**Environment:**

- Baremetal Operator version:
- Environment (metal3-dev-env or other):

/kind bug

**Comment by mquhuy** [comment]
Hi @matthewei . I'm not certain what are the deploying scripts that you're asking for? Could you please elaborate more information, and what you expect to use these scripts with?

The only related script I could think of right now is the `deploy.sh`, which is a helper script that can be used in deploying both bmo and ironic. You can check out more information about this script [from our docs](https://book.metal3.io/bmo/install_baremetal_operator#deployment-commands)

/kind question

**Comment by matthewei** [comment]
Hi @mquhuy I mean that the `deploy yaml files`, These `yaml files` are very useful for engineer and sometimes we can learn it's architecture from these `yaml files`.

**Comment by mquhuy** [comment]
I see. The final yaml manifest can be achieved with `kustomize build <kustomize-overlay>`. For instance:

```bash
kustomize build ironic-deployment/overlays/basic-auth_tls 
```

**Comment by Rozzii** [comment]
I would suggest moving this discussion to the mailing list or to the slack channel as those would fit the format of the discussion better.
