### ISSUE TITLE
We need tags for ironic-image releases

### ISSUE THREAD

**Issue by mquhuy** [metal3-io/baremetal-operator#1663]
**What steps did you take and what happened:**
- Install ironic with a release `ironic-image` image, for e.g.

```yaml
images: 
- name: quay.io/metal3-io/ironic                
  newTag: release-24.0
```

but the ironic deployment won't be ready, as the `release-24.0` image lacks the readiness and liveness probes, which is required by the `main` branch `ironic-deployment` kustomization.

**What did you expect to happen:**
We should have an `ironic-image-release-24.0` tag in BMO repo, which should be used to get a suitable kustomization that works with the `release-24.0` ironic image

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Maybe it makes more sense to store the `ironic-deployment` in `ironic-image` repo instead? The kustomization will, then, be a part of the release  branches/tags.

/kind bug

**Comment by Rozzii** [comment]
The 0.5 release branch of BMO supports 24.0 Ironic image wouldn't that fulfill your requirement?

**Comment by mquhuy** [comment]
> The 0.5 release branch of BMO supports 24.0 Ironic image wouldn't that fulfill your requirement?

Kinds of. But that's more of suitability between BMO versions and ironic versions. The problem I'm mentioning here is how an ironic-deployment version should be suitable to an ironic-image version. 

I guess the main issue here is that we have ironic deployment and ironic-image in two repos.

**Comment by mquhuy** [comment]
We discussed in the community meeting. The current situation is fine for now, as we will eventually move to `ironic-standalone-operator` instead.
