### ISSUE TITLE
introspection data shows nic speed as 0

### ISSUE THREAD

**Issue by russellb** [metal3-io/baremetal-operator#179]
I just checked the resulting hardware details from introspection on the BareMetalHost objects via metal3-io/metal3-dev-env and noticed that the NICs are listed with a speed of 0.

```
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"metal3.io/v1alpha1","kind":"BareMetalHost","metadata":{"annotations":{},"name":"kube-worker-0","namespace":"metal3"},"spec":{"bmc":{"address":"ipmi://192.168.111.1:6233","credentialsName":"kube-worker-0-bmc-secret"},"bootMACAddress":
"00:93:1e:b1:74:87","online":true}}
  creationTimestamp: "2019-05-03T18:24:45Z"
  finalizers:
  - baremetalhost.metal3.io
  generation: 2
  name: kube-worker-0
  namespace: metal3
  resourceVersion: "1382"
  selfLink: /apis/metal3.io/v1alpha1/namespaces/metal3/baremetalhosts/kube-worker-0
  uid: ba1d5285-6dd0-11e9-86cf-4c9a6490472b
spec:
  bmc:
    address: ipmi://192.168.111.1:6233
    credentialsName: kube-worker-0-bmc-secret
  bootMACAddress: 00:93:1e:b1:74:87
  hardwareProfile: ""
  online: true
status:
  errorMessage: ""
  goodCredentials:
    credentials:
      name: kube-worker-0-bmc-secret
      namespace: metal3
    credentialsVersion: "807"
  hardware:
    cpu:
      count: 2
      model: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      speedGHz: 3.50401
      type: x86_64
    nics:
    - ip: 172.22.0.54
      mac: 00:93:1e:b1:74:87
      model: 0x1af4 0x0001
      name: eth0
      network: Pod Networking
      speedGbps: 0
    - ip: 192.168.111.23
      mac: 00:93:1e:b1:74:89
      model: 0x1af4 0x0001
      name: eth1
      network: Pod Networking
      speedGbps: 0
    ramGiB: 4
    storage:
    - model: QEMU QEMU HARDDISK
      name: /dev/sda
      sizeGiB: 50
      type: HDD
    - model: '0x1af4 '
      name: /dev/vda
      sizeGiB: 8
      type: HDD
  hardwareProfile: unknown
  lastUpdated: "2019-05-03T18:29:58Z"
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: c718759b-518e-446b-afd2-010374971f81
    image:
      checksum: ""
      url: ""
    state: ready
```

**Comment by russellb** [comment]
@zaneb FYI

**Comment by russellb** [comment]
Ah, this is currently hard coded as 0 and remains a todo item.  https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/ironic.go#L380

This issue can track the todo item then :-)

**Comment by zaneb** [comment]
Yeah, this info is straight up not available from introspection.

**Comment by russellb** [comment]
Ok I think we should just remove the fields for things we don’t have available.

**Comment by dhellmann** [comment]
> Yeah, this info is straight up not available from introspection.

According to @dtantsur and @juliakreger there's a flag to enable to get extra data out of the inspector, and having that flag turned on requires an extra library that should already be in the RDO images we're using.

**Comment by dhellmann** [comment]
@dtantsur says the extra data also goes into a separate portion of the response data structure, so we need to ensure gophercloud is looking at that data.

**Comment by zaneb** [comment]
I believe we're logging the whole body of the response, and I don't see speed data in there (although that could be because I'm using virt and not bare metal).

I did plan to go through and modify all of the data structures to more closely match the information we actually have available from introspection, now that we know what that is. Doug already beat me to the punch on some of the CPU stuff ;)

**Comment by dhellmann** [comment]
OK, it sounds like the "extra" hardware stuff is added to the API response in a secondary data structure that is organized differently ("lists of lists"). So, we should ensure the flag is set to collect it, the library is in the image, and that gophercloud can deal with it and isn't just ignoring it because it doesn't fit into the data structure where the rest of the data is unmarshalled.

**Comment by bfournie** [comment]
@dhellmann see the "extra" section in the baremetal data here https://docs.google.com/document/d/1JxD0qSooTXuvldxtCGKXSd7ZDepAM1JDbncdmWDxSP0/edit?usp=sharing

**Comment by zaneb** [comment]
Here's a conveniently yamlified version of the introspection data from a virt host: http://paste.openstack.org/show/750893/

There's no `extra` section, but there is a `data` section that sounds like the list of subsystem/resource/key/value lists that @dtantsur was referring to, and appears to contain a lot of the same data as the `extra` section that @bfournie was referring to presents in a nicer format.

It's quite likely that there would be an entry like `["network", "en0", "speed", "1Gbit/s"]` if we were running on a physical host where talking about the speed of the NIC actually made sense.

**Comment by dtantsur** [comment]
To get the `extra` section we need to enable the `extra_hardware` processing hook in ironic-inspector.

**Comment by dhellmann** [comment]
> To get the `extra` section we need to enable the `extra_hardware` processing hook in ironic-inspector.

It looks like https://docs.openstack.org/ironic-inspector/latest/user/usage.html#plugins has details about that. It mentions storing the data in a Swift object. Can we store it somewhere else?

**Comment by dtantsur** [comment]
Well, we're storing it in the database already (otherwise you would not get any data).

**Comment by dhellmann** [comment]
> Well, we're storing it in the database already (otherwise you would not get any data).

OK, good. I only asked because the docs mentioned Swift and that made me think it was somehow special.

**Comment by dtantsur** [comment]
Ah, nope, just the regular introspection data storage. We should s/Swift/Swift or database/ all over the documentation :)

**Comment by dhellmann** [comment]
> Ah, nope, just the regular introspection data storage. We should s/Swift/Swift or database/ all over the documentation :)

https://review.opendev.org/658826
