### ISSUE TITLE
Introspection gives every NIC a network name of "pod networking"

### ISSUE THREAD

**Issue by russellb** [metal3-io/baremetal-operator#180]
Right now we hardcode a network name of "Pod networking" for every NIC.  This should be either removed, or made dynamic somehow.

https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/ironic.go#L378

Example:

```
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"metal3.io/v1alpha1","kind":"BareMetalHost","metadata":{"annotations":{},"name":"kube-worker-0","namespace":"metal3"},"spec":{"bmc":{"address":"ipmi://192.168.111.1:6233","credentialsName":"kube-worker-0-bmc-secret"},"bootMACAddress":
"00:93:1e:b1:74:87","online":true}}
  creationTimestamp: "2019-05-03T18:24:45Z"
  finalizers:
  - baremetalhost.metal3.io
  generation: 2
  name: kube-worker-0
  namespace: metal3
  resourceVersion: "1382"
  selfLink: /apis/metal3.io/v1alpha1/namespaces/metal3/baremetalhosts/kube-worker-0
  uid: ba1d5285-6dd0-11e9-86cf-4c9a6490472b
spec:
  bmc:
    address: ipmi://192.168.111.1:6233
    credentialsName: kube-worker-0-bmc-secret
  bootMACAddress: 00:93:1e:b1:74:87
  hardwareProfile: ""
  online: true
status:
  errorMessage: ""
  goodCredentials:
    credentials:
      name: kube-worker-0-bmc-secret
      namespace: metal3
    credentialsVersion: "807"
  hardware:
    cpu:
      count: 2
      model: Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
      speedGHz: 3.50401
      type: x86_64
    nics:
    - ip: 172.22.0.54
      mac: 00:93:1e:b1:74:87
      model: 0x1af4 0x0001
      name: eth0
      network: Pod Networking
      speedGbps: 0
    - ip: 192.168.111.23
      mac: 00:93:1e:b1:74:89
      model: 0x1af4 0x0001
      name: eth1
      network: Pod Networking
      speedGbps: 0
    ramGiB: 4
    storage:
    - model: QEMU QEMU HARDDISK
      name: /dev/sda
      sizeGiB: 50
      type: HDD
    - model: '0x1af4 '
      name: /dev/vda
      sizeGiB: 8
      type: HDD
  hardwareProfile: unknown
  lastUpdated: "2019-05-03T18:29:58Z"
  operationalStatus: OK
  poweredOn: true
  provisioning:
    ID: c718759b-518e-446b-afd2-010374971f81
    image:
      checksum: ""
      url: ""
    state: ready
```

**Comment by russellb** [comment]
@dhellmann @zaneb What is "network:" supposed to be?  I'm not sure a logical network name makes sense at this level, so my proposal would be to just remove it.  I'm curious if I'm missing something though.

**Comment by dhellmann** [comment]
> @dhellmann @zaneb What is "network:" supposed to be? I'm not sure a logical network name makes sense at this level, so my proposal would be to just remove it. I'm curious if I'm missing something though.

IIRC, this was coming from the UX group. Maybe @jtomasek can help?

If we don't have a name, do we want a CIDR or netmask or something like that?

**Comment by zaneb** [comment]
We don't have a name but we might get some more info from LLDP on bare metal. On virt, pickings are pretty sparse IIRC.

**Comment by bfournie** [comment]
@zaneb https://docs.google.com/document/d/1JxD0qSooTXuvldxtCGKXSd7ZDepAM1JDbncdmWDxSP0/edit?usp=sharing contains actual data from introspection on a baremetal server with LLDP enabled on the switch.

**Comment by zaneb** [comment]
I agree with Russell that a network name doesn't make any sense - for a start a port may be tagged for multiple VLANs, so it's not like there's even one network. LLDP can give us a list of VLAN IDs and names; that might be worth exposing.

Another thing we're going to want to know is which interface is PXE-bootable. That's also in the data. I wonder if that was @jtomasek's original motivation in asking for this?
