### ISSUE TITLE
Bump BMO 0.6 release branch to Go 1.22 

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/baremetal-operator#1803]
Release branch release-0.6 has Golang 1.21.x in use. Golang 1.21 support ends in August 2024, when Golang 1.23 is released.

BMO 0.6 is in support for quite a while still, so we need to bump it to Go 1.22 before next patch release.

**Comment by troy0820** [comment]
Can this issue be closed being that the PR for this is complete? Also if this closes, will we get the patch release shortly afterwards?

**Comment by NymanRobin** [comment]
@troy0820 let’s close it thanks for noticing! Pretty sure this should be auto closed when the PR merges can try to check what’s up with that

**Comment by tuminoid** [comment]
> Can this issue be closed being that the PR for this is complete? Also if this closes, will we get the patch release shortly afterwards?

We'll be doing a minor release and patch releases for all supported branches soon!
