### ISSUE TITLE
using secrets for user data is inconvenient

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#184]
The BMO wants the user data values to come from a Secret because that's how OpenShift stores the data needed by a host running an RHCOS image to become a node. That isn't the most convenient form for other types of images, though, so adding another way that is easier would be nice. We could expand the BareMetalHost CRD to accept base64 encoded data directly, or to have a more defined structure for the data.

See https://github.com/metal3-io/metal3-dev-env/blob/master/provision_host.sh for an example of a script that uses the existing Secret mechanism.

**Comment by dhellmann** [comment]
Some examples of things one can do with cloud-init: https://cloudinit.readthedocs.io/en/latest/topics/examples.html

**Comment by stbenjam** [comment]
Not sure if this helps for this, but gophercloud now supports the new config  drive format in Ironic, no need to gzip/base64 encode things anymore:

https://github.com/gophercloud/gophercloud/pull/1510

**Comment by dhellmann** [comment]
Nice! I think that's probably going to make it easier to merge data from a few sources before passing it to Ironic.

**Comment by zaneb** [comment]
I assumed it was in a Secret because the user_data often contains things that are secrets.

**Comment by zaneb** [comment]
Cluster API passes it as a Secret from v1alpha3 (see #363), so I think this is moot.
