### ISSUE TITLE
How to reprovision a host or reinject userData, networkData?

### ISSUE THREAD

**Issue by groundnuty** [metal3-io/baremetal-operator#1864]
As an operator and new user of beremetal-operator I'm experimenting with provisioning and configuration of a host.
After a successful inspection phase and a provisioning phase, I want to change userData or networkData to fix configuration issues. 
 
How can I trigger the reprovisioning of the host, (or maybe just re-injection of userData/networkData followed by system reboot?) to facilitate a quicker iteration over configuration changes?

At the moment the only way I found is to: `kubectl delete baremetalhosts.metal3.io sdd-n1` and start the whole process anew.

**Comment by dtantsur** [comment]
You can delete the image and add it again (or change the URL if it's different).

We should document this aspect, I guess.

**Comment by groundnuty** [comment]
@dtantsur I managed to make it work as you describe by making two URLs with the same image and just using them interchangeably - however, this feels more like a hack than a proper solution for reinjecting `userData` or `networkData`. As it is just a side-effect that this data changes when the image changes. 

To follow up on my question, the above-described method triggers re-provisioning of the machine. Is there a way to reinject the `userData` or `networkData` without re-provisioning? I imaging (depending on the cloud-init configuration etc.). That new `userData` or `networkData` would be picked up upon machine reboot.

**Comment by dtantsur** [comment]
Docs update: https://github.com/metal3-io/metal3-docs/pull/466

> I imaging (depending on the cloud-init configuration etc.). That new userData or networkData would be picked up upon machine reboot.

They would not: most first-boot software like cloud-init only works on the literally first boot. You'd need to remove whatever marker they create to make sure they don't run twice.

Furthermore, in case of a physical machine, this configuration is passed on a separate disk partition. Updating it would be quite invasive and not much better than a full re-provisioning.

**Comment by groundnuty** [comment]
Thanks for explaining.

As for the docs, I've spent a lot of time iterating over a correct configuration (format etc.) of `userData` and `networkData` (as it turned out it has to be in a wierd ironic format that gets later translated to netplan...) and what I was missing was a complete example with (eg. ubunut) image and configuration. I'm happy to make a pull request to docs, just please point me where.

**Comment by dtantsur** [comment]
Maybe extend https://book.metal3.io/bmo/instance_customization#networkdata?

**Comment by dtantsur** [comment]
The source if this page is https://github.com/metal3-io/metal3-docs/blob/main/docs/user-guide/src/bmo/instance_customization.md

**Comment by Rozzii** [comment]
@groundnuty Could we close this issue? It is not an actionable task. In the future I would recommend first asking on the project's slack page, the community meeting or on the mailing list.

**Comment by groundnuty** [comment]
@Rozzii yes, I shall close it.
Mind that questions on GitHub are indexed by search engines and therefore more accessible to others.
