### ISSUE TITLE
add real hardware profile matching

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#189]
Now that we have basic introspection working, we should add proper hardware profile matching to detect the type of hardware being used on a host.

**Comment by russellb** [comment]
Related design doc: https://github.com/metal3-io/metal3-docs/pull/4

Discussion on that kind of stalled when it wasn't really a blocking issue, but we should pick this back up and dicuss our goals and design

**Comment by zaneb** [comment]
Also being discussed in metal3-io/metal3-docs#60
