### ISSUE TITLE
replace machine reference with more generic "consumer ID" field

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#193]
The current machine reference field holds the name of a Machine object, which ties the host objects closely to the Cluster API. Let's rename that and make it a simple string to hold a "consumer ID" so we can still track that something is using the host, but not require that the something be a Machine.

**Comment by russellb** [comment]
+1, good idea

**Comment by dhellmann** [comment]
We will need a related change in the cluster-api-provider-baremetal code to update the new field.
