### ISSUE TITLE
Ironic Provisioning Error not Published Reliably

### ISSUE THREAD

**Issue by alanmeadows** [metal3-io/baremetal-operator#194]
When a `BareMetalHost` is provisioned, if there is an issue during the deployment, and the image hasn't changed, we will try again.  In fact, we will try forever.

I expect that between each failure, we will bubble up the error message from Ironic per https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/ironic.go#L809-L828

However, I do not see that playing out consistently.  Take the following example where the md5sum for `ub16-password-is-ubuntu.qcow2` was intentionally corrupted and then eventually fixed allowing the provisioning to complete.  I do not see any error history.  When we try the same for `ub-16.04-test.img` and in the middle of that process, switch the image to `ub16-password-is-ubuntu.qcow2` (this time with a correct checksum), we do see the error bubble up for the `ub-16.04-test.img` attempt.

I am still struggling to find the exact cause of this and would be happy to fix the bug if I could find it.  I suspect--but have not confirmed--as long as the image doesn't change, https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/ironic.go#L823-L824 may not be doing what we anticipate but this is only conjecture.

```
Events:
  Type    Reason                  Age   From                         Message
  ----    ------                  ----  ----                         -------
  Normal  DeprovisioningStarted   100m  metal3-baremetal-controller  Image deprovisioning started
  Normal  PowerOn                 98m   metal3-baremetal-controller  Host powered on
  Normal  DeprovisioningComplete  98m   metal3-baremetal-controller  Image deprovisioning completed
  Normal  ProvisioningStarted     88m   metal3-baremetal-controller  Image provisioning started for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2
  Normal  ProvisioningStarted     84m   metal3-baremetal-controller  Image provisioning started for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2
  Normal  ProvisioningStarted     83m   metal3-baremetal-controller  Image provisioning started for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2
  Normal  ProvisioningStarted     81m   metal3-baremetal-controller  Image provisioning started for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2
  Normal  ProvisioningStarted     80m   metal3-baremetal-controller  Image provisioning started for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2
  Normal  ProvisioningStarted     78m   metal3-baremetal-controller  Image provisioning started for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2
  Normal  ProvisioningComplete    75m   metal3-baremetal-controller  Image provisioning completed for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2
  Normal  DeprovisioningStarted   69m   metal3-baremetal-controller  Image deprovisioning started
  Normal  DeprovisioningComplete  67m   metal3-baremetal-controller  Image deprovisioning completed
  Normal  ProvisioningStarted     67m   metal3-baremetal-controller  Image provisioning started for http://172.22.0.1/images/ub-16.04-test.img
  Normal  ProvisioningError       64m   metal3-baremetal-controller  Image provisioning failed: node be43421d-c2dd-4684-9eee-c49108520e5c command status errored: {u'message': u'Error verifying image checksum: Image failed to verify against checksum. location: ub-16.04-test.img; image ID: /tmp/ub-16.04-test.img; image checksum: bad md5sum; verification checksum: fd7659f1fb028049596608f4659d5923', u'code': 500, u'type': u'ImageChecksumError', u'details': u'Image failed to verify against checksum. location: ub-16.04-test.img; image ID: /tmp/ub-16.04-test.img; image checksum: bad md5sum; verification checksum: fd7659f1fb028049596608f4659d5923'}
  Normal  ProvisioningStarted     61m   metal3-baremetal-controller  Image provisioning started for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2
  Normal  ProvisioningComplete    58m   metal3-baremetal-controller  Image provisioning completed for http://172.22.0.1/images/ub16-password-is-ubuntu.qcow2

```

**Comment by zaneb** [comment]
Would you happen to have logs handy? This output looks to be consistent with Ironic returning a different checksum for qcow2 images in the InstanceInfo from the one provided. There *are* circumstances where Ironic does that (e.g. when using an image from Glance that is not in raw format), but it doesn't appear that we should be hitting any of them (we don't use Glance). The logs that start with "checking image settings" should give us an indication if that's what's happening.

**Comment by alanmeadows** [comment]
@zaneb I will do a clean re-run of this and capture the relevant operator logs.  I casually scanned them during the process but you may see something I did not!  Will reply shortly.

**Comment by dhellmann** [comment]
I've definitely seen behavior with the event reporting API that makes me think the operator is not doing something correctly when it creates events. Sometimes it works, and sometimes events are lots.

I also learned last week that, contrary to what I thought, changing the Status fields of an object triggers reconciliation. That may mean that we're saving the error message, but then on the next iteration we clear it out.

**Comment by dhellmann** [comment]
I think we are more reliably stopping when a host encounters an error, so the message stays in the status field. @alanmeadows, are you still seeing this problem with recent versions of the operator?

**Comment by zaneb** [comment]
Let's close this and reopen if we see it again.
