### ISSUE TITLE
Support BIOS setup for baremetal server

### ISSUE THREAD

**Issue by furukawa3** [metal3-io/baremetal-operator#207]
In order to setup/reset BIOS, vendor driver is necessary.  This issue proposes a new yaml
attribute to setup BIOS with Fujitsu PRIMERGY server by using iRMC driver.

**Comment by andfasano** [comment]
@furukawa3 do you think this issue should be reopened (PR #302 looks still in progress)?

**Comment by hase1128** [comment]
@andfasano 

we need to repoen this issue(feature request).
#302 is still in progress, and we can close this issue after #302 is merged.

**Comment by hase1128** [comment]
I recreated this issue(#765 ).
