### ISSUE TITLE
add OpenAPI validation to CRD

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#214]
The operator-sdk supports generating OpenAPI validation parameters for the CRD automatically ("operator-sdk generate opensapi"). We need to

- [ ] add the current generated data, without losing any of the metadata in that file like printer columns and short names (can that also be auto-generated?)
- [ ] add a Travis test to ensure the data never grows stale

See https://github.com/operator-framework/operator-sdk/blob/master/doc/sdk-cli-reference.md#openapi and https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions

**Comment by dhellmann** [comment]
See also https://kubernetes.io/blog/2019/06/20/crd-structural-schema/ for info about upcoming requirements for structural schema definitions for CRDs.

**Comment by russellb** [comment]
This was reverted in #243
