### ISSUE TITLE
show which cleaning step is running during (de)provision operations

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#215]
Cleaning can take a little while, so we may want to expose which step is running. The [ironic docs](https://docs.openstack.org/ironic/latest/admin/cleaning.html#what-cleaning-step-is-running) explain which field has the information. We can probably just update the human-readable provisioning status message with that detail when it changes.

**Comment by maelk** [comment]
I'll look into this

**Comment by Jaakko-Os** [comment]
Hi. Please give me feedback in case I somehow missed the "beef" of this task. Testing was run in metal3-dev-env with the tests from upstream.
