### ISSUE TITLE
add coverage info to unit test output

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#221]
Go's test framework has built-in support for coverage reporting, but we don't use it. It would be good to have that information available as part of the output when unit tests are run.

**Comment by Jaakko-Os** [comment]
I'll work on this.

**Comment by Jaakko-Os** [comment]
https://github.com/metal3-io/baremetal-operator/pull/283

**Comment by dhellmann** [comment]
Thanks, @Jaakko-Os!

**Comment by dhellmann** [comment]
This was closed by #283
