### ISSUE TITLE
when a host enters the "clean failed" state the operator does not try to reset it or report an error

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#225]
If cleaning fails (such as because the ramdisk URL is wrong and the host fails to boot) the ironic node enters the "clean failed" state but the operator doesn't do anything about it and keeps trying to provision forever.

**Comment by knfoo** [comment]
Is there any way to debug this ?
It seems that my host is getting into this state and it is kind of hard to figure out what is going wrong.

Thanks

**Comment by dhellmann** [comment]
I usually have to look at the console of the host in question to see what errors are being reported there. The symptom, being stuck in a state, usually means the agent is having trouble communicating with the central services, so it can't report failures back there.

**Comment by knfoo** [comment]
Thank you.
It seemed that the problem was that uefi and dnsmasq for our hosts provided an error and therefore was stuck in a deploy / clean loop
Setting the baremetal to legacy boot fixed this for me.
