### ISSUE TITLE
Consider renaming baremetal-operator to something else

### ISSUE THREAD

**Issue by russellb** [metal3-io/baremetal-operator#227]
At least within OpenShift, it seems that we've used the term "operator" in a way that isn't consistent with other operators.  A better name could be "baremetal-controller", "baremetalhost-controller", "baremetal-controller-manager" or something similar.

The other operators I've been looking at exist to manage the lifecycle of other software running in the cluster.  We could create a "metal3-operator" for example, that knows how to launch and manage the lifecycle of our BareMetalHost controller and Ironic.

I'd like to use this issue to discuss this confusion and potentially settle on a new name.

We could also just keep the name, because naming is hard, and optionally create a "metal3-operator" too.

**Comment by sadasu** [comment]
I have a couple of suggestions: baremetal-api-controller, baremetal-cloud-controller.

**Comment by russellb** [comment]
I've thought about this some more.  Renaming things is pretty annoying and we should avoid it unless it's really necessary to avoid confusion.

The operator-sdk says it is an "SDK for building Kubernetes applications. Provides high level APIs, useful abstractions, and project scaffolding."  I consider the baremetal-operator a Kubernetes application, meaning that it runs on Kubernetes and is managed through Kubernetes APIs.

There are many operators where their operands are software that also runs on Kubernetes.  In our case, the operands are bare metal hosts.  I think it still fits the pattern.

It's true though that we could consider in the future a "metal3-operator" that knows how to run and configure the baremetal-operator, and optionally other supporting pieces.  That would be closer to what other operators I've looked at lately.

@mhrivnak thoughts?

**Comment by zaneb** [comment]
I don't know if this is the correct terminology, but I think of an operator as being a controller that's written with the Operator SDK, so it fits. It's a terrible name but that's not our fault ;)

**Comment by mhrivnak** [comment]
The definition varies, which causes confusion. The most common use of "operator" and the "operator pattern", such as what you'll see on [operatorhub.io](https://operatorhub.io/), includes three things:
* A CRD that expresses how to deploy a workload
* A controller that watches the CRD and responds to events by deploying and managing the workload
* "human operational knowledge" in code; the controller knows how to upgrade, backup, restore, scale, repair, rebalance, rotate, vacuum, pre-warm, etc.

That's largely what the operator framework is focused on. The [blog post introducing operators](https://coreos.com/blog/introducing-operators.html) may be of interest to you.

But you'll see the word "operator" applied to other kinds of controllers sometimes. The "operator lifecycle manager" can be used to install and manage a controller that doesn't fit the above definition.

Likewise, the cluster-version-operator [describes its job](https://github.com/openshift/cluster-version-operator/blob/master/docs/dev/operators.md#operator-integration-with-cvo) as "installs other operators onto a cluster". But clearly it is used to install many infra-related controllers that are a far cry from the above definition. Those controllers are expected to communicate their state back to CVO on a resource called `ClusterOperator`.

So in that way, I think the definition has expanded to include any controller process that's participating in the same ecosystem and using the same tooling as a "classic" operator.

Adding to the confusion, "controller" has increasingly come to mean [one of these](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.1.12/pkg/controller/controller.go#L40-L57), or at least a single reconcile loop and its associated logic. Often a controller doesn't have its own resource; for example, several controllers run in a cluster that watch Nodes and do various tasks in response to changes. It's normal for a single operator to include more than one of these controllers in the same process, each watching a different primary resource. So referring to a process running in a pod as a "controller", even if that process is not an "operator" per the above definition, is still not a precise descriptor.

So in terms of whether baremetal-operator should be called an "operator" or "controller", that's a long way of saying "meh". :wink: Someone in the openshift ecosystem might have a stronger opinion on the preferred convention. But I think it looks and behaves an awful lot like an operator (per the above definition), even if its operand is not a piece of software.

**Comment by russellb** [comment]
Thanks for the detailed thoughts, @mhrivnak.  I propose we close this as "won't fix" and just accept the potential confusion as the confusion is clearly not unique to this piece of software.  We just need to continue to ensure we have good documentation that describes what the baremetal-operator does.
