### ISSUE TITLE
label host to allow better selection

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#232]
The actuator supports searching for hosts based on label selectors. The host controller should add labels to the host based on discovered information (hardware profile, RAM, other settings) to take advantage of that ability. https://github.com/metal3-io/cluster-api-provider-baremetal/blob/master/pkg/cloud/baremetal/actuators/machine/actuator.go#L279

**Comment by alanmeadows** [comment]
@dhellmann Trying to align this request and https://github.com/metal3-io/cluster-api-provider-baremetal/issues/81

Do you think there is value in creating automatic labels for a node, potentially a large number of them post-discovery, e.g.:

```
hardware-cpu-count-4
hardware-ram-7
...
```

If you can select on more than just labels, e.g. expressing `hardware.cpu.count >= 4` or `hardware.cpu.ram: 7` directly.  It seems somewhat redundant and potentially a label explosion reducing the value of any other labels we do want to add.  I know you did note we likely need both but I suppose I am questioning that when we start talking about inventory which would result in so many labels.

**Comment by dhellmann** [comment]
@alanmeadows yeah, I was thinking of some sort of minimal set of values starting with hardware profile -- that will be useful in places like a UI as well. Maybe we want to aggregate some values that would be harder to establish, like total amount of disk space, although I could see exposing that as a field too (and maybe the selector logic supports expressions so we don't even need that). I hadn't done the analysis, yet, so if you're thinking about this I would love to have your input on what might be useful and what would be overly redundant.

**Comment by fmuyassarov** [comment]
I'm working on this.

**Comment by dhellmann** [comment]
Thanks, @fmuyassarov !

**Comment by zaneb** [comment]
Similar discussion happening in metal3-io/metal3-docs#60

**Comment by dhellmann** [comment]
We have https://github.com/metal3-io/metal3-docs/pull/60 and the new component to handle this.
