### ISSUE TITLE
Need hardware information for externally provisioned hosts

### ISSUE THREAD

**Issue by russellb** [metal3-io/baremetal-operator#242]
The `baremetal-operator` supports creating `BareMetalHost` objects that represent hosts that were provisioned prior to running the `baremetal-operator`.  For example, in the OpenShift integration, we first bootstrap a 3 master cluster, and then run the `baremetal-operator` to take over provisioning from then on.

All other hosts (workers) are run through Ironic inspection by the `baremetal-operator` and have hardware details on the `BareMetalHost`.  These details include IP addresses and a hostname that `cluster-api-provider-baremetal` copies over to the `Machine` `status`.  We are not able to populate the addresses in the `Machine` `status` for externally provisioned hosts.

To resolve this, we first need a way to provide that information other than `baremetal-operator` running the host through Ironic inspection.

One complication is that all of the hardware details are in the `status` section, so it's not as simple as just including it when creating the `BareMetalHost`.  One option would be to allow a new annotation that includes a json blob of hardware details, or an annotation with a reference to a `ConfigMap` that has all of the hardware details.  For an externally provisioned host, the `baremetal-operator` would copy hardware details from this annotation to the `BareMetalHost` `status`.  Other ideas welcome!

**Comment by dhellmann** [comment]
I expect this to be resolved when https://github.com/metal3-io/metal3-docs/blob/master/design/hardware-status.md is implemented.

**Comment by russellb** [comment]
> I expect this to be resolved when https://github.com/metal3-io/metal3-docs/blob/master/design/hardware-status.md is implemented.

Is someone actively working on this?  Do you know of another issue tracking that work?

**Comment by dhellmann** [comment]
@juliakreger @iurygregory I think there's some work upstream in ironic on this, isn't there? Can you link any gerrit reviews here, please?

**Comment by dhellmann** [comment]
And to be clear, there will be work in the operator to take advantage of the fact that hardware data may update outside of the explicit inspection process.

**Comment by juliakreger** [comment]
> @juliakreger @iurygregory I think there's some work upstream in ironic on this, isn't there? Can you link any gerrit reviews here, please?

https://review.opendev.org/#/c/666198/ is the outstanding item in review right now to provide the communication channel data in for updated introspection data. Sensor data collected by ironic should be exposed to prometheus as soon as the change to add querying of the ironic prometheus exporter endpoint merges which takes care of the other half of the conundrum. I think the only thing that is questionable is full smart data for NVMe devices which is seemingly going to take some additional work upstream or we write yet another thing to enumerate through and expose that data individually which may be a path taken.

**Comment by juliakreger** [comment]
I guess that makes sense because for day-2 ops it doesn't make sense for a
UI to go speak with ironic about the hardware.

**Comment by russellb** [comment]
Note that the most critical part of this is just the IP addresses and hostnames, as that blocks having a functional deployment.  Everything else is "nice to have"

**Comment by cdvultur** [comment]
Hi @russellb 
Do we plan to fix this one ? 
Seems that it got closed because of inactivity.

**Comment by dhellmann** [comment]
#470 provides the annotation described in the description of this issue. Nothing currently populates that annotation for externally provisioned hosts, so it's not the full solution.
