### ISSUE TITLE
Baremetal operator operation understanding

### ISSUE THREAD

**Issue by rkamudhan** [metal3-io/baremetal-operator#260]
![image](https://user-images.githubusercontent.com/20394160/61157015-c26f1980-a4a9-11e9-8067-fdaa7124afbb.png)

Is this correct architecture to use the bare metal operator without VMs or libvirt?

**Comment by russellb** [comment]
I would expect the provisioning bridge to be attached to a different network adaptor, not one for an existing network.  DHCP is provided via the Ironic pod for the provisioning network.

**Comment by rkamudhan** [comment]
@russellb  Please let me know, whether this design model is correct ? 
![image](https://user-images.githubusercontent.com/20394160/61250708-4248ee00-a70d-11e9-8dff-90e0f11324b1.png)

**Comment by russellb** [comment]
I'd have eno1 on "Net A", and eno2 on a new "Net B".  Your deployed server will need two interfaces as well

**Comment by rkamudhan** [comment]
@russellb bmc address is `ipmi://172.16.1.19:6233`, and I having two networks A and B. A is for the management and B is for provisioning and for IPMI is this is correct?
 
![image](https://user-images.githubusercontent.com/20394160/61254491-7de9b500-a719-11e9-81ea-110efc9cac08.png)

**Comment by russellb** [comment]
getting closer ... eno2 would be `182.22.0.N`, an address provided by DHCP, served by `dnsmasq` run along side Ironic.

The baremetal server probably has a 3rd interface for the BMC.  That can be connected to any network, but must be routable to the machine running the baremetal-operator.

**Comment by rkamudhan** [comment]
Is this a typo? you mean `eno2 would be 172.22.0.N, an address provided by DHCP, served by dnsmasq run along side Ironic.` right ? it is assigned by DHCP inside Ironic pod running `/sbin/dnsmasq`

![image](https://user-images.githubusercontent.com/20394160/61259691-1f7c0100-a730-11e9-9da2-372a9f43f44d.png)

so my `/etc/networks/interfaces` should be something like this
```
#cat vim /etc/networks/interfaces/
auto eno2
iface eno2 inet manual

auto provisioning
iface provisioning inet static
  address 172.22.0.1
  network 172.22.0.0
  netmask 255.255.255.0
  broadcast 172.1.1.255
  gateway 172.22.1.1
  dns-nameservers 8.8.8.8
  bridge_ports eno1
  bridge_stp off
  bridge_fd 0
  bridge_maxwait 0
```
Bring up only the provisioning interfaces.
Do I require to take care of any other routing?

**Comment by russellb** [comment]
Yes, that was a typo, sorry.

There would be no address on `eno2` on the baremetal operator machine.  The address on the bridge is sufficient.  Also, the address on `eno2` on the baremetal server would be in the `172.22.0.N` range.

**Comment by rkamudhan** [comment]
Thanks a lot for your works. Really cleared a lot of assumptions from my side. Based your answer and longKB answer here in slack, the `eno2` in the baremetal operator server get the IP address form the `dnsmasq` DHCP server inside the Ironic pod.  Can I have at least 2 networks provisioning net(Red Network) and baremetal network (the blue network that has the NICs that support IPMI) can be the same right ? Is that I have to create provisioning interface `172.0.0.101` or `172.0.0.1.N` in all the baremetal servers, where I want to install OS.  In my lab, I am not using baremetal server as worker node, I am using them to just provision the OS. So if the NIC support IPMI is enough right?  Just for the clarification the Ironic pod only runs on the Baremetal operator machine ? as show in the diagram. From LongKB and your answer, it is clear that  provisioning interface in all the servers will get IP address from the DHCP server. Thanks once again for answers the questions in slack. Really appreciate it. 
![image](https://user-images.githubusercontent.com/20394160/61261769-bf895880-a737-11e9-9b40-9589988c1a8d.png)

**Comment by rkamudhan** [comment]
Sorry for too many question, I am narrowing down my connectivity issues now. I settling down with 3 network solution as show in my diagram.

![image](https://user-images.githubusercontent.com/20394160/61341336-b614f480-a7fa-11e9-8582-c04499b6efac.png)


 I used the ipmitool to set the static IP address source `172.31.1.9` in the baremetal operator machine and `172.31.1.17` in Baremetal server, where I want to provisioning the OS. So in the `BareMetalHost` crd object. we specifies `bmc` as follow
```apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
    name: example-baremetalhost
    namespace: cluster-1ns
spec:
  online: true
  bmc:
    address: ipmi://172.31.1.17:6233
    credentialsName: example-baremetalhost-secret```
So it means basically in the BaremetalCRD we have to give the ipmi-lan support IP address of the baremetal server, where we want to do the provisioning right?
image.png

**Comment by dhellmann** [comment]
@rkamudhan Yes, the "address" field should include the IP address of the BMC for the host to which you are provisioning. The port number in your example looks like it corresponds to a virtualbmc port, so if you are using a physical server that is unlikely to be correct. The port number for IPMI defaults to 623, so you can leave that part of the address out, which would give you

```
bmc:
  address: ilmi://172.31.1.17
  credentialsName: example-baremetalhost-secret
```

**Comment by rkamudhan** [comment]
Yes, exactly. I removed it and now it working.

Thanks metal3 team for support on metal3 support with ipmi, I could provision my baremetal server. I am having couple of question on the baremetal operator state for baremetal machine. What is the difference between "Ready" and "Provisioned ". from the https://github.com/metal3-io/baremetal-operator/blob/9c5f7f7c7fa07f7f3de86f07b1a2405cc5fbb486/docs/baremetalhost-states.md, it is not clear for my understand, Could you explain little bit more on this? In my baremetal server, I don't see "Ready" state, it is only inspection, provisioning and provisioned. One more question, "Deprovisioning" state remove the image installed previously in the baremetal right. If there is a error during the "provisionings" state, is that mandatory to do "deprovisioning", and then do the "provisioning" ? . Last question, what is expected behaviour, when you do "kubectl delete bmh -n metal3", is that image is deprovisioned or just the ironic is wiping out the record of the node UUID.

**Comment by dhellmann** [comment]
> Yes, exactly. I removed it and now it working.

Good!

> Thanks metal3 team for support on metal3 support with ipmi, I could provision my baremetal server. I am having couple of question on the baremetal operator state for baremetal machine. What is the difference between "Ready" and "Provisioned ". from the https://github.com/metal3-io/baremetal-operator/blob/9c5f7f7c7fa07f7f3de86f07b1a2405cc5fbb486/docs/baremetalhost-states.md, it is not clear for my understand, Could you explain little bit more on this? In my baremetal server, I don't see "Ready" state, it is only inspection, provisioning and provisioned. 

The host object has 2 fields used for state tracking, which makes mapping between the diagram and the object content a little confusing. We'll need to work on that. The [API document](https://github.com/metal3-io/baremetal-operator/blob/9c5f7f7c7fa07f7f3de86f07b1a2405cc5fbb486/docs/api.md#status-fields) discusses the fields, including operationalStatus (which will show "OK" when a host is fully registered but not provisioned, and therefore in the "Ready" state) and provisioning.state which holds the more detailed information about the processing being done by ironic to register, clean, inspect, and provision the host.

> One more question, "Deprovisioning" state remove the image installed previously in the baremetal right. If there is a error during the "provisionings" state, is that mandatory to do "deprovisioning", and then do the "provisioning" ? .

If there is an error during provisioning, the operator should try again. I think it does not right now in some cases, and that's a bug. If you have details about a case where that happened to you, filing a new bug report here on GitHub would be helpful in figuring out which cases have gaps.

>  Last question, what is expected behaviour, when you do "kubectl delete bmh -n metal3", is that image is deprovisioned or just the ironic is wiping out the record of the node UUID.

Deleting the host deprovisions it.

**Comment by dhellmann** [comment]
I think we have answered all of the questions here. If not, please re-open this issue (or open a new one).
