### ISSUE TITLE
Node properties are not supported

### ISSUE THREAD

**Issue by redixin** [metal3-io/baremetal-operator#265]
It is not possible to provide `properties` when creating a node.

See https://developer.openstack.org/api-ref/baremetal/?expanded=create-node-detail#create-node

And https://github.com/gophercloud/gophercloud/blob/v0.2.0/openstack/baremetal/v1/nodes/requests.go#L220

**Comment by russellb** [comment]
Can you expand on your use case that needs feeding data into this API?

**Comment by redixin** [comment]
@russellb e.g. if uefi is the only option `--property capabilities='boot_mode:uefi'`

**Comment by russellb** [comment]
OK - a design goal is to keep Ironic hidden as an implementation detail.  Is support for UEFI only hosts the issue?  Should we rename the issue something like: `Need support for UEFI only hosts` ?

**Comment by dtantsur** [comment]
Aren't we going to switch to UEFI-only anyway?

**Comment by alexz-kh** [comment]
>Aren't we going to switch to UEFI-only anyway?
isn't it will be bad idea? not all deployment require uefi and not even all hw support it properly(at least "old" hw). i guess, it might drop some compatibility layer..

**Comment by dhellmann** [comment]
Will this be resolved if we finish the work described for #207?

**Comment by zaneb** [comment]
I think this is covered by #207.
