### ISSUE TITLE
update power management to default to soft shutdown

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#273]
The current power-off behavior when Online=false is to just turn off the power. We should default to a soft power off, which would allow the BMC to signal to the OS that the power is going to be pulled and let the OS shutdown cleanly. We will need to choose a reasonable timeout for that shutdown process.

https://docs.openstack.org/api-ref/baremetal/?expanded=change-node-power-state-detail

**Comment by Xenwar** [comment]
I will look into this
