### ISSUE TITLE
document launching the operator within the cluster

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#28]
The dev instructions talk about launching the operator outside of the cluster for development. We should add instructions for launching it inside the cluster, like one would do for production systems.

**Comment by dhellmann** [comment]
We have deploy/operator_ironic.yaml but it's not obvious from the name what that is and I don't know if it's up to date. @imain is that deployment file complete?

**Comment by russellb** [comment]
I'd love to see this marked complete along with: https://github.com/metal3-io/metal3-dev-env/issues/41

We should document here, but also have it working in metal3-dev-env
