### ISSUE TITLE
How to add parameters for BMC setup (redfish)

### ISSUE THREAD

**Issue by maelk** [metal3-io/baremetal-operator#286]
This is a general question about BMC drivers, though taking the Redfish example for clarity.

Redfish driver can take two additional parameters : redfish_verify_ca and redfish_auth_type . How can we enable the user to specify those ? 

A first option could be to pass them as options in the Address, such as : `redfish://192.168.1.1/redfish/v1/Systems/Abcd?redfish_verify_ca=false&redfish_auth_type=basic` and let the bmc driver take care of parsing the query arguments. This would require modifying the getTypeHostPort function and all drivers to take an addtional parameter, the query part.

A second option could be to extend the BMCDetails struct to add a nested struct for additional bmc driver configuration. This means modifying the api and require deeper modifications of the baremetal-operator.

Do you have any opinions on which way to go ?

**Comment by maelk** [comment]
A test implementation for option 1 can be found here : https://github.com/metal3-io/baremetal-operator/pull/287 for discussion

**Comment by stbenjam** [comment]
It seems like we have consensus now they should be additional fields in the struct instead of url parameters.  Can we close this?

**Comment by maelk** [comment]
yes, sure
/close
