### ISSUE TITLE
Leader election does not work correct after node power off

### ISSUE THREAD

**Issue by cynepco3hahue** [metal3-io/baremetal-operator#295]
## Environment

```
# oc get nodes
NAME       STATUS   ROLES           AGE   VERSION
master-0   Ready    master,worker   21h   v1.14.0+5ccbd432f
master-1   Ready    master,worker   21h   v1.14.0+5ccbd432f
master-2   Ready    master,worker   21h   v1.14.0+5ccbd432f

# oc get pods -n openshift-machine-api -o wide
NAME                                           READY   STATUS    RESTARTS   AGE   IP               NODE       NOMINATED NODE   READINESS GATES
cluster-autoscaler-operator-6b5957fbd8-zcwm4   1/1     Running   2          20h   10.129.0.59      master-2   <none>           <none>
machine-api-controllers-6b79798968-bqmj4       3/3     Running   0          17h   10.128.0.56      master-1   <none>           <none>
machine-api-operator-857dd85bb9-8jcfm          1/1     Running   0          17h   10.128.0.57      master-1   <none>           <none>
metal3-7685f8bdc9-r7zz2                        8/8     Running   0          17h   192.168.111.22   master-2   <none>           <none>

# oc get bmh --namespace openshift-machine-api
NAME                 STATUS   PROVISIONING STATUS      CONSUMER        BMC                         HARDWARE PROFILE   ONLINE   ERROR
openshift-master-0   OK       externally provisioned   demo-master-0   ipmi://192.168.111.1:6230                      true     
openshift-master-1   OK       externally provisioned   demo-master-1   ipmi://192.168.111.1:6231                      true     
openshift-master-2   OK       externally provisioned   demo-master-2   ipmi://192.168.111.1:6232                      true
```

## How to reproduce

1. Check where the BMO pod is running, in our case, it is running on the `master-2`
2. Power-off the `master-2` node via setting `spec.Online: false`, `# oc -n openshift-machine-api edit bmh openshift-master-2`
3. Verify that node does not run anymore under the libvirt
```
# virsh list
 Id    Name                           State
----------------------------------------------------
 10    openshift_master_1             running
 13    openshift_master_0             running
```
4. Verify that the pod restarted
```
# oc get pods -n openshift-machine-api -o wide
NAME                                           READY   STATUS        RESTARTS   AGE   IP               NODE       NOMINATED NODE   READINESS GATES
cluster-autoscaler-operator-6b5957fbd8-zcwm4   1/1     Running       2          21h   10.129.0.59      master-2   <none>           <none>
machine-api-controllers-6b79798968-bqmj4       3/3     Running       0          17h   10.128.0.56      master-1   <none>           <none>
machine-api-operator-857dd85bb9-8jcfm          1/1     Running       0          17h   10.128.0.57      master-1   <none>           <none>
metal3-7685f8bdc9-5nd65                        8/8     Running       0          69s   192.168.111.20   master-0   <none>           <none>
metal3-7685f8bdc9-r7zz2                        8/8     Terminating   0          17h   192.168.111.22   master-2   <none>           <none>
```
5. Verify that new pod fails to get leader election
```
# oc -n openshift-machine-api logs metal3-7685f8bdc9-5nd65 -c metal3-baremetal-operator
{"level":"info","ts":1567497633.7019377,"logger":"cmd","msg":"Go Version: go1.11.6"}
{"level":"info","ts":1567497633.7019632,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1567497633.7019677,"logger":"cmd","msg":"Version of operator-sdk: v0.8.0+git"}
{"level":"info","ts":1567497633.7021453,"logger":"cmd","msg":"Component version: metal3-io/baremetal-operator was not built with version info"}
{"level":"info","ts":1567497633.7024767,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1567497699.3227773,"logger":"leader","msg":"Found existing lock","LockOwner":"metal3-7685f8bdc9-r7zz2"}
{"level":"info","ts":1567497699.3331923,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1567497700.4640396,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1567497702.8499641,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1567497707.3879468,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1567497716.0989492,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1567497733.4708111,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1567497751.678254,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1567497767.9052875,"logger":"leader","msg":"Not the leader. Waiting."}
{"level":"info","ts":1567497784.4164011,"logger":"leader","msg":"Not the leader. Waiting."}
...
```

**Comment by dhellmann** [comment]
> 1. Verify that the pod restarted
> 
> ```
> # oc get pods -n openshift-machine-api -o wide
> NAME                                           READY   STATUS        RESTARTS   AGE   IP               NODE       NOMINATED NODE   READINESS GATES
> cluster-autoscaler-operator-6b5957fbd8-zcwm4   1/1     Running       2          21h   10.129.0.59      master-2   <none>           <none>
> machine-api-controllers-6b79798968-bqmj4       3/3     Running       0          17h   10.128.0.56      master-1   <none>           <none>
> machine-api-operator-857dd85bb9-8jcfm          1/1     Running       0          17h   10.128.0.57      master-1   <none>           <none>
> metal3-7685f8bdc9-5nd65                        8/8     Running       0          69s   192.168.111.20   master-0   <none>           <none>
> metal3-7685f8bdc9-r7zz2                        8/8     Terminating   0          17h   192.168.111.22   master-2   <none>           <none>
> ```

This shows that both pods are still there, with the old one still "Terminating". Is the leader lock released when the original pod is finally removed?

**Comment by cynepco3hahue** [comment]
What do you mean by finally? When do you expect that k8s will remove the pod in case of node failure? IIRC it will not remove the pod until will finish a volume and network clean-up and it can not finish it, because of that node not responsive.
I can manually remove the pod forcefully via `oc -n openshift-machine-api delete pod metal3-7685f8bdc9-jxs9t --force --grace-period=0` and it will remove the lock, but I think we want to avoid manual intervention.

**Comment by cybertron** [comment]
I also noticed that in my environment, it takes a long time for the pod to be restarted. 11 minutes from the time I took down the node to when the new metal3 pod was started.

**Comment by dhellmann** [comment]
> What do you mean by finally? When do you expect that k8s will remove the pod in case of node failure? IIRC it will not remove the pod until will finish a volume and network clean-up and it can not finish it, because of that node not responsive.

The whole point of kubernetes is that it manages pod lifecycles. I would expect it to eventually figure out that the node is no longer there, restart the pods on other nodes, and do something to clean up the state it was tracking for the old pods. I'm asking if you waited long enough for it to do all of that before deciding that something in this 1 operator wasn't working right.

If this operator is the only one that doesn't work, then I need to understand why the change you are proposing fixes that. If this change is correct, then I think there is a bug in the operator-sdk, since the code you're modifying was generated by that tool. So I would like to ensure we have a bug reported there, and preferably a fix, so we don't introduce the same problem into other operators.

**Comment by cybertron** [comment]
FWIW, using #296 in my local environment did fix the problem with the metal3 pod not migrating correctly when a node is taken down. I will note that the cluster didn't seem to notice that the pod was not available until I tried to power the node back on, at which point it did stand up a new pod and terminate the old one. That isn't ideal since it introduced a largely unnecessary delay, but at least recovery from the downed node didn't require manual intervention.

**Comment by cynepco3hahue** [comment]
@dhellmann The k8s hardly depends on the kubelet, if it lost connection with the kubelet it can't do anything. I waited 20 minutes without any progress.
Did you check the node failure scenario when you added leader election code, did it work before?
