### ISSUE TITLE
let ironic look up the image checksum value

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#298]
The ironic provisioner code looks at the checksum value we have and, if it is a URL, fetches the content to pass to ironic. The version of ironic we have in the images now can do that step for itself, so we should let it.

**Comment by Jaakko-Os** [comment]
I'll look into this

**Comment by hardys** [comment]
@derekhiggins did your test issues related to this get resolved yesterday?

We switched the metal3 ironic images to train yesterday, and downstream we also have train-based images available now, so I think this should be good to go, modulo feedback from Derek re his test issues.
