### ISSUE TITLE
Add option to wipe disks when deprovisioning hosts

### ISSUE THREAD

**Issue by russellb** [metal3-io/baremetal-operator#32]
Ironic has the ability to wipe disks as part of the deprovisioning workflow.  This is time consuming, so we assume this will not be default behavior.  We still may want to provide this as optional behavior in the future.

**Comment by juliakreger** [comment]
If we were to do this, with the current constraints, it might be good to take the following path:

1. unprovision the node
2. move to manageable state
3. request manual cleaning  via a "clean" provision state verb
3.1. Inside the manual cleaning step, we request the "erase_devices" step be executed for cleaning which would perform a disk shred/ATA Erase where possible.
4) When cleaning is done, ironic will report the node in the manageable state.

**Comment by alanmeadows** [comment]
There is some advantage to also having some control over _which_ disks are cleaned.

At a high level, some users may want all disks found on the host cleaned or only some of them cleaned.  Having an ability to express that somehow (what that expression looks like is open to discussion) and have that passed to the erase_devices step would be useful.

**Comment by jaxklag** [comment]
Hello,

The [metal3 automatedcleaning documentation](https://book.metal3.io/bmo/automated_cleaning) indicates that erase_devices is still not implemented : 

_Note: Ironic supports full data removal, which is not currently exposed in Metal3._

Would it be possible to implement the "erase_devices_express" and even "erase_devices" provided by Ironic ?

As to me erase_devices_express is the best compromise but erase_devices still need to be implemented to let the choice to the user the way he wants to wipe disks.
Also if data disks do not support hardware assisted erasure.

As asked by @alanmeadows, be able to choose which disks (those who don't support hardware assisted erasure) will be wiped in each modes would be very usefull to.

Regards,
