### ISSUE TITLE
Allows RAID Interface to be set by vendor driver

### ISSUE THREAD

**Issue by longkb** [metal3-io/baremetal-operator#320]
Currently, RAID interface is not set when we create Ironic node. The default interface will be set as `no-raid`. If we want to execute RAID configuration, we need to set this property as supported vendor's RAID interface

**Comment by zaneb** [comment]
This issue specifically affects drivers with a default RAIDInterface of `no-raid`. Specifically, I believe the iRMC BMC type is the only current one that provides a native RAID interface but defaults to `no-raid`. (The iDRAC driver defaults to `enabling RAID`; the iLO and IPMI drivers support only software RAID.)

**Comment by longkb** [comment]
> 
> 
> This issue specifically affects drivers with a default RAIDInterface of `no-raid`. Specifically, I believe the iRMC BMC type is the only current one that provides a native RAID interface but defaults to `no-raid`. (The iDRAC driver defaults to `enabling RAID`; the iLO and IPMI drivers support only software RAID.)

Thanks. I got your point :D

**Comment by zaneb** [comment]
Fixed by #319
