### ISSUE TITLE
enable pruning in openapi settings

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#327]
We need to ensure that pruning is turned on in the openapi settings.

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#pruning-versus-preserving-unknown-fields describes the field

https://github.com/openshift/api/pull/478/commits/db65909e9583109098bc5189fad304f82ceac667 is an example of setting it

**Comment by dhellmann** [comment]
I think this depends on #326

**Comment by zaneb** [comment]
We'll [get this](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/#pruning-don-t-preserve-unknown-fields) by default when we switch to apiVersion `apiextensions.k8s.io/v1`. Supposedly there's a way to opt in with `apiextensions.k8s.io/v1beta1` (the apiVersion in the current CRD), but it's not obvious that there's a way to make kubebuilder autogenerate the opt-in.

**Comment by zaneb** [comment]
We updated to k8s 1.16, so I think we should now be able to switch to v1 (currently still at v1beta1 though).

**Comment by zaneb** [comment]
/remove-lifecycle stale

Since the CRD is generated by the operator-sdk, this is dependent on the operator-sdk generating it with version `apiextensions.k8s.io/v1`. As of v0.13.0 it was not.

**Comment by zaneb** [comment]
Good news: kubebuilder [now supports](https://book.kubebuilder.io/reference/markers/crd-processing.html) generating the CRD with the `x-kubernetes-preserve-unknown-fields` option.
Bad news: it only supports setting it to true :facepalm:

So the solution remains switching to `apiextensions.k8s.io/v1`.
