### ISSUE TITLE
operator only reconciles one host at a time

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#336]
By default the operator is only reconciling one host at a time. We should investigate higher levels of concurrency.

https://github.com/kubernetes-sigs/controller-runtime/blob/v0.3.0/pkg/controller/controller.go#L33-L34

**Comment by kirankt** [comment]
@dhellmann I have question. Since the concurrency setting is set during the start of the controller, how do we come up with a sane number (>1), which is proportional to the number of node? Thanks.

**Comment by dhellmann** [comment]
I'm not sure we need it to be related to the number of nodes. Ironic is doing most of the work that takes a lot of time. The reconcile loop just calls the Ironic APIs.
