### ISSUE TITLE
Prevent deletion of BareMetalHost if MachineRef is set

### ISSUE THREAD

**Issue by russellb** [metal3-io/baremetal-operator#34]
If a BareMetalHost is associated with a Machine, we want to prevent deletion of a BareMetalHost.  In that case, the Machine must be deleted first.

This can be done via an admission webhook.

**Comment by dhellmann** [comment]
I wonder if a better solution to this is to have the actuator add its own finalizer? @mhrivnak any thoughts?

**Comment by mhrivnak** [comment]
I think I suggested the webhook over a finalizer, and here's why: A finalizer is helpful if you need to do some work before deletion finishes. But a finalizer is not an effective way to prevent deletion. Once the deletion timestamp is set on a resource, you can't really go back and unset it. Maybe the API would allow that to happen (although I wouldn't be surprised if that was denied), but any other controllers that have added a finalizer will have initiated their work for handling deletion.

If we want to prevent deletion in a given situation, an admission webhook is the way to go. That would let us flat-out deny a request to delete a resource without the resource being affected at all.

**Comment by dhellmann** [comment]
Ah, yes, I remember that conversation. And now we have it written down! :-)

**Comment by russellb** [comment]
As of #193, the MachineRef is changing to a more generic field.  WIth that move, I don't think this change makes as much sense anymore.  Since it's not specifically a Machine reference, we shouldn't make BMO behavior based on how we expect the machine API to be used.

We should just fix the problem over in cluster-api-provder-baremetal.

**Comment by dhellmann** [comment]
I agree that rather than blocking the host from being deleted we want to resolve the broken machine when that happens.
