### ISSUE TITLE
Host hardware details should include GPUs/graphics cards

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#341]
We expose storage and networking details now, but not extra compute resources like GPUs. We should expose whatever we can through inspection.

**Comment by zaneb** [comment]
I totally agree with this, but ironic-python-agent doesn't seem to give us much here. We do get a list of PCI vendor/product IDs, but that's not super helpful without a whitelist of stuff to look for.

The `clinfo` command will give info about any OpenCL-compatible hardware. I'm not sure to what extent that requires out-of-tree drivers to work (Nvidia drivers are proprietary). But adding support for that in ironic-python-agent would likely be a good first step.

**Comment by elfosardo** [comment]
since we probably need nvidia drivers anyway, there could also be the possibility to use the output of nvidia-smi
