### ISSUE TITLE
BMO Container Crashing

### ISSUE THREAD

**Issue by kanwar-saad** [metal3-io/baremetal-operator#342]
After unrecorded sequence of events BMO started crashing. I am creating this issue so that if someone can figure out from the stack trace that where to handle a null pointer check. Mostly I was creating and deleting baremetal hosts and at some point, the host status was stuck at provisioning. And then container started crashing. Here is the stack trace.

`{"level":"info","ts":1573730775.8003469,"logger":"cmd","msg":"Go Version: go1.10.8"}
{"level":"info","ts":1573730775.8003712,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1573730775.8003817,"logger":"cmd","msg":"Version of operator-sdk: v0.4.0+git"}
{"level":"info","ts":1573730775.8005767,"logger":"cmd","msg":"Component version: metal3-io/baremetal-operator was not built with version info"}
{"level":"info","ts":1573730775.8372185,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1573730775.8375285,"logger":"baremetalhost_ironic","msg":"ironic settings","endpoint":"http://172.22.0.2:6385/v1/","inspectorEndpoint":"http://172.22.0.2:5050/v1/","deployKernelURL":"http://172.22.0.2:6180/images/ironic-python-agent.kernel","deployRamdiskURL":"http://172.22.0.2:6180/images/ironic-python-agent.initramfs"}
{"level":"info","ts":1573730775.837645,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"metal3-baremetalhost-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1573730775.83784,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"metal3-baremetalhost-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1573730775.8379364,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1573730793.40161,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"metal3-baremetalhost-controller"}
{"level":"info","ts":1573730793.503026,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"metal3-baremetalhost-controller","worker count":1}
{"level":"info","ts":1573730793.5038235,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"metal3","Request.Name":"bm-node-2"}
{"level":"info","ts":1573730793.5045817,"logger":"baremetalhost","msg":"provisioning","Request.Namespace":"metal3","Request.Name":"bm-node-2","provisioningState":"provisioning"}
{"level":"info","ts":1573730793.5524938,"logger":"baremetalhost_ironic","msg":"found existing node by ID","host":"bm-node-2"}
{"level":"info","ts":1573730793.5526233,"logger":"baremetalhost_ironic","msg":"provisioning image to host","host":"bm-node-2","state":"manageable"}
E1114 11:26:33.552915       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/ironic.go:917
/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:529
/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:225
/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:48
/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:85
/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:225
/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213
/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa35c06]

goroutine 155 [running]:
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x1138620, 0x1b930b0)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic.(*ironicProvisioner).Provision(0xc4203111f0, 0xc420636580, 0xc, 0x0, 0x0, 0x0, 0x3aac69960615e28f, 0x2)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/ironic.go:917 +0x156
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).actionProvisioning(0xc4204d6020, 0x13bec80, 0xc4203111f0, 0xc420311180, 0x12a0884, 0xc4204d9920, 0xc, 0xc42062c201)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:529 +0x10f
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).handleProvisioning(0xc4200191c0, 0xc420311180, 0xc4200c4928, 0xc42062c200, 0xc42062c1f0, 0xc4200c48f0)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:225 +0xb6
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).(github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.handleProvisioning)-fm(0xc420311180, 0xc420644570, 0xc4204d9920, 0xc, 0xc4200c4990)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:48 +0x34
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).ReconcileState(0xc4200191c0, 0xc420311180, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:85 +0x317
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).Reconcile(0xc4204d6020, 0xc42033dc10, 0x6, 0xc42033dc80, 0x9, 0x1ba6400, 0x0, 0xc420350ae0, 0xc4200f6bb0)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:225 +0x800
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc420370140, 0x0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213 +0x1c6
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42062c140)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42062c140, 0x3b9aca00, 0x0, 0xc420471701, 0xc42018ccc0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42062c140, 0x3b9aca00, 0xc42018ccc0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x35b`

**Comment by hardys** [comment]
Since no reproducer is provided, and the line numbers from the stacktrace are now stale after a month, I'll close this as I don't think it's really actionable.

@kanwar-saad thanks for the report - if you see this again please do raise another issue with the steps to reproduce, and/or any other information we can potentially use for debugging.

**Comment by zaneb** [comment]
Assuming that the version tested was d46ea96a75a5c361abbb722f125de46d5683a71c (the most current one when this issue was opened), it looks like the issue here is that we're in the Provisioning state, but the [Image is `nil`](https://github.com/metal3-io/baremetal-operator/blob/d46ea96a75a5c361abbb722f125de46d5683a71c/pkg/provisioner/ironic/ironic.go#L917). Presumably the reproducer would involve starting provisioning by specifying an image, and then removing it again.

However, there is a [check](https://github.com/metal3-io/baremetal-operator/blob/d46ea96a75a5c361abbb722f125de46d5683a71c/pkg/controller/baremetalhost/host_state_machine.go#L220) [for that](https://github.com/metal3-io/baremetal-operator/blob/d46ea96a75a5c361abbb722f125de46d5683a71c/pkg/apis/metal3/v1alpha1/baremetalhost_types.go#L582-L584) right before the [call](https://github.com/metal3-io/baremetal-operator/blob/d46ea96a75a5c361abbb722f125de46d5683a71c/pkg/controller/baremetalhost/host_state_machine.go#L225) in which it is crashing, so this remains something of a mystery to me.
