### ISSUE TITLE
No conductor service registered which supports driver redfish+http

### ISSUE THREAD

**Issue by derekhiggins** [metal3-io/baremetal-operator#352]
When running dev-scripts with "BMC_DRIVER=redfish", it fails with the following error

level=error msg="Error: Bad request with: [POST http://172.22.0.2:6385/v1/nodes], error message: {\"error_message\": \"{\\\"debuginfo\\\": null, \\\"faultcode\\\": \\\"Client\\\", \\\"faultstring\\\": \\\"No valid host was found. Reason: No conductor service registered which supports driver redfish+http for conductor group \\\\\\\"\\\\\\\".\\\"}\"}"

**Comment by zaneb** [comment]
Fixed in the installer.
