### ISSUE TITLE
Change the user data secret reference in BareMetalHost

### ISSUE THREAD

**Issue by maelk** [metal3-io/baremetal-operator#363]
Currently, the user data secret is referenced by its name, as a string in the BMH spec. This implies that the secret is in the same namespace as the BMH.
With the recent changes in CAPI v1alpha3, the user data comes as a secret from CABPK. I would suggest to move to a secret reference for the user data secret instead of just a string with the name.

**Comment by zaneb** [comment]
Agreed, we shouldn't be relying on anything coming in from outside without an explicit namespace.

**Comment by maelk** [comment]
Considering that all objects must be in the same namespace (for owner references) this actually does not apply.

/close
