### ISSUE TITLE
BMO deployment fails due to updated api-version

### ISSUE THREAD

**Issue by kashifest** [metal3-io/baremetal-operator#372]
PR#371 to update the CRD version seems to break the bmo deployment. The following error is shown: 

``` 
error validating data: [ValidationError(CustomResourceDefinition.spec): 
unknown field "additionalPrinterColumns" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): 
unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): 
unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): 
unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false
Makefile:292: recipe for target 'deploy' failed
```   

Changing the api-version back to v1beta1 seems to work. This needs further investigation.

**Comment by maelk** [comment]
I propose a temporary revert : https://github.com/metal3-io/baremetal-operator/pull/373 The change will need to be done and tested more thoroughly to make sure the BMH CRD is not broken.

**Comment by maelk** [comment]
The core issue is that the specs have changed, there is now a version field that takes a list . Here are the definitions : https://github.com/kubernetes/apiextensions-apiserver/blob/release-1.17/pkg/apis/apiextensions/v1/types.go and the spec is now taking a list here https://github.com/kubernetes/apiextensions-apiserver/blob/release-1.17/pkg/apis/apiextensions/v1/types.go#L59 and the items definition is here : https://github.com/kubernetes/apiextensions-apiserver/blob/release-1.17/pkg/apis/apiextensions/v1/types.go#L168

**Comment by maelk** [comment]
commit reverted. We should close this issue @kashifest
