### ISSUE TITLE
operator-sdk up local launch fails

### ISSUE THREAD

**Issue by tssavita** [metal3-io/baremetal-operator#379]
I'm trying to setup metal3 baremetal operator in a Kuberetes baremetal cluster.  I followed the steps here mentioned here: https://github.com/metal3-io/baremetal-operator/blob/master/docs/dev-setup.md. When trying to launch the operator, 

```operator-sdk up local --namespace=metal3```

I get the following error. Not sure if I'm missing some important piece of info. 

Intuitively it seems that removing the -mod=vendor flag might work. 1. Not sure if this is the right approach. 2. If it is, I couldn't find the right spot where this flag is being set. Any hints would be much appreciated. 

```
DEBU[0000] Debug logging is set
INFO[0000] Running the operator locally.
INFO[0000] Using namespace metal3.
DEBU[0000] Running []string{"go", "build", "-o", "build/_output/bin/baremetal-operator-local", "-mod=vendor", "github.com/metal3-io/baremetal-operator/cmd/manager"}
build flag -mod=vendor only valid when using modules
Error: failed to build operator to run locally: (failed to exec []string{"go", "build", "-o", "build/_output/bin/baremetal-operator-local", "-mod=vendor", "github.com/metal3-io/baremetal-operator/cmd/manager"}: exit status 1)
Usage:
  operator-sdk up local [flags]

Flags:
      --enable-delve            Start the operator using the delve debugger
      --go-ldflags string       Set Go linker options
  -h, --help                    help for local
      --kubeconfig string       The file path to kubernetes configuration file; defaults to location specified by $KUBECONFIG with a fallback to $HOME/.kube/config if not set
      --namespace string        The namespace where the operator watches for changes.
      --operator-flags string   The flags that the operator needs. Example: "--flag1 value1 --flag2=value2"

Global Flags:
      --verbose   Enable verbose logging

**Comment by russellb** [comment]
Can you try `make run`?  That seems to work for me, while the command in the doc fails like you see.

**Comment by tssavita** [comment]
So it turns out, the operator-sdk v13.0.0(which was the version I was using), adds the "-mod=vendor" flag to the go build command. v0.8.0 doesn't attach the flag and then command succeeds. 
```make run``` worked as well! Thanks!

**Comment by tssavita** [comment]
Ok, I just found that operator-sdk up local only allows to run the binary on the host and not on the cluster.. So getting back to how to deploy baremetal-operator on cluster, I have a couple of questions(Sorry it it's too naive.. ) 

1. If you wanted to deploy the baremetal-operator on the cluster, do you run kubectl apply -f to all the yaml files in deploy/? 
- *If  yes*, in deploy/ there are two operator yaml files, with the same deployment name: metal3-baremetal-operator. (One has ironic-proxy and ironic-inspector-proxy, the other has dnsmasq, mariadb, and ironic HTTP endpoint.) When trying to deploy, of course there is conflict. Am I missing something on how to deploy the baremetal-operator?
- *If no*, is there a documentation link on how to deploy baremetal-operator on baremetal cluster? (I couldn't find one.. :| )

**Comment by dhellmann** [comment]
> Ok, I just found that operator-sdk up local only allows to run the binary on the host and not on the cluster.. So getting back to how to deploy baremetal-operator on cluster, I have a couple of questions(Sorry it it's too naive.. )
> 
> 1. If you wanted to deploy the baremetal-operator on the cluster, do you run kubectl apply -f to all the yaml files in deploy/?
> 
> * _If  yes_, in deploy/ there are two operator yaml files, with the same deployment name: metal3-baremetal-operator. (One has ironic-proxy and ironic-inspector-proxy, the other has dnsmasq, mariadb, and ironic HTTP endpoint.) When trying to deploy, of course there is conflict. Am I missing something on how to deploy the baremetal-operator?
> * _If no_, is there a documentation link on how to deploy baremetal-operator on baremetal cluster? (I couldn't find one.. :| )

Sorry about that. :-(

We had some documentation in this repo that moved to https://metal3.io/try-it.html and it looks like we haven't done a good job of leaving breadcrumbs behind so users who start from the docs here can find the docs there.

The scripts in the https://github.com/metal3-io/metal3-dev-env repository will help set up a system from scratch, including building a mini cluster to host metal3. 

If you want to deploy by hand into an existing cluster, the deploy/operator_ironic.yaml file should set up the full application with all of its parts running in the cluster.

**Comment by tssavita** [comment]
Thanks a lot for explaining! I deployed the baremetal-operator on Kubernetes baremetal cluster. However, I now run across a new problem: The baremetalhost is stuck in "Inspecting" State. I've created a new issue here: https://github.com/metal3-io/baremetal-operator/issues/393
