### ISSUE TITLE
After Inspection Provisioning fails when talking back to ironic-httpd on GET /v1/lookup?address

### ISSUE THREAD

**Issue by Lukasz-SendGrid** [metal3-io/baremetal-operator#389]
When provisioning a new baremetal host, after the inspection phase passes, and the host moves into the provisioning phase it fails when talking back to the ironic-httpd service when it attempts to look itself up.
172.16.18.45 - - [14/Jan/2020:18:45:30 +0000] "GET /v1/lookup?addresses=18%3A66%3Ada%3A94%3A62%3A48%2C18%3A66%3Ada%3A94%3A62%3A4a%2C18%3A66%3Ada%3A94%3A62%3A4c%2C18%3A66%3Ada%3A94%3A62%3A4e HTTP/1.1" 404 207 "-" "python-requests/2.21.0"

Does this make sense seeing as the inspection phase passed successfully, and on next boot the bmh is able to successfully talk back to ironic to look up the kernel set for it's mac.
Does this seem correct for a baremetalhost that has only one valid interface with an actual ip attached to it as its going through the provisioning process after successfully passing inspection?

From the console:
![image](https://user-images.githubusercontent.com/49925246/72386245-4d8dce00-36de-11ea-9663-1d95f45a8d2a.png)

**Comment by zaneb** [comment]
It's surprising to me also that the agent would fail to find the configuration data after successfully inspecting. Is it possible that the Ironic container was restarted in between?
