### ISSUE TITLE
Chainloading using undionly.kpxe: Initialising of network devices fails

### ISSUE THREAD

**Issue by tssavita** [metal3-io/baremetal-operator#403]
It may not be as much a metal3 issue, as much as it is, an ipxe issue, but I was wondering if anybody else has encountered the same issue. When undionly.kpxe is used for boot, I get the following error. 

<img width="362" alt="undionly" src="https://user-images.githubusercontent.com/2744118/72983319-4bfc8e00-3de1-11ea-8166-a1112a7cab99.PNG">

I've also tried using the undionly.kpxe built from the most recent of ipxe source code(without doing a checkout of the commit mentioned in the Dockerfile of ironic-image), dualboot.ipxe and directly referencing the pxelinux.0 file. All yield the same result - the network devices are initialized which I understand is how it should be, during the boot of any host. But as a result IP connection to the HTTP server is lost, which serves the initramdisk and kernel files. 

However, when I load the ipxe.iso(downloaded from https://ipxe.org/download) directly into the server(not through net boot), the initiliasing goes through, and the operating system is installed. 

P.S.: If you feel it's out of topic, please indicate so, and I'll close the issue..

**Comment by stbenjam** [comment]
I think this is more of an iPXE problem that's out of scope for what we can fix - have you tried asking on iPXE support channels?

If you idnetify something we should fix (like updating iPXE shipped in [ironic-image](http://github.com/metal3-io/ironic-image/)), please open an issue there and we can look at it.

Thanks!


/close
