### ISSUE TITLE
Define release guidelines for baremetal-operator and start publishing releases 

### ISSUE THREAD

**Issue by Arvinderpal** [metal3-io/baremetal-operator#404]
We should adopt a releasing approach similar to that of CAPI and follow the well-known semantic versioning guidelines (see references below).

Besides this being a good practice, integration with the redesigned clusterctl will require that projects follow the above mentioned releasing strategy. A similar issue was created for capbm: https://github.com/metal3-io/cluster-api-provider-baremetal/issues/224

PR Tracking:
- [ ] Makefile updates for docker build and push, and release manifests generation: https://github.com/metal3-io/baremetal-operator/pull/405
- [ ] ...

**Comment by dhellmann** [comment]
We generally put project-wide docs like that in the metal3-docs repository. Maybe we could do that for these release policies and instructions?

**Comment by stbenjam** [comment]
Could you move this issue to metal3-docs? Any metal3-wide docs should go there, including defining our release processes.

/kind documentation

/close

**Comment by Arvinderpal** [comment]
> Could you move this issue to metal3-docs? Any metal3-wide docs should go there, including defining our release processes.
> 
> /kind documentation
> 
> /close

https://github.com/metal3-io/metal3-docs/issues/71
