### ISSUE TITLE
Facing issue while testing new code in Baremetal-operator.

### ISSUE THREAD

**Issue by sharajat** [metal3-io/baremetal-operator#406]
There are some issues that we are facing while testing changes in baremetalhost crd. As per the requirement, we are adding currentBootMode parameter in the baremetalhost crd but while testing the changes baremetalhost provisioning is getting stuck in inspecting state. 
We made changes in baremetal-operator cloned in GOPATH while metal3-dev-env setup and using `make` command again to test our changes but baremetal-operator is using the existing master code instead of our changes.
On debugging Baremetal operator logs we found out that baremetal-operator is running existing code instead of the local changes.
 Is there some other method to build or test the local code ?

Following are the logs from Baremetal operator-:

`{"level":"info","ts":1579770966.9839694,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"metal3","Request.Name":"node-0"}
{"level":"info","ts":1579770966.9852643,"logger":"baremetalhost","msg":"inspecting hardware","Request.Namespace":"metal3","Request.Name":"node-0","provisioningState":"inspecting"}
{"level":"info","ts":1579770966.985394,"logger":"baremetalhost_ironic","msg":"inspecting hardware","host":"node-0","status":"OK"}
{"level":"info","ts":1579770967.027505,"logger":"baremetalhost_ironic","msg":"found existing node by ID","host":"node-0"}
{"level":"info","ts":1579770967.0457554,"logger":"baremetalhost_ironic","msg":"getting hardware details from inspection","host":"node-0"}
{"level":"info","ts":1579770967.0579052,"logger":"baremetalhost_ironic","msg":"received introspection data","host":"node-0"}
{"level":"info","ts":1579770967.0585203,"logger":"baremetalhost","msg":"changing provisioning state","Request.Namespace":"metal3","Request.Name":"node-0","provisioningState":"inspecting","old":"inspecting","new":"match profile"}
{"level":"info","ts":1579770967.0587797,"logger":"baremetalhost","msg":"saving host status","Request.Namespace":"metal3","Request.Name":"node-0","provisioningState":"inspecting","operational status":"OK","provisioning state":"match profile"}
{"level":"error","ts":1579770967.1646707,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"metal3-baremetalhost-controller","request":"metal3/node-0","error":"failed to save host status after \"inspecting\": BareMetalHost.metal3.io \"node-0\" is invalid: status.hardware.currentBootMode: Required value","errorVerbose":"BareMetalHost.metal3.io \"node-0\" is invalid: status.hardware.currentBootMode: Required value`

**Comment by aneeshkp** [comment]
Quick hack: 
Set the variable in config_{user}.sh  to run operator locally 
`export BMO_RUN_LOCAL=true`
and then change the branch name in this file  `03_launch_mgmt_cluster.sh`
` BMOBRANCH="${BMOBRANCH:-your-branch-name}" `

**Comment by stbenjam** [comment]
Is this resolved for you?

**Comment by sharajat** [comment]
Yes the issue is resolved, thanks @aneeshkp.
