### ISSUE TITLE
No DEPLOY_KERNEL_URL variable set deploying with kustomize

### ISSUE THREAD

**Issue by alexlovelltroy** [metal3-io/baremetal-operator#409]
After using Kustomize to deploy kubectl apply -k deploy/ the baremetal-operator container goes into CLBO with the error Cannot start: No DEPLOY_KERNEL_URL variable set I adjusted the command in the pod to dump the env before trying to start /baremetal-operator and confirmed that the environment variable is indeed being set correctly in the container.
command: ['sh', '-c', 'echo The app is running! && env && /baremetal-operator']

Looking for suggestions while in parallel reviewing the baremetal-operator code to see why it can't see the environment variable.

Kubectl version information for reference:

# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211

**Comment by stbenjam** [comment]
> the pod to dump the env before trying to start /baremetal-operator and confirmed that the environment variable is indeed being set correctly in the container.

`kubectl describe` shows DEPLOY_KERNEL_URL set to a value? I don't see a code path where'd you'd get that error if it was setup

https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/ironic.go#L48-L52

**Comment by alexlovelltroy** [comment]
According to `kubectl describe` the environment comes from a file in Kustomize
```
Environment Variables from:
      ironic-bmo-configmap-f8bck4hgh5  ConfigMap  Optional: false
```
When I dump the environment before starting the /baremetal-operator binary, I see the environment variables where they should be.

Full describe below

```
baremetal-operator:
    Container ID:  containerd://5a8b0e5935ace037df28328de2dbca7d74eab9a741ee3e22eaad8bf25ee96e06
    Image:         bis.local:5000/metal3-io/baremetal-operator
    Image ID:      bis.local:5000/metal3-io/baremetal-operator@sha256:0013f3c0048c2ce9dd2c58428aca4ce103b26beb44bce5d76407603ac9393278
    Port:          60000/TCP
    Host Port:     60000/TCP
    Command:
      sh
      -c
      echo The app is running! && env && /baremetal-operator
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 31 Jan 2020 13:39:07 -0600
      Finished:     Fri, 31 Jan 2020 13:39:07 -0600
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 31 Jan 2020 13:33:55 -0600
      Finished:     Fri, 31 Jan 2020 13:33:55 -0600
    Ready:          False
    Restart Count:  46
    Environment Variables from:
      ironic-bmo-configmap-f8bck4hgh5  ConfigMap  Optional: false
    Environment:
      WATCH_NAMESPACE:  metal3 (v1:metadata.namespace)
      POD_NAME:         metal3-baremetal-operator-7b977f97dc-4ghdd (v1:metadata.name)
      OPERATOR_NAME:    baremetal-operator
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from metal3-baremetal-operator-token-vkfks (ro)
```

**Comment by stbenjam** [comment]
The deploy/ directory has been refactored since this was opened, have you tried recently? The missing variable is set in the default configmpa and should be present.

**Comment by stbenjam** [comment]
Going to close this, please re-open if you're still encountering issues. Thanks!
