### ISSUE TITLE
Integrate Ironic discovery workflow

### ISSUE THREAD

**Issue by russellb** [metal3-io/baremetal-operator#41]
Ironic is capable of doing discovery of new hosts.  This should be an optional capability of the baremetal-operator.  When we discover a new host, it should result in automatically creating a corresponding BareMetalHost object.

**Comment by dhellmann** [comment]
I have an early design for this in https://docs.google.com/document/d/1hlMSdim53CQtqlYOnx1ptq3qKHKhP9LhDrRxzCutGoM/edit and will move that to metal3-docs after we have had time to collaborate more there.

**Comment by dhellmann** [comment]
> I have an early design for this in https://docs.google.com/document/d/1hlMSdim53CQtqlYOnx1ptq3qKHKhP9LhDrRxzCutGoM/edit and will move that to metal3-docs after we have had time to collaborate more there.

That design is now available in https://github.com/metal3-io/metal3-docs/pull/98
