### ISSUE TITLE
Support additional certificate verification mechanisms

### ISSUE THREAD

**Issue by stbenjam** [metal3-io/baremetal-operator#420]
In #396, we introduced the ability to control redfish_verify_ca, but obviously turning off verification is less than ideal for dev/labs -- and not really acceptable at all in a production environment.

Ironic does have some ability to point to a file containing certs to trust: https://docs.openstack.org/ironic/latest/admin/drivers/redfish.html

We should expose additional options if we're able to explicitly verify valid certificates. It's not clear to me though what the  Ironic verification does: we're largely using IP's for the BMC's, so does it still expect CN/SAN's to match? etc.

**Comment by stbenjam** [comment]
/cc @juliakreger 
/cc @dtantsur 

What do you think of this? Especially since this seems to want to point to a file, that's probably a bit challenging for baremetal-operator to do, right? Can you specify specific certs instead of a path to a file? Could the path be a URL?

**Comment by dhellmann** [comment]
How does OpenShift as a whole manage certs? Can we tap into that somehow and configure the ironic pod?

**Comment by juliakreger** [comment]
@dhellmann I've been thinking the same exact thing for the last few hours. I don't think additional logic should really be added to try and guess and say something is valid. I'd personally rather see operators take the extra step.

**Comment by kirankt** [comment]
Since we're already consuming a secret per BMH, would it make sense to add additional cert data to the secret. We can mount the cert data somewhere in the operator and then use that location to populate the verify CA field. Thoughs?

**Comment by dhellmann** [comment]
> Since we're already consuming a secret per BMH, would it make sense to add additional cert data to the secret. We can mount the cert data somewhere in the operator and then use that location to populate the verify CA field. Thoughs?

I think passing data via mount like that would mean restarting the operator, wouldn't it? And I don't think we want to do that every time a host is created or the secret is modified.

I think we want a way to do this that is either explicitly configuring the CA to use or taps in to the existing CA management for the cluster.

**Comment by stbenjam** [comment]
Some more info about how OpenStack solved this for OpenShift: https://github.com/openshift/enhancements/blob/master/enhancements/security/openstack-self-signed-certificates.md

OpenShift has an AdditionalTrustBundle, which might be appropriate for us to use if the BMC's are signed by something like a corporate CA. There's some argument against that (not sure I buy it) that only the containers verifying the BMC certs should trust that CA instead of being a cluster-wide config.

**Comment by dhellmann** [comment]
https://docs.openshift.com/container-platform/4.3/networking/configuring-a-custom-pki.html includes some details about how to add CAs or trusted certs and have them added to the container where the operator will consume them in the normal way. Doing that will require changes to the Deployment created by the machine-api-operator. Ideally it wouldn't be necessary to add a separate cert per host.
