### ISSUE TITLE
Adding programmatic FQDN control to BMH

### ISSUE THREAD

**Issue by andy-v-h** [metal3-io/baremetal-operator#421]
I suppose this is probablly a feature request, but I am wondering if this would be a feature other people would value for BareMetalHosts (and maybe I am using BMO incorrectly). Setting the hostname on BMH's in seemingly non-trivial / kind of hacky. Currently, we are setting it like this on workers and control planes.
  ``` yaml
    preKubeadmCommands:
      - echo '{{ ds.meta_data.name }}' > /etc/hostname
      - hostname "{{ ds.meta_data.hostname }}"
``` 
Looking at PR #348, the network_data.json has been usual. But it would it be useful to also be able to pass the fqdn: section of user_data  to anyone else? Would making an Issue on BMO be a better place to get this groomed and start the PR process?

**Comment by dhellmann** [comment]
I'm not sure how smart we want to make the operator about values like this. We have the general user and network data fields. Maybe the thing to do is have an operator that builds the values that are passed to the hosts as user and network data? That way we don't have multiple ways to set the same value for hostname on a host in the API, and we don't end up growing fields on the host CRD for all of the things that can be set via user and network data.

**Comment by andy-v-h** [comment]
I see what you're saying and I agree. It would be nice to avoid partially or completely wrapping the user_data API into the BMH CRDs. The difficulty I can see there comes from trying to merge the user_data from the BMH and a BMM or Machine or KubeAdmConfig CRD with like the `runCommand` section of the cloud-init user_data. And since the hostname would be 1-1 mapped to a BMH it's something I would want to sort of design to be defined at the BMH and carried forward as it gets picked up by a consumer.

**Comment by maelk** [comment]
We are planning a feature to pass the metadata as we are now passing the network_data . This way, you would just need to set a variable in the metadata in your BMH and refer to it in the user_data content. Would this work for you ?

**Comment by andy-v-h** [comment]
From what I could find, network_data.json doesn't have a hostname field. We are actually currently running that branch of the operator and love it.

**Comment by dhellmann** [comment]
See https://github.com/metal3-io/metal3-docs/pull/79

**Comment by maelk** [comment]
passing local-hostname (or local_hostname, I'm not sure) as part of the metadata does the trick. it will set the hostname automatically. The branch adding this feature in BMO is not merged yet.

**Comment by maelk** [comment]
We can probably close this now ? as it is solved by the metadata feature. Feel free to reopen if it is not the case.
/close
