### ISSUE TITLE
Mismatch in userdata secret between CAPI and BMO

### ISSUE THREAD

**Issue by maelk** [metal3-io/baremetal-operator#423]
In v1alpha3, the bootstrap provider creates a secret containing the userdata for the machine, but uses a key "value" in the secret. BMO expects the key "userData" for its userdata secret. Hence CAPBM now duplicates the CAPI secret with the correct key. Should we enhance BMO to also accept the "value" key along / instead of "userdata" . The decision here could impact https://github.com/metal3-io/baremetal-operator/pull/348 in order to keep things aligned.

**Comment by maelk** [comment]
Here is a v1alpha3 CAPI secret : 
`apiVersion: v1
data:
  value: IyMgdGV...
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane-0
  namespace: default
  ownerReferences:
  - apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
    controller: true
    kind: KubeadmConfig
    name: test1-controlplane-0
type: Opaque`

and the expected BMO userdata secret : 

`apiVersion: v1
data:
  userData: IyMgdGV
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: test1
  name: test1-controlplane-0-user-data
  namespace: default
type: Opaque`

**Comment by zaneb** [comment]
I think it makes sense (and should be simple) to support either.
I do think cluster API is making a mistake, because you can't look at the secret and know wtf it's supposed to be for, but nothing good can come from having to duplicate it.

**Comment by maelk** [comment]
Fixed by https://github.com/metal3-io/baremetal-operator/pull/436
