### ISSUE TITLE
BaremetalHost critical states stored in status

### ISSUE THREAD

**Issue by maelk** [metal3-io/baremetal-operator#431]
When using clusterctl to do the pivoting to the target cluster, only the spec part of the objects are moved. However, some critical states for ironic are kept in the Status part of the BMH. If we do not move the status, the introspection is triggered again for all BMHs of a deployed cluster. The status content should be easily recovered by running the reconciliation, even in a cluster with a blank database for ironic. We should probably move the critical states to the spec part of the BMH or maybe to a specific CRD that would contain all information needed during the pivoting. Any opinions ? 

This would definitely be a breaking change ( for v1alpha2 BMO maybe :D)

**Comment by maelk** [comment]
For now we are considering building a side utility that would take care of specifically moving the BMH to patch them with the current status on the source cluster.

**Comment by dhellmann** [comment]
We had a similar issue creating the BMH resources for control plane nodes in OpenShift. That resulted in creating the "externally provisioned" flag, which prevents reprovisioning. There is worked planned to use a DaemonSet for continuous introspection, which would re-populate the rest of the status fields.

Which fields would you want to move from status to spec? I think I considered that approach and the logic for using the right update calls in the BMO grew too complicated but that was during the early development so it's worth revisiting the approach.

**Comment by zaneb** [comment]
Wouldn't we need pretty much all of the fields in the Status? IIUC the Spec contains things that the user should set and the Status contains things that are the operator's own internal accounting. When you're only managing other k8s resources the internal accounting can be recreated, but when you're managing something external then you will always need that data. Making the internal accounting writable by the user is always an option, but not an especially palatable one. Have we considered teaching clusterctl how to move everything?

Speaking of v1alpha2, it has occurred to me that in future we should consider splitting up the current CRD into multiple ones. For example, creating the Host object and getting Ironic to talk to the BMC is something done by the system administrator or maybe an installer, whereas provisioning a Host is something done by the Machine actuator. That's two completely different actors - those things should be represented by separate CRDs with different RBAC rules. I'm not sure that helps with this though.

**Comment by maelk** [comment]
yes, we would need pretty much all the fields. I am in touch with the guy who implemented clusterctl, to see if we could move the status too. But if we would not do that, we need to move the critical state info to a spec part. I agree with the fact that it would be nice to not mix user input and controller input. For this reason, we could create a new object, in the optic of the split that you are talking about. We could have a CRD for admin input which gives the BMC address, credentials etc. ; a CRD for "user" input, such as image and userdata; and a CRD for controller input, containing the critical states. All three CRs would be linked to each other through references, like it is done in CAPI. How does that sound @zaneb and @dhellmann ?

**Comment by maelk** [comment]
Here is a very valid point about why not to do that in clusterctl : https://github.com/kubernetes-sigs/cluster-api/issues/2370#issuecomment-588219695

**Comment by dhellmann** [comment]
Let's make a list of the fields we think we can't reproduce if we lose them, because I don't think it's everything we're currently storing in the status block.

**Comment by zaneb** [comment]
Looking closer, I guess it's only the ProvisionStatus struct that contains stuff we can't recreate (in theory). Conceptually, it wouldn't be terrible to split that into a separate CRD that is only writeable by the operator but which can be copied over to a separate cluster. On a practical level, we would have to figure out if there are any places we expect to be able to atomically update that status and something else.

**Comment by zaneb** [comment]
BTW I don't think we should link through references; I think we should require each of the objects of different types that correspond to the same host to have the same name.

**Comment by dhellmann** [comment]
Since it requires separate API calls, it isn't possible to atomically update the status along with non-status values on a CR. Keeping the fields together in the same CR does avoid confusion that might be caused by having multiple references to the same host, though.

Could we use annotations to pass data from the installer to the host controller to be stored in the status fields?

**Comment by maelk** [comment]
The idea of using annotation to save and restore the status is something we did not investigate. We'll look into it. It probably means that whenever BMO is updating the status it needs to update the annotation too, and whenver reconciling, check if the annotation and the status fields are matching. But that is probably much simpler as a first hack.

**Comment by dhellmann** [comment]
> The idea of using annotation to save and restore the status is something we did not investigate. We'll look into it. It probably means that whenever BMO is updating the status it needs to update the annotation too, and whenver reconciling, check if the annotation and the status fields are matching. But that is probably much simpler as a first hack.

I would expect it to be a 1 time operation, moving data from the annotations to the status fields if the status is empty and the annotations are present.

**Comment by dhellmann** [comment]
Does #470 resolve this issue?

**Comment by maelk** [comment]
Yes, the workaround is in place.
/close
