### ISSUE TITLE
Unit test broken

### ISSUE THREAD

**Issue by mikkosest** [metal3-io/baremetal-operator#433]
~/go/src/github.com/metal3-io/baremetal-operator$ go test  ./cmd/... -v
go: github.com/operator-framework/operator-sdk@v0.15.2 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0

I made a workaroud with go.mod. Would it be ok to fix this by starting to use go.mod based packet dependency handling?

**Comment by dhellmann** [comment]
PR #367 moves this repo to use go modules. I'm not sure if we have anyone working on updating to a newer operator-sdk.

**Comment by honza** [comment]
#367 also upgrades operator-sdk

**Comment by stbenjam** [comment]
Let's check this after #367 is merged

**Comment by stbenjam** [comment]
We've moved to go modules in https://github.com/metal3-io/baremetal-operator/pull/444, could you try this again?

**Comment by mikkosest** [comment]
Works now, thanks for updates!
