### ISSUE TITLE
Extend BareMetalHostSpec with metadata secret reference

### ISSUE THREAD

**Issue by dukov** [metal3-io/baremetal-operator#447]
Currently cloud-init metadata structure and values are hardcoded in ironic provisioner (see [here](https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/ironic.go#L1000)).
BareMetal operator should enable user to supply reference to custom metadata stored in a Secret in the same manner it's implemented for user-data and network data

**Comment by dukov** [comment]
#448

**Comment by dhellmann** [comment]
#448 has merged. Does that complete the work for this issue, or should we keep it open?

**Comment by zaneb** [comment]
Looks complete to me. Feel free to reopen if that's not the case.
/close
