### ISSUE TITLE
Hardware inspection with Redfish

### ISSUE THREAD

**Issue by mikkosest** [metal3-io/baremetal-operator#450]
Hardware inspection should be possible by using Redfish when available. Legacy solution in BMO ironic pkg uses gophercloud libraries with IPA inspector url. Parsing is made to the REST response body, similar parsing should be supported for Redfish HW inspection queries. If OK, what introspection parameters we should have as as naming etc. is different. 
What do you think @dhellmann @zaneb @russellb?

**Comment by dhellmann** [comment]
I'm interested in learning how much effort it would take. From what I understand, the Redfish standard is quite flexible, and so to scan the hardware of different hosts might require different logic based on the BMC type or other factors. Have you started experimenting at all?

**Comment by etingof** [comment]
> I'm interested in learning how much effort it would take. From what I understand, the Redfish standard is quite flexible, and so to scan the hardware of different hosts might require different logic based on the BMC type or other factors. Have you started experimenting at all?

We actually already have Redfish inspection [in place](https://github.com/openstack/ironic/blob/master/ironic/drivers/modules/redfish/inspect.py).

So it should work, but the outcome greatly depends on what BMC decides to expose.

**Comment by etingof** [comment]
> AIUI inspection via the BMC cannot provide the full range of data that is available from IPA (and is not consistent between vendors), so we don't regard the IPA method as 'legacy' and we're not planning to implement another method. @dtantsur is the expert though.

This is correct. Unlike OOB inspection, IPA can gather many internal details including actual machine performance.

On the other hand, OOB inspection can be very fast (no boot required) and can run continuously during machine normal operation.

**Comment by mikkosest** [comment]
> > AIUI inspection via the BMC cannot provide the full range of data that is available from IPA (and is not consistent between vendors), so we don't regard the IPA method as 'legacy' and we're not planning to implement another method. @dtantsur is the expert though.
> 
> This is correct. Unlike OOB inspection, IPA can gather many internal details including actual machine performance.
> 
> On the other hand, OOB inspection can be very fast (no boot required) and can run continuously during machine normal operation.

We see that booting delay mentioned as a problem in big systems, so it would be great to fetch HW details without booting. 

Would it be possible to get this inspection as a part of BMO? How, through gophercloudlibs? 

Or would it be OK to use Redfish REST directly from BMO, Redfish standard at least supports
-BIOS
-SystemVendor
-NIC
-Storage
-CPU
info we need, but as you said, it probably varies between bmc:s

**Comment by dhellmann** [comment]
Gophercloud is for talking to Ironic, so if we're not using Ironic I don't think we need to use Gophercloud.

How would the baremetal-operator decide whether to use the Ironic-based inspection or to use this new thing?

**Comment by etingof** [comment]
> Or would it be OK to use Redfish REST directly from BMO, Redfish standard at least supports

This might be challenging considering how weird BMCs can be...

But what's the reason for not doing it via ironic?

**Comment by mikkosest** [comment]
> > Or would it be OK to use Redfish REST directly from BMO, Redfish standard at least supports
> 
> This might be challenging considering how weird BMCs can be...
> 
> But what's the reason for not doing it via ironic?

You mean still using IPA?, or how to choose inspector you showed in the link in BMO?

**Comment by mikkosest** [comment]
> Gophercloud is for talking to Ironic, so if we're not using Ironic I don't think we need to use Gophercloud.
> 
> How would the baremetal-operator decide whether to use the Ironic-based inspection or to use this new thing?

Would it just check BMC url,if that has redfish:// then choose that one?

**Comment by dhellmann** [comment]
> > Gophercloud is for talking to Ironic, so if we're not using Ironic I don't think we need to use Gophercloud.
> > How would the baremetal-operator decide whether to use the Ironic-based inspection or to use this new thing?
> 
> Would it just check BMC url,if that has redfish:// then choose that one?

Sure, that's a possibility. That would mean we need to separate the inspection process from the Provisioner interface now into a new interface of some sort, and something would need to know how to instantiate the right type based on the URL. The state machine in the operator may also need to change.

**Comment by dhellmann** [comment]
> AIUI inspection via the BMC cannot provide the full range of data that is available from IPA (and is not consistent between vendors), so we don't regard the IPA method as 'legacy' and we're not planning to implement another method. @dtantsur is the expert though.

It would be good to have the details of what isn't available out of band written down somewhere. This isn't the first time this question has come up.

**Comment by etingof** [comment]
> You mean still using IPA?, or how to choose inspector you showed in the link in BMO?

Speaking of OOB inspection, I thought of using ironic (not IPA). With ironic, its `redfish` driver can do the inspection w/o relying on IPA if you configure ironic node to use `redfish` inspect interface.

**Comment by mikkosest** [comment]
> > You mean still using IPA?, or how to choose inspector you showed in the link in BMO?
> 
> Speaking of OOB inspection, I thought of using ironic (not IPA). With ironic, its `redfish` driver can do the inspection w/o relying on IPA if you configure ironic node to use `redfish` inspect interface.

How could I test and activate above redfish inspection, is there some API doc or? If I'm using metal3-dev-dev there I have ironic container and ironic inspection container, is there API support for redfish based inspection in  ironic container+?

**Comment by mikkosest** [comment]
We had a discussion in metal3 community meeting today about this issue with @elfosardo and currently the only way to read Redfish inspection data from ironic is to use generic Ironic interface /v1/nodes/... it is a subset of redfish data that Ironic receives when configured to do inspection. We all agree that redfish inspection is not as detailed as IPA based introspection. Question is that would it be acceptable to allow BMO user to set Redfish inspection active and create limited inspection status to BMH instead of current IPA based inTROspection status. This would mean that the data would not be as detailed about disks and nics in Ironic /v/nodes... and BMH status field would look different. For example Volume names and WWN ids can be fetched. No EthernetInterface, CPU details.

**Comment by dhellmann** [comment]
Would the alternative inspection be enabled per host, or as a global configuration setting? Do we want a way to bypass inspection entirely, too?

Maybe someone could start writing up a design doc in the metal3-docs repo?

**Comment by maelk** [comment]
/remove-lifecycle stale
There's not much activity on-going on this right now but we would like to keep it open to tackle in the future
