### ISSUE TITLE
Disk status is not showing in Hardware introspection data in CR 

### ISSUE THREAD

**Issue by snehal1797** [metal3-io/baremetal-operator#460]
After performing introspection from baremetal operator,all the  required introspection data is populated in the Baremetal host CR. 
Here Is the disk data for reference:
--------------------------------
 - hctl: "0:2:7:0"
      model: PERC H740P Adp
      name: /dev/sdh
      rotational: true
      serialNumber: 64cd98f0b3b97d0026071b76f3a17631
      sizeBytes: 599550590976
      vendor: DELL
      wwn: "0x64cd98f0b3b97d00"
      wwnVendorExtension: "0x26071b76f3a17631"
      wwnWithExtension: 0x64cd98f0b3b97d0026071b76f3a17631
    - hctl: "0:2:8:0"
      model: PERC H740P Adp
      name: /dev/sdi
      rotational: true
      serialNumber: 64cd98f0b3b97d0026071b9d2ccc4325
      sizeBytes: 599550590976
      vendor: DELL
      wwn: "0x64cd98f0b3b97d00"
      wwnVendorExtension: "0x26071b9d2ccc4325"
      wwnWithExtension: 0x64cd98f0b3b97d0026071b9d2ccc4325

----
As you can see the above data , there is no status field found in the disk .As a user if I want to find whether disk is online or in error state,what are the operations I need to perform?
Is there any plan to add support for getting status of the disk??

**Comment by digambar15** [comment]
This is extremely critical for Hardware-classification-controller. We are working closely with Airship community, as part of validation, we need to check whether disks are active or in error state, if one the disks in the node are in error state, we will label the host accordingly which will help user identify issues, and resolve those issues before provisioning.

I have gone through the ironic introspection data and saw there are some SMART data params related to disk which may help us in this case. 
Another option is, Ironic-prometheus-exporter or k8s node-exporter may provide us some info, but before seeing/finding another option, I would like to understand, anyone from community are working on the same solution ?

**Comment by pramchan** [comment]
Do you need disk error at all? Just existence of number of disks asked should suffice.

**Comment by sumitjadhav1** [comment]
@digambar15 Tested node introspection with various combinations of failed disk along with other physical and/or virtual disks in place on BM node. The introspection data seen doesn't show failed disk, looks like BMO handles the error states on its own and shows all valid data in yaml.

Request you to share your inputs further.

**Comment by dhellmann** [comment]
I don't think we want to store status in the host resource. Status feels more like something that should be reported via live data sent to prometheus, which is better equipped to handle regular updates.

**Comment by digambar15** [comment]
Agree. Let's discuss it in our meeting.
Currently I am thinking to rely on whatever introspection data produced by Ironic and go with it.

**Comment by stbenjam** [comment]
We discussed this during the community meeting on the 15th, Prometheus is probably the right place for this kind of reporting.

Have a look at https://github.com/metal3-io/ironic-prometheus-exporter.


/close
