### ISSUE TITLE
Firmware related values are absent in Node Introspection Data (using redfish)

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/baremetal-operator#461]
After performing introspection from baremetal operator using redfish driver, all the required introspection data is populated in the Baremetal host CR. 

But Firmware related parameters have no values in it. Here is the snippet :

--------------------------------------
      model: Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
    firmware:
      bios:
        date: ""
        vendor: ""
        version: ""
    hostname: localhost.localdomain
--------------------------------------

These values will be further used in Hardware-Classification-Controller.

**Comment by zaneb** [comment]
Do you have the [`extra_hardware` processing hook](https://github.com/metal3-io/ironic-inspector-image/blob/master/inspector.conf#L22) enabled in the inspector config?
Can you paste the bmo log message showing the inspection data that the baremetal-operator is receiving from Ironic?

**Comment by sumitjadhav1** [comment]
> 
> 
> Do you have the [`extra_hardware` processing hook](https://github.com/metal3-io/ironic-inspector-image/blob/master/inspector.conf#L22) enabled in the inspector config?

Yes this is enabled. When issue was filed, we had old code under test where it was not enabled. We have checked the recent code (updated 2 days back) and observations are same.

metal3@metal3-PowerEdge-R640:~$ kubectl exec -it metal3-baremetal-operator-7d864c67d9-w8dzf --container ironic-inspector -n metal3 -- /bin/bash
[root@minikube /]# cat /etc/ironic-inspector/inspector.conf | grep -i extra_hardware
**processing_hooks** = $default_processing_hooks,**extra_hardware**,lldp_basic


> Can you paste the bmo log message showing the inspection data that the baremetal-operator is receiving from Ironic?

Here is the data for one node, please refer the attached logs for more details if required : [bmo-logs.txt](https://github.com/metal3-io/baremetal-operator/files/4688604/bmo-logs.txt)

`{"level":"info","ts":1590157176.3108344,"logger":"baremetalhost_ironic","msg":"received introspection data","host":"node-50","data":{"all_interfaces":{"eno1":{"client_id":null,"ip":null,"mac":"e4:43:4b:aa:25:b0","pxe":false},"eno2":{"client_id":null,"ip":null,"mac":"e4:43:4b:aa:25:b1","pxe":false},"eno3":{"client_id":null,"ip":"fe80::7128:86d1:8139:c6d","mac":"e4:43:4b:aa:25:b2","pxe":false},"eno4":{"client_id":null,"ip":null,"mac":"e4:43:4b:aa:25:b3","pxe":false},"ens2f0":{"client_id":null,"ip":"192.168.121.68","mac":"b8:59:9f:d5:83:2a","pxe":true},"ens2f1":{"client_id":null,"ip":"fe80::71c0:d238:7a61:9267","mac":"b8:59:9f:d5:83:2b","pxe":false},"ens7f0":{"client_id":null,"ip":"fe80::c05d:fc1f:d987:4499","mac":"b8:59:9f:d5:83:3a","pxe":false},"ens7f1":{"client_id":null,"ip":"fe80::20d0:288a:4ced:98f7","mac":"b8:59:9f:d5:83:3b","pxe":false}},"boot_interface":"b8:59:9f:d5:83:2a","configuration":{"collectors":["default"],"managers":[{"name":"MellanoxDeviceHardwareManager","version":"1"},{"name":"generic_hardware_manager","version":"1.1"}]},"cpu_arch":"x86_64","cpus":48,"error":null,"interfaces":{"ens2f0":{"client_id":null,"ip":"192.168.121.68","mac":"b8:59:9f:d5:83:2a","pxe":true}},"inventory":{"bmc_address":"192.168.110.50","bmc_v6address":"::/0","boot":{"current_boot_mode":"bios","pxe_interface":"b8:59:9f:d5:83:2a"},"cpu":{"architecture":"x86_64","count":48,"flags":["fpu","vme","de","pse","tsc","msr","pae","mce","cx8","apic","sep","mtrr","pge","mca","cmov","pat","pse36","clflush","dts","acpi","mmx","fxsr","sse","sse2","ss","ht","tm","pbe","syscall","nx","pdpe1gb","rdtscp","lm","constant_tsc","art","arch_perfmon","pebs","bts","rep_good","nopl","xtopology","nonstop_tsc","cpuid","aperfmperf","pni","pclmulqdq","dtes64","monitor","ds_cpl","vmx","smx","est","tm2","ssse3","sdbg","fma","cx16","xtpr","pdcm","pcid","dca","sse4_1","sse4_2","x2apic","movbe","popcnt","tsc_deadline_timer","aes","xsave","avx","f16c","rdrand","lahf_lm","abm","3dnowprefetch","cpuid_fault","epb","cat_l3","cdp_l3","invpcid_single","intel_ppin","ssbd","mba","ibrs","ibpb","stibp","ibrs_enhanced","tpr_shadow","vnmi","flexpriority","ept","vpid","fsgsbase","tsc_adjust","bmi1","hle","avx2","smep","bmi2","erms","invpcid","rtm","cqm","mpx","rdt_a","avx512f","avx512dq","rdseed","adx","smap","clflushopt","clwb","intel_pt","avx512cd","avx512bw","avx512vl","xsaveopt","xsavec","xgetbv1","xsaves","cqm_llc","cqm_occup_llc","cqm_mbm_total","cqm_mbm_local","dtherm","ida","arat","pln","pts","pku","ospke","avx512_vnni","md_clear","flush_l1d","arch_capabilities"],"frequency":"3700.0000","model_name":"Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz"},"disks":[{"by_path":"/dev/disk/by-path/pci-0000:18:00.0-sas-exp0x500056b36a521cff-phy0-lun-0","hctl":"0:0:0:0","model":"KPM5XVUG3T84","name":"/dev/sda","rotational":false,"serial":"58ce38ee20b79731","size":3840755982336,"vendor":"TOSHIBA","wwn":"0x58ce38ee20b79731","wwn_vendor_extension":null,"wwn_with_extension":"0x58ce38ee20b79731"},{"by_path":"/dev/disk/by-path/pci-0000:18:00.0-sas-exp0x500056b36a521cff-phy1-lun-0","hctl":"0:0:1:0","model":"KPM5XVUG3T84","name":"/dev/sdb","rotational":false,"serial":"58ce38ee20b79749","size":3840755982336,"vendor":"TOSHIBA","wwn":"0x58ce38ee20b79749","wwn_vendor_extension":null,"wwn_with_extension":"0x58ce38ee20b79749"},{"by_path":"/dev/disk/by-path/pci-0000:18:00.0-sas-exp0x500056b36a521cff-phy2-lun-0","hctl":"0:0:2:0","model":"KPM5XVUG3T84","name":"/dev/sdc","rotational":false,"serial":"58ce38ee20b79739","size":3840755982336,"vendor":"TOSHIBA","wwn":"0x58ce38ee20b79739","wwn_vendor_extension":null,"wwn_with_extension":"0x58ce38ee20b79739"},{"by_path":"/dev/disk/by-path/pci-0000:18:00.0-sas-exp0x500056b36a521cff-phy3-lun-0","hctl":"0:0:3:0","model":"KPM5XVUG3T84","name":"/dev/sdd","rotational":false,"serial":"58ce38ee20b7974d","size":3840755982336,"vendor":"TOSHIBA","wwn":"0x58ce38ee20b7974d","wwn_vendor_extension":null,"wwn_with_extension":"0x58ce38ee20b7974d"},{"by_path":"/dev/disk/by-path/pci-0000:5e:00.0-ata-1","hctl":"15:0:0:0","model":"DELLBOSS VD","name":"/dev/sde","rotational":true,"serial":"a4941d31db0c0010","size":239990276096,"vendor":"ATA","wwn":null,"wwn_vendor_extension":null,"wwn_with_extension":null},{"by_path":"/dev/disk/by-path/pci-0000:3e:00.0-nvme-1","hctl":null,"model":"Dell Express Flash NVMe P4610 1.6TB SFF","name":"/dev/nvme1n1","rotational":false,"serial":"BTLN944306QM1P6AGN","size":1600321314816,"vendor":null,"wwn":"eui.01000000010000005cd2e445a98b5151","wwn_vendor_extension":null,"wwn_with_extension":null},{"by_path":"/dev/disk/by-path/pci-0000:3d:00.0-nvme-1","hctl":null,"model":"Dell Express Flash NVMe P4610 1.6TB SFF","name":"/dev/nvme0n1","rotational":false,"serial":"BTLN944307LF1P6AGN","size":1600321314816,"vendor":null,"wwn":"eui.01000000010000005cd2e424c48b5151","wwn_vendor_extension":null,"wwn_with_extension":null}],"hostname":"localhost.localdomain","interfaces":[{"biosdevname":null,"client_id":null,"has_carrier":false,"ipv4_address":null,"ipv6_address":null,"lldp":null,"mac_address":"e4:43:4b:aa:25:b1","name":"eno2","product":"0x1521","vendor":"0x8086"},{"biosdevname":null,"client_id":null,"has_carrier":true,"ipv4_address":null,"ipv6_address":"fe80::71c0:d238:7a61:9267%ens2f1","lldp":null,"mac_address":"b8:59:9f:d5:83:2b","name":"ens2f1","product":"0x1015","vendor":"0x15b3"},{"biosdevname":null,"client_id":null,"has_carrier":true,"ipv4_address":null,"ipv6_address":"fe80::c05d:fc1f:d987:4499%ens7f0","lldp":null,"mac_address":"b8:59:9f:d5:83:3a","name":"ens7f0","product":"0x1015","vendor":"0x15b3"},{"biosdevname":null,"client_id":null,"has_carrier":true,"ipv4_address":null,"ipv6_address":"fe80::7128:86d1:8139:c6d%eno3","lldp":null,"mac_address":"e4:43:4b:aa:25:b2","name":"eno3","product":"0x1521","vendor":"0x8086"},{"biosdevname":null,"client_id":null,"has_carrier":false,"ipv4_address":null,"ipv6_address":null,"lldp":null,"mac_address":"e4:43:4b:aa:25:b0","name":"eno1","product":"0x1521","vendor":"0x8086"},{"biosdevname":null,"client_id":null,"has_carrier":true,"ipv4_address":null,"ipv6_address":"fe80::20d0:288a:4ced:98f7%ens7f1","lldp":null,"mac_address":"b8:59:9f:d5:83:3b","name":"ens7f1","product":"0x1015","vendor":"0x15b3"},{"biosdevname":null,"client_id":null,"has_carrier":false,"ipv4_address":null,"ipv6_address":null,"lldp":null,"mac_address":"e4:43:4b:aa:25:b3","name":"eno4","product":"0x1521","vendor":"0x8086"},{"biosdevname":null,"client_id":null,"has_carrier":true,"ipv4_address":"192.168.121.68","ipv6_address":"fe80::2c64:1432:ac7b:7d47%ens2f0","lldp":null,"mac_address":"b8:59:9f:d5:83:2a","name":"ens2f0","product":"0x1015","vendor":"0x15b3"}],"memory":{"physical_mb":196608,"total":201209126912},"system_vendor":{"manufacturer":"Dell Inc.","product_name":"PowerEdge R740xd (SKU=NotProvided;ModelName=PowerEdge R740xd)","serial_number":"ABCXYZ"}},"ipmi_address":"192.168.110.50","ipmi_v6address":null,"local_gb":222,"macs":["b8:59:9f:d5:83:2a"],"memory_mb":196608,"root_disk":{"by_path":"/dev/disk/by-path/pci-0000:5e:00.0-ata-1","hctl":"15:0:0:0","model":"DELLBOSS VD","name":"/dev/sde","rotational":true,"serial":"a4941d31db0c0010","size":239990276096,"vendor":"ATA","wwn":null,"wwn_vendor_extension":null,"wwn_with_extension":null}}}
`

Please let us know if you need any additional information would be to happy to share.

**Comment by zaneb** [comment]
The data you're getting back from Ironic inspector doesn't contain the "extra" key. It's not clear why this would be the case, given that you have the processing hook enabled. Maybe inspector is not getting the data from ironic-python-agent for some reason?

**Comment by dtantsur** [comment]
/close

At least one fix has been merged to ironic-inspector around this area, so I hope it has been fixed. If not, please reopen providing ironic-inspector and ramdisk logs.

**Comment by sumitjadhav1** [comment]
@dtantsur : Could you please help us locate the fix you mentioned about..?? Mean time, we will also test this at our end & update the comments. Will re-open the issue as soon as we test this.

**Comment by sumitjadhav1** [comment]
Here is the sample snippet from metal3.io/try-it.html page which shows this was working earlier in metal3-dev-env setup with virtual nodes as well. But it's not working right now in virtual node setup. We did the Metal3 deployment yesterday.

`    firmware:
      bios:
        date: 04/01/2014
        vendor: SeaBIOS
        version: 1.10.2-1ubuntu1`

Snippet from our metal3 setup with virtual nodes : 

`        {
          "id" : "firmware",
          "class" : "memory",
          "claimed" : true,
          "description" : "BIOS",
          "vendor" : "SeaBIOS",
          "physid" : "0",
          "version" : "1.10.2-1ubuntu1",
          "date" : "04/01/2014",
          "units" : "bytes",
          "size" : 98304
        },
`

Here are logs requested logs : ramdisk & ironic-inspector logs in tar file
[ramdisk_and_inspector_logs.tar.gz](https://github.com/metal3-io/baremetal-operator/files/5130101/ramdisk_and_inspector_logs.tar.gz)

Please let us know if some additional logs are required. Thanks.

**Comment by sumitjadhav1** [comment]
With the last week's code commits, we see the firmware details updated in introspection data for Virtual as well as Real nodes.
Not sure which commit in metal3 or Ironic code exactly fixed this issue. Closing the issue now.

Here are the sample outputs : 
1. For Virtual Nodes

`      firmware:
        bios:
          date: 04/01/2014
          vendor: SeaBIOS
          version: 1.10.2-1ubuntu1
      hostname: node-1`
 
2. For Real Nodes

`      firmware:
        bios:
          date: 05/04/2020
          vendor: Dell Inc.
          version: 2.7.7
      hostname: localhost.localdomain`

**Comment by sumitjadhav1** [comment]
Re-opening this issue, as we have observed this issue with recent BMO code. This could be an Ironic issue it seems. Requesting @zaneb @dtantsur @juliakreger to take a look. With recent commits in metal3-dev-env, we observe that this data is updated in ramdisk logs but not in BMO introspection data. Here is the snippet :

`  "children" : [
    {
      "id" : "core",
      "class" : "bus",
      "claimed" : true,
      "description" : "Motherboard",
      "physid" : "0",
      "children" : [
        {
          "id" : "firmware",
          "class" : "memory",
          "claimed" : true,
          "description" : "BIOS",
          "vendor" : "SeaBIOS",
          "physid" : "0",
          "version" : "1.10.2-1ubuntu1",
          "date" : "04/01/2014",
          "units" : "bytes",
          "size" : 98304
        },
`

`    firmware:
      bios:
        date: ""
        vendor: ""
        version: ""
    hostname: node-0
`
The reason for highlighting this issue : we have a proposal in HWCC [Support for new parameters in HWCC](https://github.com/metal3-io/metal3-docs/pull/147) and we are proposing to add this parameter.

**Comment by dtantsur** [comment]
As discussed on the community meeting, let's collect new inspector and ramdisk logs to be sure about the current root cause.

**Comment by sumitjadhav1** [comment]
Hi @dtantsur , attached logs as per request, PTAL and let us know if you need any additional logs.
[logs_Firmware_details_missing.zip](https://github.com/metal3-io/baremetal-operator/files/5532300/logs_Firmware_details_missing.zip)

**Comment by sumitjadhav1** [comment]
Hi @dtantsur , could you please look into the logs and share your opinion on the same. In case you need additional logs, please let us know.

**Comment by sumitjadhav1** [comment]
Hi @dtantsur @juliakreger @elfosardo request your help on this issue. Could you please take a look ?? Do let us know in case of any additional information is required. Thanks

**Comment by dtantsur** [comment]
> ipa-inspector-collectors=default,extra-hardware,logs

We have an invalid option name (`inspector` should be `inspection`), this is why the collection does not happen.
