### ISSUE TITLE
Empty namespace in UserData or NetworkData part of the BMH spec defaults to default namespace

### ISSUE THREAD

**Issue by maelk** [metal3-io/baremetal-operator#462]
If the UserData or NetworkData object references does not have a namespace specified, the Get operation is performed on the default namespace. Should it rather default to the namespace of the BMH ?

**Comment by dhellmann** [comment]
I think that makes sense.

@mhrivnak what do you think?

**Comment by maelk** [comment]
Actually, According to https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/options.go#L304, it lists across all namespaces. Would that be a desired behavior ?

**Comment by maelk** [comment]
I am a bit confused right now about what would be the exact behavior if that field is left empty

**Comment by mhrivnak** [comment]
When doing a List, leaving namespace as `""` will search across all namespaces. When doing a Get, I'm not sure what it would do by default. We should probably just set a default that makes sense for our use case. Setting it to the BMH's namespace makes sense to me.

The only other option I'd consider is using validation to enforce that the namespace must be set, but that would probably require a webhook, and that's likely more work than we want to bite off right now. That also may or may not be a desirable behavior, but I wanted to at least state it as a theoretical option. Over the long term, code, docs and APIs remain simpler when we can constrain the range of variation in user input, but that might just not be practical at this moment.

**Comment by maelk** [comment]
I would also support defaulting it to the BMH namespace.
