### ISSUE TITLE
standardize log timestamps of Baremetal-operator container

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/baremetal-operator#466]
Currently, timestamps in the logs of Baremetal-operator are not in human readable format.
When debugging it with other controllers, we need to see log entries in chronological order. 
This is difficult for the naked eye. 

The second issue is that log entires are not uniform. They are a mix of both.
Example:

```
{"level":"info","ts":1585114266.9621124,"logger":"baremetalhost_ironic","msg":"ironic settings","endpoint":
{"level":"info","ts":1585114266.9627125,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1585114266.9648638,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I0325 05:31:06.964099       1 leaderelection.go:241] attempting to acquire leader lease  metal3/baremetal-operator...
I0325 05:31:06.992323       1 leaderelection.go:251] successfully acquired lease metal3/baremetal-operator
{"level":"info","ts":1585114266.9944365,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"metal3-baremetalhost-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1585114267.0962887,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"metal3-baremetalhost-controller","source":"kind source: /, Kind="}
```

**Comment by Xenwar** [comment]
For perspective, here are long entries for capm3-controller-manager

I0325 08:25:00.337174       1 metal3machine_controller.go:98] ......
I0325 08:25:00.634846       1 metal3machine_controller.go:98] ......
I0325 08:25:00.899350       1 metal3machine_manager.go:135] .....
I0325 08:25:00.918845       1 metal3machine_manager.go:135] .....

**Comment by Xenwar** [comment]
I consider this to be a low priority task and could be made a good first issue.

**Comment by zaneb** [comment]
Instead of fixing this to output unstructured logs consistently, I wrote [bmo-log-parse](https://github.com/zaneb/bmo-log-parse) for manipulating the structured logs.
