### ISSUE TITLE
BMO should have kustomize config for test setup with BMO standalone

### ISSUE THREAD

**Issue by mikkosest** [metal3-io/baremetal-operator#472]
When using kind cluster in metal3-dev-env, Ironic needs to run outside cluster. It would be handy to have similar kustomize config for BMO standalone than there is for baremetal-operator/deploy/ironic-keepalived-config. Needed by  metal3-io/metal3-dev-env#277

**Comment by maelk** [comment]
Do you mean https://github.com/metal3-io/metal3-dev-env/issues/277 ?

**Comment by mikkosest** [comment]
> Do you mean [metal3-io/metal3-dev-env#277](https://github.com/metal3-io/metal3-dev-env/pull/277) ?

Corrected

**Comment by maelk** [comment]
Is this closed by #473  ? @mikkosest

**Comment by dhellmann** [comment]
See #500 and #501

**Comment by maelk** [comment]
I would think this is resolved. Please re-open if not.
