### ISSUE TITLE
BMO should be provisioning baremetals using direct redfish calls instead of through ironic which enable us to boot over WAN. Also support for creating RAIDS and custom disk partitions should be provided

### ISSUE THREAD

**Issue by Kiriti29** [metal3-io/baremetal-operator#476]
BMO should be provisioning baremetals using direct redfish calls instead of through ironic which enable us to boot over WAN. This approach enables us to avoid creating a local dhcp server dependency which won't be accessible when the control plane running BMO and the target bootstrap node are in different networks.

Second point here is to enable configuring the harware raids and disk partitions while bootstrapping the baremetal itself since redfish api supports these functionalities.

**Comment by dhellmann** [comment]
The redfish API isn't sufficient to provision a host. We need the ironic agent, which knows how to download an image and write it to the disks of the host.

There is ongoing work to let us attach the image containing the agent to the host using a remote ISO. That all relies on Ironic, but does use the redfish APIs. Booting the host from that ISO would not require the DHCP server we have in our deployment today, but the host would still need a way to get an IP address.

There are a few other tickets related to RAID setup already, so I think we can separate that issue from the redfish question.

**Comment by stbenjam** [comment]
Please have a look at https://github.com/metal3-io/baremetal-operator/issues/206 for information about RAID.  Disk partitioning is related to the OS configuration, and would be done with user data (via cloud-init, ignition, etc).

Based on @dhellmann's comment above we don't think we could do this without Ironic, but feel free to open a single-topic issue related to this, or draft a proposal doc.  BMO is generic enough that you can write an alternative provisioner than the default implementation that uses Ironic.

/close
