### ISSUE TITLE
How to enable SRIOV configuration for a baremetal host

### ISSUE THREAD

**Issue by sb1975** [metal3-io/baremetal-operator#485]
Requirement : As a Tenant I need to utilize SRIOV function so that I can have direct access to the Network via the Network Interface. For this the host needs to be configured with SRIOV PF and VF before the host operating system installation.
How can the baremetal-operator be enhanced to support the SRIOV function ?

**Comment by dhellmann** [comment]
I don't know much about SRIOV. How does one configure the PF and VF? (What are those?) Is the configuration done from within the operating system on the host? Or the BIOS?

**Comment by sb1975** [comment]
The Virtual Functions for the network device will be created at boot time when the kernel module and driver for the device is loaded. 
Then the SRIOV device plugin(https://github.com/intel/sriov-network-device-plugin) will detect the SRIOV VFs. Then it works with SRIOV CNI and meta-plugin like multus.
Below link may help as well, which seems like more of an operator focused approach - https://github.com/openshift/sriov-network-operator
https://docs.openshift.com/container-platform/4.2/networking/multiple_networks/configuring-sr-iov.html
Also below is an example of configuring SRIOV in mellanox devices - https://community.mellanox.com/s/article/kubernetes-ipoib-ethernet-rdma-sr-iov-networking-with-connectx4-connectx5

Some other reference : https://software.intel.com/en-us/articles/configure-sr-iov-network-virtual-functions-in-linux-kvm

**Comment by maelk** [comment]
From your description, it seems that everything needs to be done at boot time, so if you have a disk image with a built-in SRIOV feature (i.e. proper kernel modules, drivers and configuration), then it should already be supported out of the box by Metal3.

**Comment by sb1975** [comment]
But if you need Day2- Reconfiguration of SRIOV ports , then wont you need to integrate with something like the sriov-network-operator ?

**Comment by maelk** [comment]
Probably, but this is not something that is in Metal3 scope, it is a more general issue for any Kubernetes node that uses SRIOV. As far as I understood your point, there is no baremetal specific operation there. Is this correct ?

**Comment by maelk** [comment]
Possibly related : https://github.com/metal3-io/baremetal-operator/pull/302

**Comment by sb1975** [comment]
so the first step will be to ensure the SRIOV Enablement is done via BMO which depends on this PR - Sriov enablement in BMO : https://github.com/metal3-io/baremetal-operator/pull/302 
The other aspect of configuring the SRIOV PF, VF is being handled by the cloud-init which is provided as part of PreKubeadmConfig , further details provided in this reference 
https://godoc.org/sigs.k8s.io/cluster-api/bootstrap/kubeadm/api/v1alpha3#KubeadmConfigSpec 
https://github.com/metal3-io/metal3-dev-env/blob/master/vm-setup/roles/v1aX_integration_test/templates/workers_ubuntu.yaml 

So closing this for now as all the query and configuration needed is updated as of now.

**Comment by nmathew** [comment]
@sb1975 Will this enable /sys/class/net/${PF_NAME}/device/sriov_numvfs. Do you have a sample config.
