### ISSUE TITLE
Fix broken link to vBMC doc in docs/dev-setup.md

### ISSUE THREAD

**Issue by demonCoder95** [metal3-io/baremetal-operator#507]
The hyperlink to vBMC documentation in the dev-setup.md file is broken. The documentation has moved [here](https://docs.openstack.org/project-deploy-guide/tripleo-docs/latest/environments/virtualbmc.html)
I just noticed this while reading the docs, I can send a quick patch myself for this.

**Comment by dhellmann** [comment]
This was fixed by #508
