### ISSUE TITLE
StatusAnnotation is undocumented

### ISSUE THREAD

**Issue by mhrivnak** [metal3-io/baremetal-operator#524]
The [StatusAnnotation](https://github.com/metal3-io/baremetal-operator/blob/7438682/pkg/apis/metal3/v1alpha1/baremetalhost_types.go#L26-L27) was added as part of the BareMetalHost API, but it doesn't have documentation to describe what it's for, what value it should have, how the value gets used, or why you would put status in an annotation instead of in the Status. It would clear things up for someone trying to understand the API (including other developers) to write a couple of sentences about what it's for and how it works.

**Comment by maelk** [comment]
@kashifest Can you look into this ?

**Comment by kashifest** [comment]
Sure. I will add some details @maelk  @mhrivnak

**Comment by zaneb** [comment]
Fixed by #524
/close
