### ISSUE TITLE
add dukov as reviewer

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/baremetal-operator#552]
@dukov qualifies as a reviewer under the policy described in https://github.com/metal3-io/metal3-docs/pull/93 but is not a member of the org. After the rest of the migration work is done, we should invite dukov to join and be added as a reviewer.

**Comment by dhellmann** [comment]
@dukov, I sent you an invitation to join the org. After you have accepted the invitation, you could submit a patch to add yourself to the reviewers list in the OWNERS file of this repo. Then, I will review the PR and merge it.

**Comment by dukov** [comment]
Done. See #556

**Comment by dhellmann** [comment]
Merged #556 to complete this.
