### ISSUE TITLE
Failed to create ironic node

### ISSUE THREAD

**Issue by ankit-kumar5** [metal3-io/baremetal-operator#554]
We are currently testing the Metal3/BMO and Cluster Provisioning on ​Proliant DL360 Gen10 using redfish driver. I am facing issue in creating node. Below is the log for ironic container. This error i am getting for vBMC also while installing metal3

2020-06-20 09:29:28.720 46 ERROR wsme.api [req-9db598ba-2a41-4b27-98ce-1eeaa8b2f3ef - - - - -] Server-side error: "Not Found (HTTP 404)". Detail:
Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/wsmeext/pecan.py", line 85, in callfunction
    result = f(self, *args, **kwargs)
File "/usr/lib/python3.6/site-packages/ironic/api/controllers/v1/node.py", line 2264, in post
    new_node, topic)
File "/usr/lib/python3.6/site-packages/ironic/conductor/rpcapi.py", line 227, in create_node
    return cctxt.call(context, 'create_node', node_obj=node_obj)
File "/usr/lib/python3.6/site-packages/ironic/common/json_rpc/client.py", line 112, in call
    **kwargs)
File "/usr/lib/python3.6/site-packages/ironic/common/json_rpc/client.py", line 160, in _request
    result = _get_session().post(url, json=body)
File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 392, in post
    return self.request(url, 'POST', **kwargs)
File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 248, in request
    return self.session.request(url, method, **kwargs)
File "/usr/lib/python3.6/site-packages/keystoneauth1/session.py", line 968, in request
    raise exceptions.from_response(resp, method, url)

keystoneauth1.exceptions.http.NotFound: Not Found (HTTP 404)
: keystoneauth1.exceptions.http.NotFound: Not Found (HTTP 404)
2020-06-20 09:29:28.721 46 INFO eventlet.wsgi.server [req-9db598ba-2a41-4b27-98ce-1eeaa8b2f3ef - - - - -] ::1 "POST /v1/nodes HTTP/1.1" status: 500  len: 452 time: 0.5463657.

IN BMO log, i am seeing this:

2020-06-20T05:46:09.368-0400    ERROR   controller-runtime.controller   Reconciler error        {"controller": "metal3-baremetalhost-controller", "request": "metal3/node-1", "error": "action \"registering\" failed: failed to validate BMC access: failed to register host in ironic: Internal Server Error", "errorVerbose": "Internal Server Error\nfailed to register host in ironic

[centos@metal3 baremetal-operator]$ kubectl get baremetalhost -A
NAMESPACE   NAME       STATUS   PROVISIONING STATUS   CONSUMER   BMC                                                                                         HARDWARE PROFILE   ONLINE   ERROR
metal3      node-0     OK       **registering**                      redfish+http://192.168.111.1:8000/redfish/v1/Systems/e3ef7161-c040-485f-95a2-c25626de0dc0                      true
metal3      node-1     OK       **registering**                      redfish+http://192.168.111.1:8000/redfish/v1/Systems/cd0ec592-70b1-44e0-8913-ccdc288606f2                      true
metal3      worker-9   OK       **registering**                      redfish+http://172.17.1.106/redfish/v1/Systems/1                                                               true

All are stuck in registering phase.

Even i am getting the above when i tried to run locally by following this 
https://github.com/metal3-io/baremetal-operator/blob/master/docs/dev-setup.md

**Comment by zaneb** [comment]
It looks like Ironic is trying (and failing) to contact Keystone, which means it is deployed incorrectly. Are you using the image from https://github.com/metal3-io/ironic-image?

**Comment by ankit-kumar5** [comment]
This is i have configured in config_{user}.sh
# Container image for ironic pod
#
export IRONIC_IMAGE="quay.io/metal3-io/ironic"

Yeah, even i am confused why it contacting keystone. I have checked the ironic.conf it is mentioned **auth_strategy = noauth**. So it should not contact keystone. Am i missing something that needs to be mentioned in the config file.

Attaching the config_{user}.sh

# Default of ~/.ssh/id_rsa.pub is set in lib/common.sh
#
export SSH_PUB_KEY=~/.ssh/id_rsa.pub

#
# Select the Container Runtime, can be "podman" or "docker"
# Defaults to "podman"
#
export CONTAINER_RUNTIME="podman"

#
# Set the Baremetal Operator repository to clone
#
export BMOREPO="${BMOREPO:-https://github.com/metal3-io/baremetal-operator.git}"

#
# Set the Baremetal Operator branch to checkout
#
export BMOBRANCH="${BMOBRANCH:-master}"

#
# Set the Cluster Api baremetal provider repository to clone
#
export CAPBMREPO="${CAPBMREPO:-https://github.com/metal3-io/cluster-api-provider-baremetal.git}"

#
# Set the Cluster Api baremetal provider branch to checkout
#
export CAPBMBRANCH="${CAPBMBRANCH:-master}"

#
# Force deletion of the BMO and CAPBM repositories before cloning them again
#
export FORCE_REPO_UPDATE="${FORCE_REPO_UPDATE:-false}"

#
# Run a local baremetal operator instead of deploying in Kubernetes
#
export BMO_RUN_LOCAL=true

#
# Run a local CAPI operator instead of deploying in Kubernetes
#
export CAPBM_RUN_LOCAL=true

#
# Do not retry on failure during verifications or tests of the environment
# This should be true. It could only be set to false for verifications of a
# dev env deployment that fully completed. Otherwise failures will appear as
# resources are not ready.
#
export SKIP_RETRIES=false

#
# Interval between retries after verification or test failure
#
export TEST_TIME_INTERVAL=10

#
# Number of maximum verification or test retries
#
export TEST_MAX_TIME=120

#
# Set the driver. The default value is 'ipmi'
#
export BMC_DRIVER="redfish"

# Select the Cluster API version
# Accepted values : v1alpha1 v1alpha2
# default: v1alpha1
#
export CAPI_VERSION=v1alpha3

# Configure provisioning network for single-stack ipv6
PROVISIONING_IPV6=false

# Image OS (can be "Cirros", "Ubuntu", "Centos", overriden by IMAGE_* if set)
#
export IMAGE_OS="Centos"

export DEFAULT_HOSTS_MEMORY=8192
# Image for target hosts deployment
#
export IMAGE_NAME="CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2"

# Location of the image to download
#
export IMAGE_LOCATION="http://172.17.1.225:8010/"

# Image username for ssh
#
export IMAGE_USERNAME="centos"

# Container image for ironic pod
#
export IRONIC_IMAGE="quay.io/metal3-io/ironic"

# Container image for vbmc container
#
export VBMC_IMAGE="quay.io/metal3-io/vbmc"

# Container image for sushy-tools container
#
export SUSHY_TOOLS_IMAGE="quay.io/metal3-io/sushy-tools"

# APIEndpoint IP for target cluster
export CLUSTER_APIENDPOINT_IP="192.168.111.249"

# Cluster provisioning Interface
export CLUSTER_PROVISIONING_INTERFACE="ironicendpoint"

# POD CIDR
export POD_CIDR=${POD_CIDR:-"192.168.0.0/18"}

export EPHEMERAL_CLUSTER="minikube"

**Comment by ankit-kumar5** [comment]
> It looks like Ironic is trying (and failing) to contact Keystone, which means it is deployed incorrectly. Are you using the image from https://github.com/metal3-io/ironic-image?

Also this is the error i am getting in **bmo.out.log**

ERROR   controller-runtime.controller   Reconciler error        {"controller": "metal3-baremetalhost-controller", "request": "metal3/node-0", "error": "action \"registering\" failed: failed to validate BMC access: failed to register host in ironic: Internal Server Error", "errorVerbose": "Internal Server Error\nfailed to register host in ironic

**Comment by dhellmann** [comment]
@ankit-kumar5 can you describe how you deployed this instance of metal3? Are you using kustomize and the deploy YAML files in each repository? Did you use metal3-dev-env? Something else?

**Comment by ankit-kumar5** [comment]
> @ankit-kumar5 can you describe how you deployed this instance of metal3? Are you using kustomize and the deploy YAML files in each repository? Did you use metal3-dev-env? Something else?

Yeah, i used metal3-dev-env for deploying metal3. I followed this link 

https://metal3.io/blog/2020/02/18/metal3-dev-env-install-deep-dive.html

**Comment by ankit-kumar5** [comment]
I did install standalone setup of ironic. In ironic.conf when the value for **rpc-transport = json-rpc**, then i am facing same issue over there. But when the value is set **rpc-transport = oslo**, the commands work seemlessly. But in metal3 environment setting the value to **oslo** fails with error 

2020-06-27 06:52:46.151 28 ERROR oslo.messaging._drivers.impl_rabbit [req-170bfa95-31b7-4e14-9d48-333fb89d4ebd - - - - -] Connection failed: [Errno 111] ECONNREFUSED (retrying in 32.0 seconds): ConnectionRefusedError: [Errno 111] ECONNREFUSED
2020-06-27 06:53:18.194 28 ERROR oslo.messaging._drivers.impl_rabbit [req-170bfa95-31b7-4e14-9d48-333fb89d4ebd - - - - -] Connection failed: [Errno 111] ECONNREFUSED (retrying in 32.0 seconds): ConnectionRefusedError: [Errno 111] ECONNREFUSED

Can you please tell what is the correct config for ironic to use?

**Comment by ankit-kumar5** [comment]
Adding host=$IRONIC_IP in ironic.conf worked.

Thanks.

**Comment by zaneb** [comment]
In the metal3 deployment of Ironic there's no RabbitMQ, so `rpc_transport = json-rpc` is definitely correct.
