### ISSUE TITLE
Typo in bootMACAddress causes non-obvious failures

### ISSUE THREAD

**Issue by hardys** [metal3-io/baremetal-operator#580]
If someone accidentally writes `bootMacAddress` instead of `bootMACAddress` (or any other similar typo) we skip creating the ironic port for that node and silently ignore the wrong key containing the MAC.

This then leads to one of several non-obvious failure modes:

- Testing in metal3-dev-env we see the BMH stuck forever in `inspecting` state, IPA reports an error like `Failed looking up node with addresses <mac> ...`

- In downstream OpenShift testing deployment/inspection actually succeeds, but then if something causes the pod containing the ironic services to get rescheduled (such as a controlplane outage), Ironic fails on adoption due to the missing port.

I'm not yet certain why the behavior differs in each case (need to compare the ironic configs), but it seems that we should validate the BMH more strictly to avoid this?

There is also no obvious way to recover from this - modifying the yaml to correct the bootMACAddress key isn't enough, the host is still stuck inspecting (or in adopt failed), I suspect this is because we don't modify the BMC secret, so we don't re-attempt the validate path where the port can now be created.

**Comment by hardys** [comment]
Thanks to @dtantsur for confirming that when using baremetal with IPMI, inspector can guess which data belongs to which node by matching IPMI addresses - so the difference with the downstream results above was that it's a baremetal env and not vbmc as when testing with metal3-dev-env

For some additional context see this downstream issue ref https://bugzilla.redhat.com/show_bug.cgi?id=1854142

**Comment by hardys** [comment]
So it looks like @zaneb added validations for the BMH fields in https://github.com/metal3-io/baremetal-operator/pull/256 but that doesn't account for the case where there's a key that is present but doesn't match the schema for the resource.

I'm not sure on the preferred pattern for adding that, but it seems that we could avoid this problem if we rejected BMH resources that did not conform to the required schema (e.g contain keys we didn't expect in this case).

**Comment by maelk** [comment]
Is there an equivalent of pruning for kubebuilder with Operator SDK ? By default it is enabled in kubebuilder (you can turn it off with specific annotations https://book.kubebuilder.io/reference/markers/crd-processing.html)

**Comment by dhellmann** [comment]
> Is there an equivalent of pruning for kubebuilder with Operator SDK ? By default it is enabled in kubebuilder (you can turn it off with specific annotations https://book.kubebuilder.io/reference/markers/crd-processing.html)

I think @honza determined that it wasn't supported, which is another reason to move off of operator-sdk. I'm looking at kubebuilder again this week to see if I can work around the limitations I found a few weeks ago.

**Comment by hardys** [comment]
I'm not sure that pruning unknown fields is enough, given that bootMACAddress is an optional field?

Ideally we need some way of rejecting any resource containing unknown fields, which is a slightly different requirement I think?

**Comment by dhellmann** [comment]
> I'm not sure that pruning unknown fields is enough, given that bootMACAddress is an optional field?
> 
> Ideally we need some way of rejecting any resource containing unknown fields, which is a slightly different requirement I think?

If there's a way to do that, I would expect it to be an OpenAPI layer thing rather than something we had to do ourselves. We're generating the schema data as part of the CRD. Is it being used?

**Comment by maelk** [comment]
We might be able to use webhooks to reject such a resource as long as we check it as an Unstructured object. Any type of conversion would effectively prune it.

**Comment by hardys** [comment]
So it looks like there should be client side validation when you enable pruning:

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2

So perhaps that is enough, I'll give it a try as it should be simpler than the admission webhook approach I think?

**Comment by dhellmann** [comment]
> So it looks like there should be client side validation when you enable pruning:
> 
> https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2
> 
> So perhaps that is enough, I'll give it a try as it should be simpler than the admission webhook approach I think?

Yes, let's definitely see if we can enable that. As I said earlier, I think @honza determined that operator-sdk did not honor the setting to enable it, but I've worked out how we can change to kubebuilder which should honor it so we can include better API validation to the list of motivations for that work.

**Comment by hardys** [comment]
Ok so it does seem that pruning enables client-side validation against the schema, adding `preserveUnknownFields: false` to the CRD results in this error when the bootMACAddress is malformed:

```
$ kubectl apply -f bmhosts_crs.yaml
secret/node-0-bmc-secret unchanged
error: error validating "bmhosts_crs.yaml": error validating data: ValidationError(BareMetalHost.spec): unknown field "bootMacAddress" in io.metal3.v1alpha1.BareMetalHost.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by zaneb** [comment]
See #327.
