### ISSUE TITLE
Hardware profile "unknown" for Dell Idrack baremetals

### ISSUE THREAD

**Issue by FaridHub** [metal3-io/baremetal-operator#617]
I have been facing hardware profile status as "**unknown**" for all the Dell Idrack machines I have been using.
Kindly find the  description of bmh below "**kubectl describe bmh/bmh-idrac-247 -n metal3**"

Name:         bmh-idrac-247
Namespace:    metal3
Labels:       <none>
Annotations:  API Version:  metal3.io/v1alpha1
Kind:         BareMetalHost
Metadata:
  Creation Timestamp:  2020-08-28T17:45:17Z
  Finalizers:
    baremetalhost.metal3.io
  Generation:  1
  Managed Fields:
    API Version:  metal3.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:bmc:
          .:
          f:address:
          f:credentialsName:
          f:disableCertificateVerification:
        f:bootMACAddress:
        f:consumerRef:
          .:
          f:kind:
          f:name:
        f:image:
          .:
          f:checksum:
          f:url:
        f:online:
    Manager:      kubectl
    Operation:    Update
    Time:         2020-08-28T17:45:17Z
    API Version:  metal3.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"baremetalhost.metal3.io":
      f:status:
        .:
        f:errorMessage:
        f:goodCredentials:
          .:
          f:credentials:
            .:
            f:name:
            f:namespace:
          f:credentialsVersion:
        f:hardware:
          .:
          f:cpu:
            .:
            f:arch:
            f:clockMegahertz:
            f:count:
            f:flags:
            f:model:
          f:firmware:
            .:
            f:bios:
              .:
              f:date:
              f:vendor:
              f:version:
          f:hostname:
          f:nics:
          f:ramMebibytes:
          f:storage:
          f:systemVendor:
            .:
            f:manufacturer:
            f:productName:
            f:serialNumber:
        f:hardwareProfile:
        f:lastUpdated:
        f:operationHistory:
          .:
          f:deprovision:
            .:
            f:end:
            f:start:
          f:inspect:
            .:
            f:end:
            f:start:
          f:provision:
            .:
            f:end:
            f:start:
          f:register:
            .:
            f:end:
            f:start:
        f:operationalStatus:
        f:poweredOn:
        f:provisioning:
          .:
          f:ID:
          f:bootMode:
          f:image:
            .:
            f:checksum:
            f:url:
          f:rootDeviceHints:
            .:
            f:deviceName:
          f:state:
        f:triedCredentials:
          .:
          f:credentials:
            .:
            f:name:
            f:namespace:
          f:credentialsVersion:
    Manager:         baremetal-operator
    Operation:       Update
    Time:            2020-08-28T18:32:35Z
  Resource Version:  19472405
  Self Link:         /apis/metal3.io/v1alpha1/namespaces/metal3/baremetalhosts/bmh-idrac-247
  UID:               812e10e0-3657-4230-86fe-be55db2d482d
Spec:
  Bmc:
    Address:                           idrac://10.X.X.X.X
    Credentials Name:                  bmc-secret-2
    Disable Certificate Verification:  true
  Boot MAC Address:                    1C:XX:XX:XX:XX
  Consumer Ref:
    Kind:  BareMetalMachine
    Name:  baremetal-machine-idrac-247-fedora
  Image:
    Checksum:  http://10.X.X.X:6180/images/Fedora-Cloud-Base-32-1.6.x86_64.qcow2.md5sum
    URL:       http://10.X.X.X:6180/images/Fedora-Cloud-Base-32-1.6.x86_64.qcow2
  Online:      true
Status:
  Error Message:
  Good Credentials:
    Credentials:
      Name:               bmc-secret-2
      Namespace:          metal3
    Credentials Version:  19454009
  Hardware:
    Cpu:
      Arch:             x86_64
      Clock Megahertz:  3900
      Count:            72
      Flags:
        3dnowprefetch
        abm
        acpi
        adx
        aes
        aperfmperf
        apic
        arat
        arch_capabilities
        arch_perfmon
        art
        avx
        avx2
        avx512_vnni
        avx512bw
        avx512cd
        avx512dq
        avx512f
        avx512vl
        bmi1
        bmi2
        bts
        cat_l3
        cdp_l3
        clflush
        clflushopt
        clwb
        cmov
        constant_tsc
        cpuid
        cpuid_fault
        cqm
        cqm_llc
        cqm_mbm_local
        cqm_mbm_total
        cqm_occup_llc
        cx16
        cx8
        dca
        de
        ds_cpl
        dtes64
        dtherm
        dts
        epb
        ept
        erms
        est
        f16c
        flexpriority
        flush_l1d
        fma
        fpu
        fsgsbase
        fxsr
        hle
        ht
        ibpb
        ibrs
        ibrs_enhanced
        ida
        intel_ppin
        intel_pt
        invpcid
        invpcid_single
        lahf_lm
        lm
        mba
        mca
        mce
        md_clear
        mmx
        monitor
        movbe
        mpx
        msr
        mtrr
        nonstop_tsc
        nopl
        nx
        ospke
        pae
        pat
        pbe
        pcid
        pclmulqdq
        pdcm
        pdpe1gb
        pebs
        pge
        pku
        pln
        pni
        popcnt
        pse
        pse36
        pts
        rdrand
        rdseed
        rdt_a
        rdtscp
        rep_good
        rtm
        sdbg
        sep
        smap
        smep
        smx
        ss
        ssbd
        sse
        sse2
        sse4_1
        sse4_2
        ssse3
        stibp
        syscall
        tm
        tm2
        tpr_shadow
        tsc
        tsc_adjust
        tsc_deadline_timer
        vme
        vmx
        vnmi
        vpid
        x2apic
        xgetbv1
        xsave
        xsavec
        xsaveopt
        xsaves
        xtopology
        xtpr
      Model:  Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
    Firmware:
      Bios:
        Date:
        Vendor:
        Version:
    Hostname:     ar25sXXX.XXXXXX.com
    Nics:
      Ip:           10.X.X.X
      Mac:          1c:xx.xx.xx.xx.xx
      Model:        0x15b3 0x1015
      Name:         eno2
      Pxe:          false
      Speed Gbps:   0
      Vlan Id:      0
      Ip:           10.X.X.X
      Mac:          1c:xx.xx.xx.xx.xx
      Model:        0x15b3 0x1015
      Name:         eno1
      Pxe:          true
      Speed Gbps:   0
      Vlan Id:      0
    Ram Mebibytes:  393216
    Storage:
      Hctl:                  0:0:0:0
      Model:                 MTFDDAK960TDD
      Name:                  /dev/sda
      Rotational:            false
      Serial Number:         194424BD944E
      Size Bytes:            960197124096
      Vendor:                ATA
      Wwn:                   0x500a075124bd944e
      Wwn With Extension:    0x500a075124bd944e
      Hctl:                  0:2:0:0
      Model:                 PERC H330 Mini
      Name:                  /dev/sdb
      Rotational:            true
      Serial Number:         64cd98f0a0d8fa00263b5f6d0716cd0d
      Size Bytes:            8000987201536
      Vendor:                DELL
      Wwn:                   0x64cd98f0a0d8fa00
      Wwn Vendor Extension:  0x263b5f6d0716cd0d
      Wwn With Extension:    0x64cd98f0a0d8fa00263b5f6d0716cd0d
    System Vendor:
      Manufacturer:   Dell Inc.
      Product Name:   PowerEdge R640 (SKU=NotProvided;ModelName=PowerEdge R640)
      Serial Number:  HZW0H13
  Hardware Profile:   unknown
  Last Updated:       2020-08-28T18:32:35Z
  Operation History:
    Deprovision:
      End:    <nil>
      Start:  <nil>
    Inspect:
      End:    2020-08-28T18:07:14Z
      Start:  2020-08-28T17:45:28Z
    Provision:
      End:    <nil>
      Start:  2020-08-28T18:07:14Z
    Register:
      End:             2020-08-28T17:45:28Z
      Start:           2020-08-28T17:45:17Z
  Operational Status:  OK
  Powered On:          false
  Provisioning:
    ID:         473f12dd-5cfb-4811-a316-4af4fb60967a
    Boot Mode:  UEFI
    Image:
      Checksum:
      URL:
    Root Device Hints:
      Device Name:  /dev/sda
    State:          provisioning
  Tried Credentials:
    Credentials:
      Name:               bmc-secret-2
      Namespace:          metal3
    Credentials Version:  19454009
Events:
  Type    Reason               Age   From                         Message
  ----    ------               ----  ----                         -------
  Normal  Registered           47m   metal3-baremetal-controller  Registered new host
  Normal  BMCAccessValidated   47m   metal3-baremetal-controller  Verified access to BMC
  Normal  InspectionStarted    47m   metal3-baremetal-controller  Hardware inspection started
  Normal  InspectionComplete   25m   metal3-baremetal-controller  Hardware inspection completed
  **Normal  ProfileSet           25m   metal3-baremetal-controller  Hardware profile set: unknown**
  Normal  ProvisioningStarted  25m   metal3-baremetal-controller  Image provisioning started for http://10.37.49.251:6180/images/Fedora-Cloud-Base-32-1.6.x86_64.qcow2

> **kubectl gte bmh -n metal3**

![image](https://user-images.githubusercontent.com/8111839/91605132-9c4a5880-e98d-11ea-9e2e-84ee59b3d872.png)

Just like to know if this is normal or it must represent some hardware information. However, I am able to provision OS through it.

**Comment by dhellmann** [comment]
This is normal. The hardware profile feature was never fully developed, so the logic for choosing a profile is limited. The only use for the profile is to set the root device hints, and now that we have an API for doing that you should go ahead and use those fields instead of the profile.

**Comment by dhellmann** [comment]
I should also mention that the hardware-classification-controller provides some of the features that were originally planned for the hardware profile feature of the baremetal-operator, so if you are looking for a tool to examine the hardware and make decisions based on what is found you could look there.

**Comment by zaneb** [comment]
That's the default so if you didn't set it then that is expected. See the [API documentation](https://github.com/metal3-io/baremetal-operator/blob/master/docs/api.md#status-fields) for details.
/close

**Comment by FaridHub** [comment]
Baremetal alone is not enough to extract and display hardware-profile. So, closing this issue.
