### ISSUE TITLE
Ironic is exhausting MySQL Connections

### ISSUE THREAD

**Issue by kplimack** [metal3-io/baremetal-operator#618]
Noticed that my mysql backup jobs were failing and the noticed that mysql connections are being exhausted.  If I restart the pod, it takes about 10 minutes for them to climb back up to nearly the limit.

Running `capm3-v0.4.0`

```bash
mysql -u ironic
ERROR 1040 (HY000): Too many connections

lsof -Pni | grep ESTABLISHED | wc -l
65
```

**Comment by dhellmann** [comment]
The BMO doesn't talk directly to the database. Only Ironic should be doing that.

Is there a configuration setting we can use in Ironic to manage that connection pool?

**Comment by elfosardo** [comment]
you could try setting max_pool_size
https://docs.openstack.org/ironic/latest/configuration/config.html#database.max_pool_size
kind of weird though, the default is 5 connections max
