### ISSUE TITLE
bmh status collection issue

### ISSUE THREAD

**Issue by shibaPuppy** [metal3-io/baremetal-operator#624]
pod restart delayed due to issue

It seems that the bmo pod is not collecting state again when it restarts.
There is a message in status.errorMessage, but the node is fine.

**Comment by dhellmann** [comment]
Could you provide more details about what happened? What is the message in `status.errorMessage`? Do you have logs for the baremetal-operator?

**Comment by shibaPuppy** [comment]
> Could you provide more details about what happened? What is the message in `status.errorMessage`? Do you have logs for the baremetal-operator?

[status.errorMessage](https://github.com/metal3-io/baremetal-operator/blob/master/pkg/apis/metal3/v1alpha1/baremetalhost_types.go#L540)

1. bmo pods restart
2. pod cannot start due to insufficient resources
```
Message:   The node was low on resource: ephemeral-storage. Container ironic was using 1214562664Ki, 
which exceeds its request of 0. Container ironic-endpoint-keepalived was using 76Ki, which exceeds its request of 0. 
Container ironic-dnsmasq was using 4066680Ki, which exceeds its request of 0. 
Container ironic-httpd was using 312Ki, which exceeds its request of 0. 
Container ironic-inspector was using 58676Ki, which exceeds its request of 0. Container mariadb was using 192560Ki, which exceeds its request of 0.

Message:   Pod The node had condition: [DiskPressure]
```
3. pod restart
4. bmo status re-collection
5. bmh nodes error
```
NAME     STATUS   PROVISIONING STATUS   CONSUMER   BMC                         HARDWARE PROFILE   ONLINE   ERROR
node-2   "~~"       provisioned                      ipmi://192.168.111.1:6232   unknown            true
node-3   OK       provisioned                      ipmi://192.168.111.1:6233   unknown            true
node-4   OK       provisioned                      ipmi://192.168.111.1:6234   unknown            true
```
- 
6. "~~~" - i can't remember what kind of message was there
