### ISSUE TITLE
how to disable auto_tls

### ISSUE THREAD

**Issue by TonyZhang1989** [metal3-io/baremetal-operator#724]
hi guys,
     i got this error  "sslv3 alert bad certificate" on centos8 ramdisk .
     so i consider to change enable_auto_tls=False
    what should i do ?

**Comment by dtantsur** [comment]
Hi! Disabling TLS is intentionally made hard, you need to rebuild the ironic-python-agent image. But actually, you need to check what goes wrong with TLS verification in your case, maybe you need to update your base OS or something like that.
