### ISSUE TITLE
Drac operation failed

### ISSUE THREAD

**Issue by mel1nn** [metal3-io/baremetal-operator#744]
Hi,
I want to provision a dell server (IDRAC 7, version 2.65.65.65), and before the Ironic inspection, an error occurs in the Ironic conductor: `dracclient.exceptions.DRACEmptyResponseField: Attribute 'CurrentAssignedSequence' is not nullable, but no value received`.

Thanks for your help !

**Comment by fmuyassarov** [comment]
/cc @dtantsur 
Can you please check it with Ironic community? Because, it seems related directly to Ironic.

**Comment by hardys** [comment]
It seems like there is something missing in the drac response which triggers this error:

https://opendev.org/openstack/python-dracclient/commit/ba1eb4aa99db7b78168ff2b0d19918924a0cb2aa

As mentioned this is probably something to investigate with the Ironic community via https://storyboard.openstack.org/#!/project/openstack/ironic - you'll need to include the ironic-conductor logs and details of the drac firmware version I expect, unless it's something that @dtantsur and other Ironic experts are familiar with.

**Comment by dtantsur** [comment]
Unfortunately, I'm not familiar with dracclient any more, you'll need to ask rpioso or ajya on #openstack-ironic IRC.

**Comment by rpioso** [comment]
@mel1nn, if possible, please share the exception's entire stack traceback from the ironic-conductor service log.

Thank you!

**Comment by mel1nn** [comment]
I made a new test today and I do not have the error anymore, great ! I saw that the ironic images were updated few days ago, so probably the error was patched.

Thanks for your help.
