### ISSUE TITLE
[Request] More frequent tag releases

### ISSUE THREAD

**Issue by s3rj1k** [metal3-io/baremetal-operator#746]
We need more frequent tag releases to ease vendoring efforts of community.

**Comment by s3rj1k** [comment]
@dhellmann @zaneb @maelk

**Comment by zaneb** [comment]
I support this.
I also have no idea how to do it.

**Comment by s3rj1k** [comment]
@zaneb just do git tag with proper version number (for go.mod support)

**Comment by honza** [comment]
The question I'd have is how often do we make releases? How do we decide when to cut one? Should we somehow track k8s releases? I guess we should also think about backwards compatibility, and what guarantees we want to stick to, etc.

**Comment by s3rj1k** [comment]
@honza My thoughts: 
 - release should be on every change of public function or change of known public behavior
 - no need to track k8s releases strictly if k8s release does not change any known behavior
 - proper vendoring is a way of providing guarantees when something major changes
 - would be nice to see some quick comments on release when some major breaking change happens

**Comment by zaneb** [comment]
I think it certainly makes sense to make a new release every time the CRD changes.

**Comment by s3rj1k** [comment]
@zaneb One other example when release should be planned is this type of change https://github.com/metal3-io/baremetal-operator/pull/741

It does not have to be just exactly for this change only, release could accumulate number of features.

But this PR certainly could break things for community.

**Comment by s3rj1k** [comment]
any news on this?

**Comment by s3rj1k** [comment]
/remove-lifecycle stale
still an issue, but after https://github.com/metal3-io/baremetal-operator/commit/f4865dbd25f288543513b1afb3f0e614070ad226
could we maybe tag API releases instead?

**Comment by honza** [comment]
Should we tag `v1.0.0` and see where that takes us?

**Comment by s3rj1k** [comment]
@honza I assume that 1.0.0 tag should be placed on matching commit hash with https://github.com/metal3-io/cluster-api-provider-metal3/releases/tag/v0.5.4

**Comment by honza** [comment]
On second thought, perhaps we shouldn't declare 1.0.0 while we're in alpha.

**Comment by dhellmann** [comment]
> On second thought, perhaps we shouldn't declare 1.0.0 while we're in alpha.

Indeed, I would expect to have a stable API version before a 1.0.0 declaration.

**Comment by furkatgofurov7** [comment]
> @honza I assume that 1.0.0 tag should be placed on matching commit hash with https://github.com/metal3-io/cluster-api-provider-metal3/releases/tag/v0.5.4

@s3rj1k yes you are right, the BMO tag is normally pushed after capm3 is released.
 i,e when capm3 v1.0.0 is released, BMO tag with v1.0.0 also needs to be pushed (https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/docs/releasing.md#create-a-new-tag-for-ironic-and-bmo-images).

**Comment by furkatgofurov7** [comment]
Also related to this, we had a discussion on slack some time ago asking everyone's opinion on this: https://kubernetes.slack.com/archives/CHD49TLE7/p1633610872156200 when we started efforts to uplift CAPM3 to v1beta1 API of CAPI, and the work on that almost finished. 

The release of CAPM3 with support of v1beta1 API does not exist yet, but we were planning internally to make one soon (which would be v1.0.0 CAPM3 most probably), meaning we would need to push the same tag for BMO+ironic. However, seems we do not want to go to v1.0.0 yet, AFAIU.

**Comment by s3rj1k** [comment]
@fmuyassarov someething like v0.5.4 will work also, as an starting point

**Comment by s3rj1k** [comment]
So now we have like 3 capm3-v1.1.x tagged releases, this is nice, but now there is an issue with missing tags for go.mod that are under the repo root, like one in the api folder.

ref: https://github.com/metal3-io/baremetal-operator/issues/1082

**Comment by furkatgofurov7** [comment]
Hi,

Do you think we can close this issue now, thoughts?

/cc @zaneb @honza @s3rj1k @Rozzii @dhellmann

**Comment by zaneb** [comment]
Yeah, I believe we can declare victory here.

**Comment by Rozzii** [comment]
yeah let's close it please.
