### ISSUE TITLE
Support BIOS setup for baremetal server

### ISSUE THREAD

**Issue by hase1128** [metal3-io/baremetal-operator#765]
I recreated this issue instead of #207 , because I took over this issue from @furukawa3

In order to setup/reset BIOS, vendor driver is necessary. This issue proposes a new yaml
attribute to setup BIOS with Fujitsu PRIMERGY server by using iRMC driver.

**Comment by hase1128** [comment]
This issue can be closed after #302 is merged.

**Comment by MahnoorAsghar** [comment]
> This issue can be closed after #302 is merged.
Shall we close this issue?
