### ISSUE TITLE
Kubectl field-selector does not work for some fields in BMH

### ISSUE THREAD

**Issue by s3rj1k** [metal3-io/baremetal-operator#779]
This does not work: ```kubectl get bmh --field-selector=spec.online=true``` and outputs:
```
Error from server (BadRequest): Unable to find "metal3.io/v1alpha1, Resource=baremetalhosts" that match label selector "", field selector "spec.online=true": field label not supported: spec.online
```

One would think that ```spec.*``` is not supported selector but this works (for pods): 
```kubectl get pods --field-selector=spec.restartPolicy=Always```

Seems that this is more of a k8s issue rather than operator, but still makes me wonder, can field selector support be some how extended to BMH?

**Comment by dhellmann** [comment]
I wonder if this is a difference in behavior between native types and CRDs?

Can you use `status.poweredOn` instead?

**Comment by s3rj1k** [comment]
@dhellmann 
```
Error from server (BadRequest): Unable to find "metal3.io/v1alpha1, Resource=baremetalhosts" that match label selector "", field selector "status.poweredOn=true": field label not supported: status.poweredOn
```
Also does not work

**Comment by s3rj1k** [comment]
```
kubectl get bmh --field-selector=status.bootMode=UEFI
Error from server (BadRequest): Unable to find "metal3.io/v1alpha1, Resource=baremetalhosts" that match label selector "", field selector "status.bootMode=UEFI": field label not supported: status.bootMode
```

does not work for strings :(

**Comment by fmuyassarov** [comment]
@s3rj1k I'm not sure if you can filter with any field. [Here](https://github.com/kubernetes/kubernetes/blob/35bf00acb1f5f2be22cdcb180c5e1227a72934fc/pkg/apis/core/v1/conversion.go#L33) is it seems `--field-selector` is limited to
```
				"metadata.namespace",
				"spec.nodeName",
				"spec.restartPolicy",
				"spec.schedulerName",
				"spec.serviceAccountName",
				"status.phase",
				"status.podIP",
				"status.podIPs",
				"status.nominatedNodeName":
``` 
and I think that's the same for CRD...

**Comment by fmuyassarov** [comment]
> @s3rj1k I'm not sure if you can filter with any field. [Here](https://github.com/kubernetes/kubernetes/blob/35bf00acb1f5f2be22cdcb180c5e1227a72934fc/pkg/apis/core/v1/conversion.go#L33) is it seems `--field-selector` is limited to
> 
> ```
> "metadata.namespace",
> "spec.nodeName",
> "spec.restartPolicy",
> "spec.schedulerName",
> "spec.serviceAccountName",
> "status.phase",
> "status.podIP",
> "status.podIPs",
> "status.nominatedNodeName":
> ```
> 
> and I think that's the same for CRD...

Sorry, not fully the same, because some fields might not exist in CRD.

**Comment by s3rj1k** [comment]
@fmuyassarov Thanks!

So this is indeed k8s issue, seems that `field-selector` code is useless in real world.

Was hoping using this as a selector in golang code.
