### ISSUE TITLE
 BMO should overwrite spec.online to false if inspector.conf has "power_off = true" after inspection

### ISSUE THREAD

**Issue by Lukasz-SendGrid** [metal3-io/baremetal-operator#790]
Something we've ran into, when setting this option in `inspector.conf` ran by the ironic-inspector container:

```
[processing]
power_off = true
```

when inspection is completed, the node is powered off, but the spec for the bmh doesn't change and `spec.online: true` is still set, so when bmo goes to perform it's power check every minute it will enforce what's in the spec thus turning the machine back on. A more consistent behavior might be that when the status of the bmh in question is changed it's online status should be set to false if that option is used. I don't know if this is something in the ironic database so might be hard to lookup, but even an option to power off the bmh after inspection in the bmo spec or in the bmh spec would be good as well. 

Thanks!

**Comment by dhellmann** [comment]
The Spec fields for the host are the source of truth for what the user has indicated they want. If you want the host offline after inspection, you can set `online: false` when you create the host without changing Ironic's configuration.

**Comment by Lukasz-SendGrid** [comment]
Works for me. Thank you for the quick response! Closing.
