### ISSUE TITLE
Resetting status.errorCount manualy? 

### ISSUE THREAD

**Issue by s3rj1k** [metal3-io/baremetal-operator#798]
Is there any way of re-setting `errorCount` manually inside bmh object?
Maybe using some kind of special annotation?

```
{"level":"info","ts":1613681703.0899441,"logger":"controllers.BareMetalHost","msg":"done","baremetalhost":"default/master-2","provisioningState":"deprovisioning","requeue":false,"after":18790.040866384}
```

Waiting for ~5h is a bit too much :)

Would you be willing to accept for review PR that add special annotation for clearing error count and message?

**Comment by andfasano** [comment]
The error count was meant to introduce an exponential backoff in case of error, so clearing out the message doesn't seem the correct thing to do to manage an erroneous situation: there should be an intervention (manual or automatic) to fix the problem, with a subsequent re-evaluation (reconcile) that will take care of clearing error if the right conditions are met. Can you please provide more details about you specific scenario? What kind of error? What did prevent the reconcile retriggering?

**Comment by s3rj1k** [comment]
@andfasano Image field on bmh object was incorrectly set in this particular case, this triggered multiple reconsiles and eventually a backoff.

I think that we need some kind of a backup plan to remove this errors without re-provisioning bmh.

**Comment by s3rj1k** [comment]
@andfasano Any ideas how to approach this?

**Comment by andfasano** [comment]
And fixing the Image field on the bmh object didn't retrigger the reconcile loop and cleared out the errorCount? If not, that's the issue to be fixed

**Comment by s3rj1k** [comment]
@andfasano no, to re-trigger I had to pause/resume reconcile via annotation, after that, successful de-provisioning cleared errorCount as expected.

**Comment by s3rj1k** [comment]
@andfasano So this happened again in different setup, stuck at backoff with no apparent way to trigger reconcile.

```
{"level":"info","ts":1615829787.7539394,"logger":"controllers.BareMetalHost","msg":"publishing event","baremetalhost":"worker-1","reason":"InspectionError","message":"No lookup attributes were found, inspector won't be able to find it after introspection, consider creating ironic ports or providing an IPMI address"}

{"level":"info","ts":1615829788.0157337,"logger":"controllers.BareMetalHost","msg":"done","baremetalhost":"worker-1","provisioningState":"inspecting","requeue":false,"after":11686.964158174}
```

This error happened because of ironic not providing free port to `worker-1` node, but this is different story, not related to this feature.

cc: @dhellmann 

Can we please consider implementing this in some way?

For additional notes, ironic error happened due to Ironic pod being unexpectedly restarted.
```
"error":"action \"registering\" failed: failed to validate BMC access: failed to create port in ironic: The service is currently unable to handle the request due to a temporary overloading or maintenance. This is a temporary condition. Try again later."
```

**Comment by andfasano** [comment]
> @andfasano no, to re-trigger I had to pause/resume reconcile via annotation, after that, successful de-provisioning cleared errorCount as expected.

I guess could make sense to have an explicit mechanism to force re-triggering a reconciliation loop for a specific BMH, considering that in some cases the remediation task could be an external (in respect to the resource) activity carried out by a user, but still wondering why amending the Image field didn't work, as it is a normal spec field?

**Comment by dhellmann** [comment]
> > @andfasano no, to re-trigger I had to pause/resume reconcile via annotation, after that, successful de-provisioning cleared errorCount as expected.
> 
> I guess could make sense to have an explicit mechanism to force re-triggering a reconciliation loop for a specific BMH, considering that in some cases the remediation task could be an external (in respect to the resource) activity carried out by a user, but still wondering why amending the Image field didn't work, as it is a normal spec field?

Any edit of the host resource should trigger reconciliation. If we want a less crude way to do it, we could add an annotation API to reset the value, but maybe it would be better to reduce the longest wait time that we use?

**Comment by s3rj1k** [comment]
@dhellmann 

>  maybe it would be better to reduce the longest wait time that we use

This would help to make this kind of issues to solve semiautomatic,

> If we want a less crude way to do it, we could add an annotation API to reset the value

but also this approach would greatly help with debugability

currently struggling with this long back-off blocking and unability to disable this during debuging.

**Comment by andfasano** [comment]
> we could add an annotation API to reset the value

I'm not very keen to such approach (if the intention it's to zero the value), as it will give the user the possibility to modify a field that it is managed by the operator - and usually the ErrorCount goes in pair with the ErrorMessage, so it wouldn't be enough to clear it.
I think that in such cases what it's required it's something like a "wake up" annotation that will set it to 1, forcing thus at the same time a re-evaluation of the current status without losing the current error condition

**Comment by dhellmann** [comment]
> > we could add an annotation API to reset the value
> 
> I'm not very keen to such approach (if the intention it's to zero the value), as it will give the user the possibility to modify a field that it is managed by the operator - and usually the ErrorCount goes in pair with the ErrorMessage, so it wouldn't be enough to clear it.
> I think that in such cases what it's required it's something like a "wake up" annotation that will set it to 1, forcing thus at the same time a re-evaluation of the current status without losing the current error condition

That makes sense. I was mostly pointing out that *any* edit to the host should trigger reconciliation, so we don't need a special API just to trigger a retry. If we wanted an API to let the user say "I think I have cleared the error on this host, try again" then an annotation would make sense instead of a spec field, because the controller could delete the annotation.

**Comment by s3rj1k** [comment]
@andfasano So how do we set ErrorCount to 1 ?

via annotation?

**Comment by andfasano** [comment]
The idea sounds fine to me, but I think we should prepare first a design proposal on https://github.com/metal3-io/metal3-docs to be discussed and approved by the community (I could prepare a draft tomorrow in case)

**Comment by s3rj1k** [comment]
@andfasano Would be great, thanks!

**Comment by zaneb** [comment]
@s3rj1k Please open a new bug and upload logs so we can figure out what the root cause is here.
As Andrea and Doug pointed out, modifying the BMH to fix the erroneous configuration will cause an immediate reconcile, and the fact that another reconcile is scheduled in 5 hours time is not relevant.

There is definitely work still to be done on retrying provisioning. When a bad image is set I believe we currently retry in a loop without incrementing error count past 1 (it goes from provisioning->deprovisioning->ready->provisioning with the successful deprovisioning clearing the error count). Ideally the error count should continue to increment as long as the image hasn't changed.

Clearly you are seeing something else, where the deprovisioning is failing repeatedly. That shouldn't happen if ironic is working and the BMC is reachable, so we need to look into it.

**Comment by s3rj1k** [comment]
@zaneb For the most part https://github.com/metal3-io/metal3-docs/pull/171 seems like a solution, let's keep this one open until that design doc is implemented.

If I encounter similar issue to this I will do another more specific issue with logs.

**Comment by zaneb** [comment]
No that is absolutely not a solution. In fact that the existence of such workarounds tends to prevent people from reporting obvious bugs is one reason not to implement them.

**Comment by s3rj1k** [comment]
@zaneb existence of such workaround help people fix issues in production clusters without recompiling code and not having new gray hair appearing.

Lets not forget that contributions to code works both ways, sometimes community just needs some workaround to solve current active problems without waiting for quite some time for a proper fix.

**Comment by zaneb** [comment]
After a lot of back-and-forth on metal3-io/metal3-docs#171 we have concluded that a retry can be triggered at any time by making any change to the BMH resource (e.g. add an annotation of your choice, not one recognised by the bmo), and we have no information to suggest that this mechanism would not work as intended when the underlying problem is fixed. Please open another bug if information comes to light suggesting otherwise.
/close
