### ISSUE TITLE
Set boot device for pxe boot

### ISSUE THREAD

**Issue by knfoo** [metal3-io/baremetal-operator#810]
When I am reading the api documentation, the reference does not describe the `bootMACAddress`, but it is used in the examples, this kind of confused my to believe that it was actually used to set the boot nic device.

IT seems that the documentation in the code states that it is only used for the libvirt vbmc integration.
https://github.com/metal3-io/baremetal-operator/blob/0e689212fe8cc2fa3c7d863a11ed4071f9359b55/apis/metal3.io/v1alpha1/baremetalhost_types.go#L310

The openstack cli has an option to set the boot device.
Would it be possible to do use the `bootMACAddress` for that ?
`openstack baremetal node boot device set`

**Comment by dhellmann** [comment]
The `bootMACAddress` value is used to link inspection data back to the node in Ironic, and therefore back to the host resource in metal3. Ideally it is the MAC of the NIC on which the host PXE boots, but I'm not sure that's a strict requirement as long as it is a real MAC from a NIC in the host.

**Comment by knfoo** [comment]
OK that makes sense.
It would be really cool if it was also used to configure the host to PXE boot from that mac.
And even be able to set if it should be IPv4 or IPv6.

**Comment by dtantsur** [comment]
> It would be really cool if it was also used to configure the host to PXE boot from that mac.
> And even be able to set if it should be IPv4 or IPv6.

To my best knowledge, IPMI does not provide this ability. Redfish does (on some systems), but in a vendor-specific way (through BIOS settings or UEFI boot order, which are not standardized).

**Comment by knfoo** [comment]
OK, I guess it is just a wish then.
Thank you for the information.
