### ISSUE TITLE
RAM parameter and value are absent in Node Introspection Data (using redfish) 

### ISSUE THREAD

**Issue by sumitjadhav1** [metal3-io/baremetal-operator#818]
After performing introspection from baremetal operator using redfish driver, all the required introspection data is populated in the Baremetal host CR.

But RAM parameters are absent in this data. This was working earlier, seems some recent changes have broken this functionality. 

This causes regression issue in HWCC, Here is the snippet :

![RAM-Comparison-Failure](https://user-images.githubusercontent.com/48747693/111607397-3543a280-87fe-11eb-9cd5-d405dbde6463.png)

Issue is easily reproducible in metal-dev-env setup with vBMC nodes.
@digambar15 @Ashughorla @ravipwaghmare @fmuyassarov @dtantsur @poonampawar28

**Comment by fmuyassarov** [comment]
I remember seeing `status.hardware.ramMebibytes` previously in bmh manifests. I don't know what has changed but I also don't see it in the bmh manifests saved from the [integration CI run](https://jenkins.nordix.org/view/Airship/job/airship_master_v1a4_integration_test_ubuntu/).

**Comment by sumitjadhav1** [comment]
Attaching Ironic-Inspector, Ironic-Conductor, BMO logs for reference. 
In Ironic-conductor log, we see "size_gib" as 4, whereas in inspector/bmo logs "physical_mb" is seen 0.

@dtantsur Please take a look and let us know if any additional info required.

[bmo.log](https://github.com/metal3-io/baremetal-operator/files/6309997/bmo.log)
[ironic-conductor.log](https://github.com/metal3-io/baremetal-operator/files/6309998/ironic-conductor.log)
[ironic-inspector.log](https://github.com/metal3-io/baremetal-operator/files/6310000/ironic-inspector.log)

**Comment by dtantsur** [comment]
You'll also need ramdisk logs, `physical_mb` is coming from `dmidecode` output.

And note that `size_gib` is likely about the hard drive, not RAM.

**Comment by sumitjadhav1** [comment]
Ironic-inspector log snippet, will this suffice for ramdisk logs as I don't see any ramdisk log present in /var/log/ironic-inspector/ramdisk/ [_If something fails during the introspection ramdisk run, ironic-inspector stores the ramdisk logs in /var/log/ironic-inspector/ramdisk/ as gz-compressed tar files_] : `2021-04-14 07:26:39.436 1 DEBUG ironic_inspector.main [req-28e6ee9b-f9ed-4f9a-a498-a637cf1c365c - - - - -] [node: MAC 00:c7:3d:e0:d6:e0] Received data from the ramdisk: {'inventory': {'interfaces': [{'name': 'enp2s0', 'mac_address': '00:c7:3d:e0:d6:e2', 'ipv4_address': '192.168.111.21', 'ipv6_address': 'fe80::9611:6b33:c1e0:46f2%enp2s0', 'has_carrier': True, 'lldp': [], 'vendor': '0x1af4', 'product': '0x0001', 'client_id': None, 'biosdevname': None}, {'name': 'enp1s0', 'mac_address': '00:c7:3d:e0:d6:e0', 'ipv4_address': '172.22.0.72', 'ipv6_address': 'fe80::a096:4b03:4c58:cd80%enp1s0', 'has_carrier': True, 'lldp': [], 'vendor': '0x1af4', 'product': '0x0001', 'client_id': None, 'biosdevname': None}], 'cpu': {'model_name': 'Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz', 'frequency': '2400.010', 'count': 2, 'architecture': 'x86_64', 'flags': ['fpu', 'vme', 'de', 'pse', 'tsc', 'msr', 'pae', 'mce', 'cx8', 'apic', 'sep', 'mtrr', 'pge', 'mca', 'cmov', 'pat', 'pse36', 'clflush', 'mmx', 'fxsr', 'sse', 'sse2', 'ss', 'syscall', 'nx', 'rdtscp', 'lm', 'constant_tsc', 'arch_perfmon', 'rep_good', 'nopl', 'xtopology', 'cpuid', 'tsc_known_freq', 'pni', 'pclmulqdq', 'vmx', 'ssse3', 'cx16', 'pcid', 'sse4_1', 'sse4_2', 'x2apic', 'popcnt', 'tsc_deadline_timer', 'aes', 'xsave', 'avx', 'f16c', 'rdrand', 'hypervisor', 'lahf_lm', 'cpuid_fault', 'pti', 'ibrs', 'ibpb', 'tpr_shadow', 'vnmi', 'ept', 'vpid', 'fsgsbase', 'tsc_adjust', 'smep', 'arat', 'umip', 'arch_capabilities']}, 'disks': [{'name': '/dev/sda', 'model': 'QEMU HARDDISK', 'size': 53687091200, 'rotational': True, 'wwn': None, 'serial': 'drive-scsi0-0-0-0', 'vendor': 'QEMU', 'wwn_with_extension': None, 'wwn_vendor_extension': None, 'hctl': '0:0:0:0', 'by_path': '/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0'}], 'memory': {'total': 4120039424, 'physical_mb': 0}, 'bmc_address': '0.0.0.0', 'bmc_v6address': '::/0', 'system_vendor': {'product_name': 'Standard PC (Q35 + ICH9, 2009)', 'serial_number': '', 'manufacturer': 'QEMU'}, 'boot': {'current_boot_mode': 'bios', 'pxe_interface': '00:c7:3d:e0:d6:e0'}, 'hostname': 'node-1'}, 'root_disk': {'name': '/dev/sda', 'model': 'QEMU HARDDISK', 'size': 53687091200, 'rotational': True, 'wwn': None, 'serial': 'drive-scsi0-0-0-0', 'vendor': 'QEMU', 'wwn_with_extension': None, 'wwn_vendor_extension': None, 'hctl': '0:0:0:0', 'by_path': '/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0'}, 'boot_interface': '00:c7:3d:e0:d6:e0', 'configuration': {'collectors': ['default', 'extra-hardware', 'logs'], 'managers': [{'name': 'generic_hardware_manager', 'version': '1.1'}]}, 'data': [['disk', 'logical', 'count', '1'], ['disk', 'sda', 'size', '53'], ['disk', 'sda', 'vendor', 'QEMU'], ['disk', 'sda', 'model', 'QEMU HARDDISK'], ['disk', 'sda', 'rev', '2.5+'], ['disk', 'sda', 'optimal_io_size', '0'], ['disk', 'sda', 'physical_block_size', '512'], ['disk', 'sda', 'rotational', '1'], ['disk', 'sda', 'nr_requests', '256'], ['disk', 'sda', 'scheduler', 'mq-deadline'], ['disk', 'sda', 'Write Cache Enable', '1'], ['disk', 'sda', 'Read Cache Disable', '0'], ['disk', 'sda', 'scsi-id', 'scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-0-0'], ['disk', 'sda', 'SMART/vendor', 'QEMU'], ['disk', 'sda', 'SMART/product', 'QEMU HARDDISK'], ['system', 'product', 'name', 'Standard PC (Q35 + ICH9, 2009)'], ['system', 'product', 'vendor', 'QEMU'], ['system', 'product', 'version', 'pc-q35-2.11'], ['system', 'product', 'uuid', '266ab48a-5532-41fb-9435-b536b4a1c299'], ['firmware', 'bios', 'version', '1.10.2-1ubuntu1'], ['firmware', 'bios', 'date', '04/01/2014'], ['firmware', 'bios', 'vendor', 'SeaBIOS'], ['memory', 'total', 'size', '4294967296'], ['network', 'enp1s0', 'businfo', 'virtio@0'], ['network', 'enp1s0', 'ipv4', '172.22.0.72'], ['network', 'enp1s0', 'ipv4-netmask', '255.255.255.0'], ['network', 'enp1s0', 'ipv4-cidr', '24'], ['network', 'enp1s0', 'ipv4-network', '172.22.0.0'], ['network', 'enp1s0', 'link', 'yes'], ['network', 'enp1s0', 'driver', 'virtio_net'], ['network', 'enp1s0', 'autonegotiation', 'off'], ['network', 'enp1s0', 'serial', '00:c7:3d:e0:d6:e0'], ['network', 'enp1s0', 'rx-checksumming', 'on [fixed]'], ['network', 'enp1s0', 'tx-checksumming', 'on'], ['network', 'enp1s0', 'tx-checksumming/tx-checksum-ipv4', 'off [fixed]'], ['network', 'enp1s0', 'tx-checksumming/tx-checksum-ip-generic', 'on'], ['network', 'enp1s0', 'tx-checksumming/tx-checksum-ipv6', 'off [fixed]'], ['network', 'enp1s0', 'tx-checksumming/tx-checksum-fcoe-crc', 'off [fixed]'], ['network', 'enp1s0', 'tx-checksumming/tx-checksum-sctp', 'off [fixed]'], ['network', 'enp1s0', 'scatter-gather', 'on'], ['network', 'enp1s0', 'scatter-gather/tx-scatter-gather', 'on'], ['network', 'enp1s0', 'scatter-gather/tx-scatter-gather-fraglist', 'off [fixed]'], ['network', 'enp1s0', 'tcp-segmentation-offload', 'on'], ['network', 'enp1s0', 'tcp-segmentation-offload/tx-tcp-segmentation', 'on'], ['network', 'enp1s0', 'tcp-segmentation-offload/tx-tcp-ecn-segmentation', 'on'], ['network', 'enp1s0', 'tcp-segmentation-offload/tx-tcp-mangleid-segmentation', 'off'], ['network', 'enp1s0', 'tcp-segmentation-offload/tx-tcp6-segmentation', 'on'], ['network', 'enp1s0', 'generic-segmentation-offload', 'on'], ['network', 'enp1s0', 'generic-receive-offload', 'on'], ['network', 'enp1s0', 'large-receive-offload', 'off [fixed]'], ['network', 'enp1s0', 'rx-vlan-offload', 'off [fixed]'], ['network', 'enp1s0', 'tx-vlan-offload', 'off [fixed]'], ['network', 'enp1s0', 'ntuple-filters', 'off [fixed]'], ['network', 'enp1s0', 'receive-hashing', 'off [fixed]'], ['network', 'enp1s0', 'highdma', 'on [fixed]'], ['network', 'enp1s0', 'rx-vlan-filter', 'on [fixed]'], ['network', 'enp1s0', 'vlan-challenged', 'off [fixed]'], ['network', 'enp1s0', 'tx-lockless', 'off [fixed]'], ['network', 'enp1s0', 'netns-local', 'off [fixed]'], ['network', 'enp1s0', 'tx-gso-robust', 'on [fixed]'], ['network', 'enp1s0', 'tx-fcoe-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-gre-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-gre-csum-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-ipxip4-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-ipxip6-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-udp_tnl-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-udp_tnl-csum-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-gso-partial', 'off [fixed]'], ['network', 'enp1s0', 'tx-tunnel-remcsum-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-sctp-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-esp-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-udp-segmentation', 'off [fixed]'], ['network', 'enp1s0', 'tx-gso-list', 'off [fixed]'], ['network', 'enp1s0', 'rx-gro-list', 'off'], ['network', 'enp1s0', 'tls-hw-rx-offload', 'off [fixed]'], ['network', 'enp1s0', 'fcoe-mtu', 'off [fixed]'], ['network', 'enp1s0', 'tx-nocache-copy', 'off'], ['network', 'enp1s0', 'loopback', 'off [fixed]'], ['network', 'enp1s0', 'rx-fcs', 'off [fixed]'], ['network', 'enp1s0', 'rx-all', 'off [fixed]'], ['network', 'enp1s0', 'tx-vlan-stag-hw-insert', 'off [fixed]'], ['network', 'enp1s0', 'rx-vlan-stag-hw-parse', 'off [fixed]'], ['network', 'enp1s0', 'rx-vlan-stag-filter', 'off [fixed]'], ['network', 'enp1s0', 'l2-fwd-offload', 'off [fixed]'], ['network', 'enp1s0', 'hw-tc-offload', 'off [fixed]'], ['network', 'enp1s0', 'esp-hw-offload', 'off [fixed]'], ['network', 'enp1s0', 'esp-tx-csum-hw-offload', 'off [fixed]'], ['network', 'enp1s0', 'rx-udp_tunnel-port-offload', 'off [fixed]'], ['network', 'enp1s0', 'tls-hw-tx-offload', 'off [fixed]'], ['network', 'enp1s0', 'rx-gro-hw', 'off [fixed]'], ['network', 'enp1s0', 'tls-hw-record', 'off [fixed]'], ['network', 'enp2s0', 'businfo', 'virtio@1'], ['network', 'enp2s0', 'ipv4', '192.168.111.21'], ['network', 'enp2s0', 'ipv4-netmask', '255.255.255.0'], ['network', 'enp2s0', 'ipv4-cidr', '24'], ['network', 'enp2s0', 'ipv4-network', '192.168.111.0'], ['network', 'enp2s0', 'link', 'yes'], ['network', 'enp2s0', 'driver', 'virtio_net'], ['network', 'enp2s0', 'autonegotiation', 'off'], ['network', 'enp2s0', 'serial', '00:c7:3d:e0:d6:e2'], ['network', 'enp2s0', 'rx-checksumming', 'on [fixed]'], ['network', 'enp2s0', 'tx-checksumming', 'on'], ['network', 'enp2s0', 'tx-checksumming/tx-checksum-ipv4', 'off [fixed]'], ['network', 'enp2s0', 'tx-checksumming/tx-checksum-ip-generic', 'on'], ['network', 'enp2s0', 'tx-checksumming/tx-checksum-ipv6', 'off [fixed]'], ['network', 'enp2s0', 'tx-checksumming/tx-checksum-fcoe-crc', 'off [fixed]'], ['network', 'enp2s0', 'tx-checksumming/tx-checksum-sctp', 'off [fixed]'], ['network', 'enp2s0', 'scatter-gather', 'on'], ['network', 'enp2s0', 'scatter-gather/tx-scatter-gather', 'on'], ['network', 'enp2s0', 'scatter-gather/tx-scatter-gather-fraglist', 'off [fixed]'], ['network', 'enp2s0', 'tcp-segmentation-offload', 'on'], ['network', 'enp2s0', 'tcp-segmentation-offload/tx-tcp-segmentation', 'on'], ['network', 'enp2s0', 'tcp-segmentation-offload/tx-tcp-ecn-segmentation', 'on'], ['network', 'enp2s0', 'tcp-segmentation-offload/tx-tcp-mangleid-segmentation', 'off'], ['network', 'enp2s0', 'tcp-segmentation-offload/tx-tcp6-segmentation', 'on'], ['network', 'enp2s0', 'generic-segmentation-offload', 'on'], ['network', 'enp2s0', 'generic-receive-offload', 'on'], ['network', 'enp2s0', 'large-receive-offload', 'off [fixed]'], ['network', 'enp2s0', 'rx-vlan-offload', 'off [fixed]'], ['network', 'enp2s0', 'tx-vlan-offload', 'off [fixed]'], ['network', 'enp2s0', 'ntuple-filters', 'off [fixed]'], ['network', 'enp2s0', 'receive-hashing', 'off [fixed]'], ['network', 'enp2s0', 'highdma', 'on [fixed]'], ['network', 'enp2s0', 'rx-vlan-filter', 'on [fixed]'], ['network', 'enp2s0', 'vlan-challenged', 'off [fixed]'], ['network', 'enp2s0', 'tx-lockless', 'off [fixed]'], ['network', 'enp2s0', 'netns-local', 'off [fixed]'], ['network', 'enp2s0', 'tx-gso-robust', 'on [fixed]'], ['network', 'enp2s0', 'tx-fcoe-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-gre-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-gre-csum-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-ipxip4-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-ipxip6-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-udp_tnl-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-udp_tnl-csum-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-gso-partial', 'off [fixed]'], ['network', 'enp2s0', 'tx-tunnel-remcsum-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-sctp-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-esp-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-udp-segmentation', 'off [fixed]'], ['network', 'enp2s0', 'tx-gso-list', 'off [fixed]'], ['network', 'enp2s0', 'rx-gro-list', 'off'], ['network', 'enp2s0', 'tls-hw-rx-offload', 'off [fixed]'], ['network', 'enp2s0', 'fcoe-mtu', 'off [fixed]'], ['network', 'enp2s0', 'tx-nocache-copy', 'off'], ['network', 'enp2s0', 'loopback', 'off [fixed]'], ['network', 'enp2s0', 'rx-fcs', 'off [fixed]'], ['network', 'enp2s0', 'rx-all', 'off [fixed]'], ['network', 'enp2s0', 'tx-vlan-stag-hw-insert', 'off [fixed]'], ['network', 'enp2s0', 'rx-vlan-stag-hw-parse', 'off [fixed]'], ['network', 'enp2s0', 'rx-vlan-stag-filter', 'off [fixed]'], ['network', 'enp2s0', 'l2-fwd-offload', 'off [fixed]'], ['network', 'enp2s0', 'hw-tc-offload', 'off [fixed]'], ['network', 'enp2s0', 'esp-hw-offload', 'off [fixed]'], ['network', 'enp2s0', 'esp-tx-csum-hw-offload', 'off [fixed]'], ['network', 'enp2s0', 'rx-udp_tunnel-port-offload', 'off [fixed]'], ['network', 'enp2s0', 'tls-hw-tx-offload', 'off [fixed]'], ['network', 'enp2s0', 'rx-gro-hw', 'off [fixed]'], ['network', 'enp2s0', 'tls-hw-record', 'off [fixed]'], ['cpu', 'physical', 'number', 2], ['cpu', 'physical', 'smt', 'notsupported'], ['cpu', 'physical_0', 'vendor', 'GenuineIntel'], ['cpu', 'physical_0', 'product', 'Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz'], ['cpu', 'physical_0', 'cores', 1], ['cpu', 'physical_0', 'threads', 1], ['cpu', 'physical_0', 'family', 6], ['cpu', 'physical_0', 'model', 62], ['cpu', 'physical_0', 'stepping', 4], ['cpu', 'physical_0', 'architecture', 'x86_64'], ['cpu', 'physical_0', 'l1d cache', '32K'], ['cpu', 'physical_0', 'l1i cache', '32K'], ['cpu', 'physical_0', 'l2 cache', '4096K'], ['cpu', 'physical_0', 'l3 cache', '16384K'], ['cpu', 'physical_0', 'current_Mhz', 2400.01], ['cpu', 'physical_0', 'flags', 'fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti ibrs ibpb tpr_shadow vnmi ept vpid fsgsbase tsc_adjust smep arat umip arch_capabilities'], ['cpu', 'physical_0', 'threads_per_core', 1], ['cpu', 'physical_1', 'vendor', 'GenuineIntel'], ['cpu', 'physical_1', 'product', 'Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz'], ['cpu', 'physical_1', 'cores', 1], ['cpu', 'physical_1', 'threads', 1], ['cpu', 'physical_1', 'family', 6], ['cpu', 'physical_1', 'model', 62], ['cpu', 'physical_1', 'stepping', 4], ['cpu', 'physical_1', 'architecture', 'x86_64'], ['cpu', 'physical_1', 'l1d cache', '32K'], ['cpu', 'physical_1', 'l1i cache', '32K'], ['cpu', 'physical_1', 'l2 cache', '4096K'], ['cpu', 'physical_1', 'l3 cache', '16384K'], ['cpu', 'physical_1', 'current_Mhz', 2400.01], ['cpu', 'physical_1', 'flags', 'fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cpuid_fault pti ibrs ibpb tpr_shadow vnmi ept vpid fsgsbase tsc_adjust smep arat umip arch_capabilities'], ['cpu', 'physical_1', 'threads_per_core', 1], ['cpu', 'logical', 'number', 2], ['numa', 'nodes', 'count', 1], ['numa', 'node_0', 'cpu_count', 2], ['numa', 'node_0', 'cpu_mask', '3'], ['system', 'kernel', 'version', '4.18.0-294.el8.x86_64'], ['system', 'kernel', 'arch', 'x86_64'], ['system', 'kernel', 'cmdline', 'selinux=0 troubleshoot=0 text nofb nomodeset vga=normal ipa-insecure=1 console=ttyS0 ipa-debug=1 ipa-insecure=1 ipa-inspection-collectors=default,extra-hardware,logs ipa-enable-vlan-interfaces=all ipa-inspection-dhcp-all-interfaces=1 ipa-collect-lldp=1 ipa-api-url=https://172.22.0.2:6385 console=ttyS0 ipa-inspection-callback-url=https://172.22.0.2:5050/v1/continue ipa-global-request-id=req-b1cb3d34-7f3c-4abd-9a7e-020f373b4c71 BOOTIF=00:c7:3d:e0:d6:e0 initrd=deploy_ramdisk'], ['system', 'rtc', 'utc', 'no'], ['hw', 'auxv', 'hwcap', 'f8bfbff'], ['hw', 'auxv', 'pagesz', '4096'], ['hw', 'auxv', 'flags', '0x0'], ['hw', 'auxv', 'hwcap2', '0x2'], ['hw', 'auxv', 'platform', 'x86_64']], 'logs': '<hidden>', 'error': None} api_continue /usr/lib/python3.6/site-packages/ironic_inspector/main.py:339`

**Comment by zaneb** [comment]
The interesting parts of the inspection data from the bmo logs:

```yaml
extra:
  memory:
    total:
      size: 4294967296
  numa:
    node_0:
      cpu_count: 2
      cpu_mask: 3
    nodes:
      count: 1
inventory:
  memory:
    physical_mb: 0
    total: 4120039424
memory_mb: 0
```

We use the top-level [`memory_mb`](https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/hardwaredetails/hardwaredetails.go#L19). So it looks like the problem is in IPA somewhere.

**Comment by sumitjadhav1** [comment]
Thank @zaneb for your analysis. Can we take this up for resolution ? Since it's a regression issue.

**Comment by dtantsur** [comment]
We need ramdisk logs, I cannot understand anything from the resulting data only.

**Comment by dtantsur** [comment]
I think nowadays ramdisk logs are published as podman logs from a separate container and removed from `/var/log/ironic-inspector/ramdisk` after that. Please check it.

**Comment by zaneb** [comment]
https://opendev.org/openstack/ironic-python-agent/commit/448ded43fe1cfea9247dbd5612715124e5abbb55 looks potentially related.
See https://storyboard.openstack.org/#!/story/2007588.

In any event not a baremetal-operator issue, so...
/close

**Comment by sumitjadhav1** [comment]
Attaching ramdisk logs as per requested in community meeting, please check node-19 (886bd373-d5fa-4c09-a103-c548a260df2f) in file, reopening till we get some guidance on this.

@dtantsur PTAL

[ramdisk-logs-Real-Node-Setup.txt](https://github.com/metal3-io/baremetal-operator/files/6392828/ramdisk-logs-Real-Node-Setup.txt)

**Comment by zaneb** [comment]
I opened https://storyboard.openstack.org/#!/story/2008865 to track this.

**Comment by zaneb** [comment]
This was broken by lyonel/lshw#60.

I submitted a fix at lyonel/lshw#65, and a workaround in IPA at https://review.opendev.org/c/openstack/ironic-python-agent/+/788588

**Comment by sumitjadhav1** [comment]
@dtantsur @zaneb @bfournie @elfosardo @fmuyassarov Please share the IPA images to be used for verifying this fix. Thanks in advance.

**Comment by dtantsur** [comment]
You can try the centos8-master images from https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ for testing

**Comment by sumitjadhav1** [comment]
> 
> 
> You can try the centos8-master images from https://tarballs.opendev.org/openstack/ironic-python-agent/dib/files/ for testing

I tested the same, we do see RAM updated now but also received ramdisk error in ironic-inspector log which says : 

`.0-ata-1'}, 'boot_interface': '24:6e:96:53:10:e4', 'configuration': {'collectors': ['default', 'extra-hardware', 'logs'], 'managers': [{'name': 'IntelCnaHardwareManager', 'version': '1.0'}, {'name': 'generic_hardware_manager', 'version': '1.1'}]}, 'logs': '<hidden>', 'error': "The following errors were encountered:\n* failed to run hardware-detect utility: [Errno 2] No such file or directory: 'hardware-detect': 'hardware-detect'"} api_continue /usr/lib/python3.6/site-packages/ironic_inspector/main.py:339
2021-05-07 15:04:11.939 1 DEBUG ironic_inspector.process [-] [node: MAC 24:6e:96:53:10:e4 BMC 192.168.110.19] Running pre-processing hook ramdisk_error _run_pre_hooks /usr/lib/python3.6/site-packages/ironic_inspector/process.py:129
2021-05-07 15:04:11.940 1 ERROR ironic_inspector.utils [-] [node: MAC 24:6e:96:53:10:e4 BMC 192.168.110.19] Ramdisk reported error: The following errors were encountered:
* failed to run hardware-detect utility: [Errno 2] No such file or directory: 'hardware-detect': 'hardware-detect'
2021-05-07 15:04:11.940 1 ERROR ironic_inspector.process [-] [node: MAC 24:6e:96:53:10:e4 BMC 192.168.110.19] Hook ramdisk_error failed, delaying error report until node look up: Ramdisk reported error: The following errors were encountered:
* failed to run hardware-detect utility: [Errno 2] No such file or directory: 'hardware-detect': 'hardware-detect': ironic_inspector.utils.Error: Ramdisk reported error: The following errors were encountered:
`

The introspection fails for baremetal node as seen in openstack CLI as well : 

`node-48@node48-PowerEdge-R640:~$ openstack baremetal node list
+--------------------------------------+----------------+---------------+-------------+--------------------+-------------+
| UUID                                 | Name           | Instance UUID | Power State | Provisioning State | Maintenance |
+--------------------------------------+----------------+---------------+-------------+--------------------+-------------+
| 5f24e239-af3d-48a9-a3e1-ab51fb26a9fe | metal3~node-1  | None          | power on    | manageable         | False       |
| ddbf7fbe-9e9b-45cf-900b-7e9cc7233b5b | **metal3~node-19** | None          | power on    | **inspect failed**     | False       |
+--------------------------------------+----------------+---------------+-------------+--------------------+-------------+
`

**Comment by bfournie** [comment]
The ironic-python-agent rpm at current-tripleo should now have this fix - https://trunk.rdoproject.org/centos8-master/component/baremetal/current-tripleo/. It has hash 4ac3d79 which is the latest fix from May 4, see https://github.com/openstack/ironic-python-agent/commits/master.

**Comment by sumitjadhav1** [comment]
Able to observe RAM parameter back, please refer the attached logs for reference.

[Verification-RAM-Parameter.txt](https://github.com/metal3-io/baremetal-operator/files/6531831/Verification-RAM-Parameter.txt)

Thanks
