### ISSUE TITLE
Power management errors are never reported

### ISSUE THREAD

**Issue by zaneb** [metal3-io/baremetal-operator#828]
The `PowerOn()` and `PowerOff()` method of the ironic Provisioner never return an ErrorMessage, so despite a considerable amount of accounting that is in place for power management errors, none will ever be reported. If changing the power state fails (i.e. ironic accepts our request but is unable to carry it out) we just keep silently trying forever.

To resolve this we will need to implement checking of the LastError field from ironic, along with a force flag as used by other methods such as Adopt() (see #749).

A complication is that after a soft power off failure, we want to attempt a hard power off without flagging an error. However, there's no way to tell if a failed attempt we detect was a soft or hard power off attempt. (Note that the current code flow is unnecessarily confusing: if we start a hard power off then we end up checking on its progress by calling softPowerOff(), even though that is off the table. This code should probably be refactored so that checking the state is common.) A solution would be to say that we will only attempt a soft power off on the first attempt; if it fails we will flag a power management error and once ErrorCount > 0 we will only ever force a hard power off.

**Comment by dtantsur** [comment]
> after a soft power off failure, we want to attempt a hard power off without flagging an error

This sounds like something we could implement in ironic.

**Comment by zaneb** [comment]
> > after a soft power off failure, we want to attempt a hard power off without flagging an error
> 
> This sounds like something we could implement in ironic.

+1, I doubt metal³ is the only potential consumer of that.

**Comment by sadasu** [comment]
> > > after a soft power off failure, we want to attempt a hard power off without flagging an error
> > 
> > 
> > This sounds like something we could implement in ironic.
> 
> +1, I doubt metal³ is the only potential consumer of that.

I would think that each controller needs to make the decision for itself to proceed to the remedial action (in this case a hard power off) when soft power off isn't succeeding.
