### ISSUE TITLE
Image update in ironic on re-registration is fragile

### ISSUE THREAD

**Issue by zaneb** [metal3-io/baremetal-operator#839]
Updating the image data during registration using `getImageUpdateOptsForNode()` happens only if the node doesn't exist. This is a bug, because if writing the image data it fails then we will never try it again so long as the node exist.

Without data we cannot adopt, so if this occurred we would be stuck in a permanent error loop if the host is in the Provisioned/Deprovisioning states.

_Originally identified in https://github.com/metal3-io/baremetal-operator/pull/784#discussion_r604217324_

**Comment by fmuyassarov** [comment]
Do we need to add a retry ?
/kind bug

**Comment by zaneb** [comment]
It retries fine, but on the retry the Node will already exist in Ironic. The image setting are currently only written in the path where the Node didn't exist and we had to recreate it. They should be written unconditionally, whether the node already existed or not.
