### ISSUE TITLE
Redfish-virtualmedia configuration

### ISSUE THREAD

**Issue by egarzuel** [metal3-io/baremetal-operator#896]
Hello,

One question related to redfish and redfish-virtualmedia, not sure if it’s a bug or an issue with my config file.
Currently I tried to perform hardware inspection by metal3, which is ok (node is in ready state) if under BMC section I’m using this address :
   _address: redfish://10.10.3.10/redfish/v1/Systems/1_
   
But, If I’m using address with redfish-virtualmedia, ironic is not able to get the power status :
    _address: redfish-virtualmedia://10.10.3.10/redfish/v1/Managers/1_
**Events :
Normal  RegistrationError  2m51s  metal3-baremetal-controller  Failed to get power state for node 7fc12e46-784b-4cb1-a965-f3d28 │
│ a00d437. Error: The attribute Boot is missing from the resource /redfish/v1/Managers/1**

If I’m correct, my understanding is for IPMI management (power status, boot option, reset…), we must be under _/redfish/v1/Systems/1_. But for virtualmedia management, we must be under _/redfish/v1/Managers/1…_
Question, how I can config to use both address depending on the ironic step (IPMI management versus virtualmanagment) ? 
Thanks.

**Comment by dtantsur** [comment]
> But for virtualmedia management, we must be under /redfish/v1/Managers/1

This is not correct. Where did you get this information? You should use systems in both cases.

**Comment by egarzuel** [comment]
Hi,
Thanks for your reply. We also use Systems with redfish-virtual media, unfortunately it doesn't work. I will logs to post here.

Regards.

**Comment by egarzuel** [comment]
For information, I'm working on SuperMicro server, and redfish implementation seems not correct :
https://storyboard.openstack.org/#!/story/2008370

I will check under this way.

Regards.

**Comment by egarzuel** [comment]
Redfish release not correct on SuperMicro (even if latest firmware are installed) . I'm checking to see if we can upgrade.
