### ISSUE TITLE
BMO changes for CAPM3 v1alpha5

### ISSUE THREAD

**Issue by jan-est** [metal3-io/baremetal-operator#919]
@andfasano @dhellmann Cluster API will be releasing v1alpha4 api soon and CAPM3 will follow those changes by releasing new v1alpha5 api. We need some of [these changes](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md) in BMO to be able to deploy it as part of the CAPM3. 

At least we need to follow:
- Align manager flag names with upstream Kubernetes components
- And follow some kustomization changes mentioned in CAPI document

Our plan is to keep full backward compatibility with flags in BMO and for kustomization we would thinking to have separate kustomization in place for CAPM3 v1alpha4 and v1alpha5. Any thought of that?

Any ideas, concerns or point that needs to take to account when making changes in BMO to fit to upcoming CAPM3 changes?

**Comment by kashifest** [comment]
@jan-est can you elaborate the changes in bit more detail probably copy paste those parts from CAPI change doc so that the required changes in BMO is visible.

**Comment by jan-est** [comment]
@kashifest @dhellmann @andfasano 
We would like to to have this implemented [Align manager flag names with upstream Kubernetes components](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md#align-manager-flag-names-with-upstream-kubernetes-components)

We may need some, not all changes from [Required kustomize changes to have a single manager watching all namespaces and answer to webhook calls](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md#required-kustomize-changes-to-have-a-single-manager-watching-all-namespaces-and-answer-to-webhook-calls) Since BMO does not use webhooks we don't need to be worried about webhook related customization.

**Comment by jan-est** [comment]
Have we ever consider to have releases and versioning in BMO? In the long run changes like above would make more sense to make within new API and release. Or what do you think?

**Comment by dhellmann** [comment]
> @kashifest @dhellmann @andfasano
> We would like to have this implemented [Align manager flag names with upstream Kubernetes components](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md#align-manager-flag-names-with-upstream-kubernetes-components)

That seems reasonable. It would be nice to keep the old names for backwards compatibility.

> We may need some, not all changes from [Required kustomize changes to have a single manager watching all namespaces and answer to webhook calls](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md#required-kustomize-changes-to-have-a-single-manager-watching-all-namespaces-and-answer-to-webhook-calls) Since BMO does not use webhooks we don't need to be worried about webhook related customization.

Perhaps we should start thinking about creating an operator to manage our deployment(s). Is that what they mean by "a single deployment manager"?

**Comment by dhellmann** [comment]
> Have we ever consider to have releases and versioning in BMO? In the long run changes like above would make more sense to make within new release. Or what do you think?

We have discussed it, and there was no opposition, but I don't think we've encountered anything yet that forced us to do it so no one has taken the time.

**Comment by andfasano** [comment]
> Since BMO does not use webhooks we don't need to be worried about webhook related customization.

@jan-est There's the @ardaguclu PR #865 that is in a pretty final stage

**Comment by jan-est** [comment]
We didn't need to do any changes in BMO, since we took BMO deployment out from CAPM3 in [242](https://github.com/metal3-io/cluster-api-provider-metal3/pull/242)
