### ISSUE TITLE
Status subresource is getting big to fit in the annotation with many multipath disks

### ISSUE THREAD

**Issue by fmuyassarov** [metal3-io/baremetal-operator#952]
As part of pivoting operation, we are storing bareMetalHost status subresource data in the `baremetalhost.metal3.io/status` annotation so that BMO in the target cluster can continue reconciliation from point it was before pivoting. In some cases, where there are quite many multipath disks attached to a BMH, e.g, 800 then the BMH `metadata.annotations` field becomes too big, because it stores storage entry for each and every disk regardless of multipath. The problem with that is - there is a limit on how much data can be stored in `metadata` field and is currently 262144 bytes.

In one of our deployments we are hitting the issue with this limited size because of big number of multipath disks
`metadata.annotations: Too long: must have at most 262144 bytes`

Any thoughts on how to avoid it?

A couple of things we were thinking:
1. Don't store all the disks entries for multipath disks
2. Increase the data limit for the metadata field during CRD generation (not sure if possible to do it via some flags). I've started a discussion with Kubebuilder folks on this

As a workaround, based on https://github.com/argoproj/argo-cd/issues/5704#issuecomment-792337798
- `kubectl create -f`  can be used instead if `kubect apply -f`   if the resource is being created 1st time
- ` kubectl replace -f` can be used instead of `kubect apply -f`   if the resource is being created not 1st time

Ref: https://github.com/metal3-io/baremetal-operator/blob/master/docs/statusAnnotation.md

**Comment by fmuyassarov** [comment]
> 2. Increase the data limit for the metadata field during CRD generation (not sure if possible to do it via some flags). I've started a discussion with Kubebuilder folks on this
>
Apparently it's not possible because it is a global limit

**Comment by fmuyassarov** [comment]
I will close it here because it is more related to CAPM3 rather than BMO.

Please see the discussion in https://github.com/metal3-io/cluster-api-provider-metal3/issues/266

/close

**Comment by zaneb** [comment]
As discussed in the meeting today, I think in the long term the answer is to move this data to a separate CRD so that we don't have to include it in the status annotation.

In the meantime, collapsing the multipath disks (whatever those are) seems like a reasonable approach. You could make an argument that that should be done in ironic-python-agent even /cc @dtantsur.

**Comment by fmuyassarov** [comment]
@zaneb thanks. I've copy pasted your comment on the active discussion in CAPM3 repo. Please see https://github.com/metal3-io/cluster-api-provider-metal3/issues/266

**Comment by dtantsur** [comment]
> In the meantime, collapsing the multipath disks (whatever those are) seems like a reasonable approach. You could make an argument that that should be done in ironic-python-agent even

It may make sense indeed.
