### ISSUE TITLE
Support Ironic hardware driver properties to be configurable

### ISSUE THREAD

**Issue by chatla-telekom** [metal3-io/baremetal-operator#956]
Currently,  users do not have the possibility to configure the properties of BMC Drivers' Interfaces like boot inferface, management interface, etc. as they are hard coded in BMO. By allowing these properties to be configurable via a config file or environment variables, it would allow users to adapt BMO for custom use cases.

**Comment by zaneb** [comment]
A design goal of metal³ is not to expose the implementation details of ironic in the BaremetalHost API.
Note that it is possible to register your own BMC drivers in go code, or to propose additional drivers upstream.

**Comment by chatla-telekom** [comment]
But what if we would want to use a different configuration for an existing driver itself? For example, the ilo5 driver in the code is configured to use "ilo-ipxe" boot interface

`func (a *iLO5AccessDetails) BootInterface() string {
	return "ilo-ipxe"
}`

but this negates the possbility of having another boot interface for the same driver like "ilo-uefi-https".

**Comment by dtantsur** [comment]
> possbility of having another boot interface for the same driver like "ilo-uefi-https".

I think this particular case may justify a new driver.

**Comment by chatla-telekom** [comment]
The idea is not to expose the Ironic Hardware details in the BareMetalHost API but configure it in a config file like ironic.env or define a new config file for example, driver.env to specify the custom properties of the driver interfaces:

```
BOOT_INTERFACE_TYPE=ilo-uefi-https
MANAGEMENT_INTERFACE_TYPE=
POWER_INTERFACE_TYPE=
RAID_INTERFACE_TYPE=ilo5
VENDOR_INTERFACE_TYPE=
```
and in the go code we could have a condition to check if a custom configuration is defined, if not we can use the default properties of the driver interfaces. 

```
func (a *iLO5AccessDetails) BootInterface(bootInterfaceType string) string {
	if bootInterfaceType != "" {
		return bootInterfaceType

	}
	return "ilo-ipxe"
}
```

This way, we can reuse the existing BMC drivers itself instead of creating new ones for different properties.

**Comment by zaneb** [comment]
We discussed this a bit in the community meeting, so capturing some notes here.

None of these fields are currently relying on programming logic, so it would make sense to be able to load the config for each driver from a file. For example, the ilo5 driver could read its config from `/opt/metal3/bmc-config/ilo5.yaml` or something, and fall back to the defaults in code for options that are not specified there.
