### ISSUE TITLE
Add prometheus metric for provisioner not ready

### ISSUE THREAD

**Issue by zaneb** [metal3-io/baremetal-operator#960]
Ironic not being ready is an obvious thing that folks might want to alert on, so add a Prometheus metric for when `prov.IsReady()` return false.

**Comment by thevibhu** [comment]
I am interested in this, can I take up this issue?

**Comment by thevibhu** [comment]
@zaneb Could you please explain the issue a little bit more and let me know how can I run/test my code?

**Comment by zaneb** [comment]
Metrics are defined here: https://github.com/metal3-io/baremetal-operator/blob/master/controllers/metal3.io/metrics.go
`IsReady()` is called here: https://github.com/metal3-io/baremetal-operator/blob/master/controllers/metal3.io/baremetalhost_controller.go#L226
The metrics URL for Prometheus is printed to the console at startup.
