### ISSUE TITLE
Some drivers return false from `NeedsMAC()` though they need a MAC to Adopt

### ISSUE THREAD

**Issue by zaneb** [metal3-io/baremetal-operator#979]
Some bmc drivers require a `BootMACAddress` to be set in order to identify the host. (For example, the IPMI driver when used with libvirt requires this.) These drivers return `true` from the method `NeedsMAC()`.

Other drivers can successfully inspect and provision without a `BootMACAddress` (For example, the IPMI driver when used with physical hardware.) These drivers return `false` from the method `NeedsMAC()`.

_However_, some drivers - including but possibly not limited to IPMI - return `false` but actually do need a boot MAC address set to adopt (which happens if the ironic Pod is relocated to a different node and thus the DB has to be rebuilt). So while they appear to work without one, in fact they'll fail at some point in the future when the Pod moves around.

Different ironic drivers have different requirements, so we have to look into them more deeply. Original discussion: https://github.com/openshift/cluster-baremetal-operator/pull/195#discussion_r706206348

By the time we get to adopting we should have the HardwareDetails in most cases, so perhaps we can obtain a MAC address from there and avoid requiring one from the start.

**Comment by dtantsur** [comment]
Have you tested it recently? The adoption validation has changed.

**Comment by hardys** [comment]
> Have you tested it recently? The adoption validation has changed.

I'm not aware of recent testing - can you confirm exactly when/which release the adoption validation changed?

This stems from previous problems discussed via https://github.com/metal3-io/baremetal-operator/issues/580 and in particular https://bugzilla.redhat.com/show_bug.cgi?id=1854142 where we found that after a controlplane outage, every worker failed to adopt due to a missing `bootMACAddress`.

**Comment by dtantsur** [comment]
Okay, I've checked: we do require MAC address for adoption. That being said, I don't think it's valid to change `NeedsMac` because it will make MAC address required also on normal enrollment (where it can be filled in by inspection). I think we just say that MAC address is always needed on adoption, wdyt?

**Comment by zaneb** [comment]
Adoption needs to always work transparently otherwise the ironic DB is not really ephemeral.

We could use a MAC address found from HardwareDetails for inspection when one is not provided in the BMH (we don't currently). I agree that if _every_ driver needs a MAC to adopt then it doesn't make sense to change all of the `NeedsMAC()` methods to return true.

If inspection is skipped and the HardwareDetails are not filled in by other means this would still present a problem, but maybe we can say that is unusual enough not to bother with.

**Comment by hardys** [comment]
> Adoption needs to always work transparently otherwise the ironic DB is not really ephemeral.
> 
> We could use a MAC address found from HardwareDetails for inspection when one is not provided in the BMH (we don't currently). I agree that if _every_ driver needs a MAC to adopt then it doesn't make sense to change all of the `NeedsMAC()` methods to return true.
> 
> If inspection is skipped and the HardwareDetails are not filled in by other means this would still present a problem, but maybe we can say that is unusual enough not to bother with.

This sounds like a reasonable compromise to me - no impact to the existing API (`bootMACAddress` remains optional on drivers which don't require it for deployment) but if we fall back to using `status.hardware` to avoid the adopt failure, that seems likely to solve the majority of deployed-then-adopt-failed cases
